export const babyRomperPatternMaster = [
  {
    id: "baby-romper-front-body",
    name: "Front Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 1,
    description:
      "Primary front body panel forming the chest, abdomen, front rise and upper leg areas of the baby romper.",
  },
  {
    id: "baby-romper-back-body",
    name: "Back Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 2,
    description:
      "Primary back body panel forming the back, seat, rear rise and upper leg areas of the baby romper.",
  },
  {
    id: "baby-romper-left-front-body",
    name: "Left Front Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Optional left front panel used in wrap-front, asymmetric, colour-blocked or opening-front romper construction.",
  },
  {
    id: "baby-romper-right-front-body",
    name: "Right Front Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional right front panel used in wrap-front, asymmetric, colour-blocked or opening-front romper construction.",
  },
  {
    id: "baby-romper-left-back-body",
    name: "Left Back Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional left back panel used in centre-back opening, shaped, panelled or colour-blocked romper construction.",
  },
  {
    id: "baby-romper-right-back-body",
    name: "Right Back Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional right back panel used in centre-back opening, shaped, panelled or colour-blocked romper construction.",
  },
  {
    id: "baby-romper-front-yoke",
    name: "Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 7,
    description:
      "Optional upper front yoke used for style shaping, gathering, decoration or contrast fabric.",
  },
  {
    id: "baby-romper-back-yoke",
    name: "Back Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 8,
    description:
      "Optional upper back yoke used for shoulder stability, style shaping or decorative construction.",
  },
  {
    id: "baby-romper-left-front-yoke",
    name: "Left Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional left front yoke used in asymmetric or panelled romper styles.",
  },
  {
    id: "baby-romper-right-front-yoke",
    name: "Right Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Optional right front yoke used in asymmetric or panelled romper styles.",
  },
  {
    id: "baby-romper-centre-front-panel",
    name: "Centre Front Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Optional central front insert used for decoration, opening construction, embroidery or colour blocking.",
  },
  {
    id: "baby-romper-centre-back-panel",
    name: "Centre Back Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Optional central back insert used for shaping, opening construction or decorative treatment.",
  },
  {
    id: "baby-romper-left-side-panel",
    name: "Left Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional left side panel used for shaping, contrast fabric, ventilation or fit adjustment.",
  },
  {
    id: "baby-romper-right-side-panel",
    name: "Right Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Optional right side panel used for shaping, contrast fabric, ventilation or fit adjustment.",
  },
  {
    id: "baby-romper-front-waist-panel",
    name: "Front Waist Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 15,
    description:
      "Optional front waist section joining the bodice and lower romper body.",
  },
  {
    id: "baby-romper-back-waist-panel",
    name: "Back Waist Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 16,
    description:
      "Optional back waist section providing fit control and joining the upper and lower body.",
  },
  {
    id: "baby-romper-waistband",
    name: "Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional continuous waistband providing shaping, elastic containment or decorative separation.",
  },
  {
    id: "baby-romper-waist-elastic-casing",
    name: "Waist Elastic Casing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional casing containing inserted elastic around the waist.",
  },
  {
    id: "baby-romper-front-crotch-panel",
    name: "Front Crotch Panel",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Shaped front crotch section providing diaper room, comfort and lower-body fit.",
  },
  {
    id: "baby-romper-back-crotch-panel",
    name: "Back Crotch Panel",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Shaped back crotch section providing seat depth, diaper accommodation and movement.",
  },
  {
    id: "baby-romper-crotch-gusset",
    name: "Crotch Gusset",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Primary gusset inserted between the legs to improve mobility, comfort and seam strength.",
  },
  {
    id: "baby-romper-crotch-gusset-lining",
    name: "Crotch Gusset Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional soft inner lining improving comfort and hygiene inside the crotch gusset.",
  },
  {
    id: "baby-romper-crotch-opening-facing",
    name: "Crotch Opening Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional pair of facings clean-finishing and stabilising the crotch opening.",
  },
  {
    id: "baby-romper-crotch-snap-placket-front",
    name: "Front Crotch Snap Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional reinforced front placket supporting snap fasteners for diaper access.",
  },
  {
    id: "baby-romper-crotch-snap-placket-back",
    name: "Back Crotch Snap Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional reinforced back placket supporting the matching snap-fastener components.",
  },
  {
    id: "baby-romper-crotch-snap-reinforcements",
    name: "Crotch Snap Reinforcements",
    required: false,
    cutQuantity: 6,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional reinforcement patches supporting snap fasteners along the crotch opening.",
  },
  {
    id: "baby-romper-left-leg",
    name: "Left Leg",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional separate left leg section used in long-leg, short-leg or panelled romper construction.",
  },
  {
    id: "baby-romper-right-leg",
    name: "Right Leg",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional separate right leg section used in long-leg, short-leg or panelled romper construction.",
  },
  {
    id: "baby-romper-left-front-leg",
    name: "Left Front Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional left front leg panel used for articulation, reinforcement or contrast styling.",
  },
  {
    id: "baby-romper-right-front-leg",
    name: "Right Front Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Optional right front leg panel used for articulation, reinforcement or contrast styling.",
  },
  {
    id: "baby-romper-left-back-leg",
    name: "Left Back Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Optional left back leg panel supporting seat-to-leg contour and movement.",
  },
  {
    id: "baby-romper-right-back-leg",
    name: "Right Back Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional right back leg panel supporting seat-to-leg contour and movement.",
  },
  {
    id: "baby-romper-left-leg-cuff",
    name: "Left Leg Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Optional knitted or self-fabric cuff finishing the left leg opening.",
  },
  {
    id: "baby-romper-right-leg-cuff",
    name: "Right Leg Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional knitted or self-fabric cuff finishing the right leg opening.",
  },
  {
    id: "baby-romper-leg-opening-binding",
    name: "Leg Opening Binding",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional stretch binding strips finishing both leg openings.",
  },
  {
    id: "baby-romper-leg-elastic-casings",
    name: "Leg Elastic Casings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional casings containing elastic around both leg openings.",
  },
  {
    id: "baby-romper-left-foot",
    name: "Left Attached Foot",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Optional enclosed left foot section used in footed baby romper construction.",
  },
  {
    id: "baby-romper-right-foot",
    name: "Right Attached Foot",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Optional enclosed right foot section used in footed baby romper construction.",
  },
  {
    id: "baby-romper-left-sole",
    name: "Left Sole",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional shaped sole panel completing the underside of the left attached foot.",
  },
  {
    id: "baby-romper-right-sole",
    name: "Right Sole",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional shaped sole panel completing the underside of the right attached foot.",
  },
  {
    id: "baby-romper-left-toe",
    name: "Left Toe Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional shaped toe panel improving fit and volume in the left attached foot.",
  },
  {
    id: "baby-romper-right-toe",
    name: "Right Toe Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional shaped toe panel improving fit and volume in the right attached foot.",
  },
  {
    id: "baby-romper-left-heel",
    name: "Left Heel Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional shaped heel panel improving fit in the left attached foot.",
  },
  {
    id: "baby-romper-right-heel",
    name: "Right Heel Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional shaped heel panel improving fit in the right attached foot.",
  },
  {
    id: "baby-romper-foot-grip-backing",
    name: "Foot Grip Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional stabilising sole pieces supporting anti-slip print or silicone grip application.",
  },
  {
    id: "baby-romper-short-sleeves",
    name: "Short Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional pair of short sleeves used in warm-weather or basic baby romper styles.",
  },
  {
    id: "baby-romper-long-sleeves",
    name: "Long Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional pair of long sleeves providing full arm coverage.",
  },
  {
    id: "baby-romper-raglan-sleeves",
    name: "Raglan Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional pair of raglan sleeves extending to the neckline for comfort and mobility.",
  },
  {
    id: "baby-romper-left-raglan-sleeve",
    name: "Left Raglan Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional anatomically or decoratively shaped left raglan sleeve.",
  },
  {
    id: "baby-romper-right-raglan-sleeve",
    name: "Right Raglan Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional anatomically or decoratively shaped right raglan sleeve.",
  },
  {
    id: "baby-romper-sleeve-cuffs",
    name: "Sleeve Cuffs",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional knitted or self-fabric cuffs finishing the sleeve openings.",
  },
  {
    id: "baby-romper-foldover-mitten-cuffs",
    name: "Foldover Mitten Cuffs",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Optional extended sleeve cuffs that fold over the hands to form protective mittens.",
  },
  {
    id: "baby-romper-mitten-cuff-linings",
    name: "Foldover Mitten Cuff Linings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Optional soft inner layers completing foldover mitten cuffs.",
  },
  {
    id: "baby-romper-sleeve-opening-binding",
    name: "Sleeve Opening Binding",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Optional stretch binding strips finishing sleeveless or cap-sleeve armholes.",
  },
  {
    id: "baby-romper-neckband",
    name: "Neckband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Primary knitted or self-fabric band finishing and controlling the neckline.",
  },
  {
    id: "baby-romper-front-neck-binding",
    name: "Front Neck Binding",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Optional binding strip finishing the front neckline.",
  },
  {
    id: "baby-romper-back-neck-binding",
    name: "Back Neck Binding",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Optional binding strip finishing the back neckline.",
  },
  {
    id: "baby-romper-neck-facing-front",
    name: "Front Neck Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 58,
    description:
      "Optional shaped facing clean-finishing and stabilising the front neckline.",
  },
  {
    id: "baby-romper-neck-facing-back",
    name: "Back Neck Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 59,
    description:
      "Optional shaped facing clean-finishing and stabilising the back neckline.",
  },
  {
    id: "baby-romper-envelope-neck-left",
    name: "Left Envelope Shoulder Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 60,
    description:
      "Optional overlapping left shoulder extension used in envelope-neck baby garments.",
  },
  {
    id: "baby-romper-envelope-neck-right",
    name: "Right Envelope Shoulder Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 61,
    description:
      "Optional overlapping right shoulder extension used in envelope-neck baby garments.",
  },
  {
    id: "baby-romper-envelope-neck-facings",
    name: "Envelope Shoulder Facings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 62,
    description:
      "Optional facings stabilising and finishing the overlapping envelope shoulder sections.",
  },
  {
    id: "baby-romper-left-shoulder-placket",
    name: "Left Shoulder Placket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional paired placket pieces forming a snap or button opening at the left shoulder.",
  },
  {
    id: "baby-romper-right-shoulder-placket",
    name: "Right Shoulder Placket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 64,
    description:
      "Optional paired placket pieces forming a snap or button opening at the right shoulder.",
  },
  {
    id: "baby-romper-shoulder-placket-reinforcements",
    name: "Shoulder Placket Reinforcements",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 65,
    description:
      "Optional reinforcement pieces supporting snap, button or buttonhole placement on shoulder plackets.",
  },
  {
    id: "baby-romper-front-opening-left-placket",
    name: "Left Front Opening Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 66,
    description:
      "Optional left front placket forming one side of a centre-front opening.",
  },
  {
    id: "baby-romper-front-opening-right-placket",
    name: "Right Front Opening Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 67,
    description:
      "Optional right front placket forming the opposite side of a centre-front opening.",
  },
  {
    id: "baby-romper-front-placket-interfacing",
    name: "Front Placket Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 68,
    description:
      "Optional reinforcement stabilising the front opening plackets.",
  },
  {
    id: "baby-romper-back-opening-left-placket",
    name: "Left Back Opening Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 69,
    description:
      "Optional left back placket forming one side of a centre-back opening.",
  },
  {
    id: "baby-romper-back-opening-right-placket",
    name: "Right Back Opening Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 70,
    description:
      "Optional right back placket forming the opposite side of a centre-back opening.",
  },
  {
    id: "baby-romper-back-placket-interfacing",
    name: "Back Placket Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 71,
    description:
      "Optional reinforcement stabilising the back opening plackets.",
  },
  {
    id: "baby-romper-front-zip-facings",
    name: "Front Zip Facings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 72,
    description:
      "Optional paired facings stabilising and finishing a centre-front zip opening.",
  },
  {
    id: "baby-romper-inner-zip-guard",
    name: "Inner Zip Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 73,
    description:
      "Optional protective strip positioned behind the zip to prevent skin contact and snagging.",
  },
  {
    id: "baby-romper-zip-chin-guard",
    name: "Zip Chin Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 74,
    description:
      "Optional soft protective piece covering the upper zip end near the baby's chin.",
  },
  {
    id: "baby-romper-asymmetric-wrap-left",
    name: "Left Wrap Front",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 75,
    description:
      "Optional left overlapping front panel used in kimono or wrap-style baby rompers.",
  },
  {
    id: "baby-romper-asymmetric-wrap-right",
    name: "Right Wrap Front",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 76,
    description:
      "Optional right underlapping front panel used in kimono or wrap-style baby rompers.",
  },
  {
    id: "baby-romper-wrap-edge-binding",
    name: "Wrap Edge Binding",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 77,
    description:
      "Optional continuous binding finishing the neckline and front edges of a wrap romper.",
  },
  {
    id: "baby-romper-left-internal-tie",
    name: "Left Internal Tie",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 78,
    description:
      "Optional internal tie securing the underlap of a wrap-style romper.",
  },
  {
    id: "baby-romper-right-external-tie",
    name: "Right External Tie",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 79,
    description:
      "Optional external tie securing the outer wrap panel.",
  },
  {
    id: "baby-romper-collar-upper",
    name: "Upper Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 80,
    description:
      "Optional upper collar panel forming a flat, Peter Pan or shirt-style collar.",
  },
  {
    id: "baby-romper-collar-under",
    name: "Under Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 81,
    description:
      "Optional under-collar panel completing the collar construction.",
  },
  {
    id: "baby-romper-collar-interfacing",
    name: "Collar Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 82,
    description:
      "Optional lightweight reinforcement stabilising the collar.",
  },
  {
    id: "baby-romper-hood-centre",
    name: "Hood Centre Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 83,
    description:
      "Optional centre hood panel creating crown depth and shape.",
  },
  {
    id: "baby-romper-hood-left-side",
    name: "Left Hood Side",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 84,
    description:
      "Optional left side hood panel forming the left hood profile.",
  },
  {
    id: "baby-romper-hood-right-side",
    name: "Right Hood Side",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 85,
    description:
      "Optional right side hood panel forming the right hood profile.",
  },
  {
    id: "baby-romper-hood-lining-centre",
    name: "Hood Centre Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 86,
    description:
      "Optional soft lining panel covering the inside centre of the hood.",
  },
  {
    id: "baby-romper-hood-lining-sides",
    name: "Hood Side Linings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 87,
    description:
      "Optional left and right lining panels completing the hood interior.",
  },
  {
    id: "baby-romper-hood-opening-band",
    name: "Hood Opening Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 88,
    description:
      "Optional knitted or self-fabric band finishing the hood opening.",
  },
  {
    id: "baby-romper-hood-ear-pieces",
    name: "Decorative Hood Ears",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 89,
    description:
      "Optional upper and under pieces forming decorative animal ears on the hood.",
  },
  {
    id: "baby-romper-hood-ear-interfacing",
    name: "Hood Ear Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 90,
    description:
      "Optional lightweight support pieces stabilising decorative hood ears.",
  },
  {
    id: "baby-romper-chest-pocket",
    name: "Chest Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 91,
    description:
      "Optional small patch pocket positioned on the front chest.",
  },
  {
    id: "baby-romper-kangaroo-pocket",
    name: "Kangaroo Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 92,
    description:
      "Optional large front pocket with openings at both sides.",
  },
  {
    id: "baby-romper-left-side-pocket",
    name: "Left Side Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 93,
    description:
      "Optional small pocket positioned at the left side of the romper.",
  },
  {
    id: "baby-romper-right-side-pocket",
    name: "Right Side Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 94,
    description:
      "Optional small pocket positioned at the right side of the romper.",
  },
  {
    id: "baby-romper-pocket-opening-binding",
    name: "Pocket Opening Binding",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 95,
    description:
      "Optional binding strips finishing stretch pocket openings.",
  },
  {
    id: "baby-romper-front-body-lining",
    name: "Front Body Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 96,
    description:
      "Optional soft lining panel covering the inside front body.",
  },
  {
    id: "baby-romper-back-body-lining",
    name: "Back Body Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 97,
    description:
      "Optional soft lining panel covering the inside back body.",
  },
  {
    id: "baby-romper-sleeve-linings",
    name: "Sleeve Linings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 98,
    description:
      "Optional soft lining pieces covering the inside of both sleeves.",
  },
  {
    id: "baby-romper-thermal-front-lining",
    name: "Thermal Front Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 99,
    description:
      "Optional insulating layer positioned inside the front body.",
  },
  {
    id: "baby-romper-thermal-back-lining",
    name: "Thermal Back Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 100,
    description:
      "Optional insulating layer positioned inside the back body.",
  },
  {
    id: "baby-romper-knee-reinforcements",
    name: "Knee Reinforcements",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 101,
    description:
      "Optional abrasion-resistant patches protecting the knees of crawling babies.",
  },
  {
    id: "baby-romper-seat-reinforcement",
    name: "Seat Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 102,
    description:
      "Optional durable panel reinforcing the seat and diaper area.",
  },
  {
    id: "baby-romper-elbow-reinforcements",
    name: "Elbow Reinforcements",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 103,
    description:
      "Optional abrasion-resistant patches protecting both elbow areas.",
  },
  {
    id: "baby-romper-neck-tape",
    name: "Back Neck Tape",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 104,
    description:
      "Optional soft tape covering and stabilising the back neck seam.",
  },
  {
    id: "baby-romper-shoulder-seam-covers",
    name: "Shoulder Seam Covers",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 105,
    description:
      "Optional soft strips covering shoulder seams to reduce irritation.",
  },
  {
    id: "baby-romper-side-seam-covers",
    name: "Side Seam Covers",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 106,
    description:
      "Optional internal strips covering side seams for comfort and clean finishing.",
  },
  {
    id: "baby-romper-crotch-seam-cover",
    name: "Crotch Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 107,
    description:
      "Optional soft internal strip covering the crotch seam.",
  },
  {
    id: "baby-romper-chest-logo-backing",
    name: "Chest Logo Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 108,
    description:
      "Optional internal support patch behind chest embroidery, appliqué or branding.",
  },
  {
    id: "baby-romper-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 109,
    description:
      "Optional backing patches supporting embroidery, appliqué, badges or decorative attachments.",
  },
  {
    id: "baby-romper-label-backing",
    name: "Brand Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 110,
    description:
      "Optional support piece for a woven, printed or heat-transfer brand label.",
  },
  {
    id: "baby-romper-care-label-backing",
    name: "Care Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 111,
    description:
      "Optional internal support piece for care, size and fibre-content labels.",
  },
  {
    id: "baby-romper-snap-backing",
    name: "Snap Fastener Backing",
    required: false,
    cutQuantity: 6,
    cutOnFold: false,
    custom: false,
    sequence: 112,
    description:
      "Optional reinforcement patches supporting snap fasteners at openings and closures.",
  },
  {
    id: "baby-romper-button-backing",
    name: "Button Attachment Backing",
    required: false,
    cutQuantity: 3,
    cutOnFold: false,
    custom: false,
    sequence: 113,
    description:
      "Optional reinforcement patches positioned behind button attachment points.",
  },
  {
    id: "baby-romper-buttonhole-backing",
    name: "Buttonhole Backing",
    required: false,
    cutQuantity: 3,
    cutOnFold: false,
    custom: false,
    sequence: 114,
    description:
      "Optional reinforcement patches stabilising buttonhole positions.",
  },
];

export default babyRomperPatternMaster;