export const canvasJacketPatternMaster = [
  {
    id: "canvas-jacket-left-front",
    name: "Left Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Main left front canvas shell panel including shoulder, armhole, side seam, centre-front opening and hem shaping.",
  },
  {
    id: "canvas-jacket-right-front",
    name: "Right Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Main right front canvas shell panel including shoulder, armhole, side seam, centre-front opening and hem shaping.",
  },
  {
    id: "canvas-jacket-back",
    name: "Back",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 3,
    description:
      "Main back canvas panel cut on the centre-back fold with shoulder, armhole, side seam and hem shaping.",
  },
  {
    id: "canvas-jacket-left-front-yoke",
    name: "Left Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional upper left front yoke used for reinforcement, styling, seam relocation or colour-block construction.",
  },
  {
    id: "canvas-jacket-right-front-yoke",
    name: "Right Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional upper right front yoke used for reinforcement, styling, seam relocation or colour-block construction.",
  },
  {
    id: "canvas-jacket-back-yoke",
    name: "Back Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 6,
    description:
      "Optional upper back yoke improving shoulder strength, structure and workwear appearance.",
  },
  {
    id: "canvas-jacket-left-front-side-panel",
    name: "Left Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Optional shaped left front side panel used for fit control, reinforcement or contrast construction.",
  },
  {
    id: "canvas-jacket-right-front-side-panel",
    name: "Right Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Optional shaped right front side panel used for fit control, reinforcement or contrast construction.",
  },
  {
    id: "canvas-jacket-left-back-side-panel",
    name: "Left Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional shaped left back side panel improving fit, movement and functional seam placement.",
  },
  {
    id: "canvas-jacket-right-back-side-panel",
    name: "Right Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Optional shaped right back side panel improving fit, movement and functional seam placement.",
  },
  {
    id: "canvas-jacket-left-upper-sleeve",
    name: "Left Upper Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Main left upper sleeve panel shaped for shoulder fit, elbow movement and heavy-duty workwear construction.",
  },
  {
    id: "canvas-jacket-right-upper-sleeve",
    name: "Right Upper Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Main right upper sleeve panel shaped for shoulder fit, elbow movement and heavy-duty workwear construction.",
  },
  {
    id: "canvas-jacket-left-under-sleeve",
    name: "Left Under Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Left under-sleeve section completing the two-piece sleeve and supporting ergonomic arm movement.",
  },
  {
    id: "canvas-jacket-right-under-sleeve",
    name: "Right Under Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Right under-sleeve section completing the two-piece sleeve and supporting ergonomic arm movement.",
  },
  {
    id: "canvas-jacket-left-elbow-reinforcement",
    name: "Left Elbow Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional abrasion-resistant canvas reinforcement panel protecting the left elbow.",
  },
  {
    id: "canvas-jacket-right-elbow-reinforcement",
    name: "Right Elbow Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional abrasion-resistant canvas reinforcement panel protecting the right elbow.",
  },
  {
    id: "canvas-jacket-left-shoulder-reinforcement",
    name: "Left Shoulder Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional double-layer reinforcement protecting the left shoulder from tools, straps and repeated abrasion.",
  },
  {
    id: "canvas-jacket-right-shoulder-reinforcement",
    name: "Right Shoulder Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional double-layer reinforcement protecting the right shoulder from tools, straps and repeated abrasion.",
  },
  {
    id: "canvas-jacket-left-front-facing",
    name: "Left Front Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Left front facing finishing and stabilising the centre-front opening, neckline and fastening area.",
  },
  {
    id: "canvas-jacket-right-front-facing",
    name: "Right Front Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Right front facing finishing and stabilising the centre-front opening, neckline and fastening area.",
  },
  {
    id: "canvas-jacket-front-facing-interfacing",
    name: "Front Facing Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Optional reinforcement pieces supporting both front facings and centre-front fastenings.",
  },
  {
    id: "canvas-jacket-outer-storm-flap",
    name: "Outer Storm Flap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional outer flap covering the centre-front zip or snap fastening for added wind protection.",
  },
  {
    id: "canvas-jacket-inner-storm-flap",
    name: "Inner Storm Flap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional inner flap positioned behind the centre-front zip to reduce wind entry.",
  },
  {
    id: "canvas-jacket-zip-guard",
    name: "Zip Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional internal guard protecting the wearer from the centre-front zip.",
  },
  {
    id: "canvas-jacket-upper-collar",
    name: "Upper Collar",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 25,
    description:
      "Outer collar section providing neckline structure, coverage and characteristic work-jacket styling.",
  },
  {
    id: "canvas-jacket-under-collar",
    name: "Under Collar",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 26,
    description:
      "Under-collar section supporting collar roll, shape and clean construction.",
  },
  {
    id: "canvas-jacket-collar-interfacing",
    name: "Collar Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 27,
    description:
      "Optional reinforcement stabilising the collar and maintaining shape during repeated industrial use.",
  },
  {
    id: "canvas-jacket-corduroy-collar-overlay",
    name: "Corduroy Collar Overlay",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 28,
    description:
      "Optional contrast corduroy or soft-fabric upper-collar layer used in heritage canvas jackets.",
  },
  {
    id: "canvas-jacket-detachable-hood-centre",
    name: "Detachable Hood Centre Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional centre panel forming the crown of a detachable workwear hood.",
  },
  {
    id: "canvas-jacket-detachable-hood-left-side",
    name: "Detachable Hood Left Side",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Optional left side panel of a detachable hood.",
  },
  {
    id: "canvas-jacket-detachable-hood-right-side",
    name: "Detachable Hood Right Side",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Optional right side panel of a detachable hood.",
  },
  {
    id: "canvas-jacket-hood-facing",
    name: "Hood Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional facing used to clean-finish and reinforce the detachable hood opening.",
  },
  {
    id: "canvas-jacket-hood-attachment-tab",
    name: "Hood Attachment Tabs",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Optional tab pieces used to attach a removable hood to the collar or neckline.",
  },
  {
    id: "canvas-jacket-left-chest-pocket",
    name: "Left Chest Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional heavy-duty patch pocket positioned on the left chest.",
  },
  {
    id: "canvas-jacket-right-chest-pocket",
    name: "Right Chest Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional heavy-duty patch pocket positioned on the right chest.",
  },
  {
    id: "canvas-jacket-left-chest-pocket-flap",
    name: "Left Chest Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional upper and under flap pieces covering the left chest pocket.",
  },
  {
    id: "canvas-jacket-right-chest-pocket-flap",
    name: "Right Chest Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Optional upper and under flap pieces covering the right chest pocket.",
  },
  {
    id: "canvas-jacket-left-lower-pocket",
    name: "Left Lower Patch Pocket",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Main left lower utility patch pocket designed for storage and repeated industrial use.",
  },
  {
    id: "canvas-jacket-right-lower-pocket",
    name: "Right Lower Patch Pocket",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Main right lower utility patch pocket designed for storage and repeated industrial use.",
  },
  {
    id: "canvas-jacket-left-lower-pocket-flap",
    name: "Left Lower Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional upper and under flap pieces protecting the left lower pocket opening.",
  },
  {
    id: "canvas-jacket-right-lower-pocket-flap",
    name: "Right Lower Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional upper and under flap pieces protecting the right lower pocket opening.",
  },
  {
    id: "canvas-jacket-left-pocket-gusset",
    name: "Left Lower Pocket Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional expandable gusset increasing the capacity of the left lower utility pocket.",
  },
  {
    id: "canvas-jacket-right-pocket-gusset",
    name: "Right Lower Pocket Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional expandable gusset increasing the capacity of the right lower utility pocket.",
  },
  {
    id: "canvas-jacket-left-pocket-reinforcement",
    name: "Left Pocket Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional internal reinforcement supporting the left utility pocket attachment area.",
  },
  {
    id: "canvas-jacket-right-pocket-reinforcement",
    name: "Right Pocket Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional internal reinforcement supporting the right utility pocket attachment area.",
  },
  {
    id: "canvas-jacket-left-hand-warmer-pocket-bag",
    name: "Left Hand-Warmer Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional pair of pocket-bag sections forming a side-entry left hand-warmer pocket.",
  },
  {
    id: "canvas-jacket-right-hand-warmer-pocket-bag",
    name: "Right Hand-Warmer Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional pair of pocket-bag sections forming a side-entry right hand-warmer pocket.",
  },
  {
    id: "canvas-jacket-left-tool-pocket",
    name: "Left Tool Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional narrow utility pocket designed to hold a ruler, tool, pen or work accessory.",
  },
  {
    id: "canvas-jacket-right-tool-pocket",
    name: "Right Tool Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional narrow utility pocket designed to hold a ruler, tool, pen or work accessory.",
  },
  {
    id: "canvas-jacket-left-sleeve-pocket",
    name: "Left Sleeve Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional utility patch or zipped pocket positioned on the left sleeve.",
  },
  {
    id: "canvas-jacket-right-sleeve-pocket",
    name: "Right Sleeve Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional utility patch or zipped pocket positioned on the right sleeve.",
  },
  {
    id: "canvas-jacket-left-cuff",
    name: "Left Cuff",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Outer and inner left cuff sections finishing and controlling the sleeve opening.",
  },
  {
    id: "canvas-jacket-right-cuff",
    name: "Right Cuff",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Outer and inner right cuff sections finishing and controlling the sleeve opening.",
  },
  {
    id: "canvas-jacket-left-cuff-interfacing",
    name: "Left Cuff Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Optional reinforcement supporting the left cuff and fastening positions.",
  },
  {
    id: "canvas-jacket-right-cuff-interfacing",
    name: "Right Cuff Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Optional reinforcement supporting the right cuff and fastening positions.",
  },
  {
    id: "canvas-jacket-left-sleeve-placket",
    name: "Left Sleeve Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Optional placket piece used to finish and reinforce the left sleeve opening.",
  },
  {
    id: "canvas-jacket-right-sleeve-placket",
    name: "Right Sleeve Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Optional placket piece used to finish and reinforce the right sleeve opening.",
  },
  {
    id: "canvas-jacket-front-waistband-left",
    name: "Left Front Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 58,
    description:
      "Optional left front lower band used in trucker, bomber or short work-jacket construction.",
  },
  {
    id: "canvas-jacket-front-waistband-right",
    name: "Right Front Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 59,
    description:
      "Optional right front lower band used in trucker, bomber or short work-jacket construction.",
  },
  {
    id: "canvas-jacket-back-waistband",
    name: "Back Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 60,
    description:
      "Optional back lower band supporting a fitted, elasticated or structured jacket hem.",
  },
  {
    id: "canvas-jacket-left-side-adjuster-tab",
    name: "Left Waist Adjustment Tab",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 61,
    description:
      "Optional upper and under tab pieces used to adjust the left side waist.",
  },
  {
    id: "canvas-jacket-right-side-adjuster-tab",
    name: "Right Waist Adjustment Tab",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 62,
    description:
      "Optional upper and under tab pieces used to adjust the right side waist.",
  },
  {
    id: "canvas-jacket-left-front-lining",
    name: "Left Front Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional left front lining panel providing comfort and clean internal finishing.",
  },
  {
    id: "canvas-jacket-right-front-lining",
    name: "Right Front Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 64,
    description:
      "Optional right front lining panel providing comfort and clean internal finishing.",
  },
  {
    id: "canvas-jacket-back-lining",
    name: "Back Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 65,
    description:
      "Optional back lining panel covering internal seams and improving comfort.",
  },
  {
    id: "canvas-jacket-left-sleeve-lining",
    name: "Left Sleeve Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 66,
    description:
      "Optional left sleeve lining panel providing smooth dressing and seam coverage.",
  },
  {
    id: "canvas-jacket-right-sleeve-lining",
    name: "Right Sleeve Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 67,
    description:
      "Optional right sleeve lining panel providing smooth dressing and seam coverage.",
  },
  {
    id: "canvas-jacket-left-front-insulation",
    name: "Left Front Insulation",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 68,
    description:
      "Optional thermal insulation layer positioned between the left front shell and lining.",
  },
  {
    id: "canvas-jacket-right-front-insulation",
    name: "Right Front Insulation",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 69,
    description:
      "Optional thermal insulation layer positioned between the right front shell and lining.",
  },
  {
    id: "canvas-jacket-back-insulation",
    name: "Back Insulation",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 70,
    description:
      "Optional thermal insulation layer positioned between the back shell and lining.",
  },
  {
    id: "canvas-jacket-left-sleeve-insulation",
    name: "Left Sleeve Insulation",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 71,
    description:
      "Optional insulation layer positioned within the left sleeve.",
  },
  {
    id: "canvas-jacket-right-sleeve-insulation",
    name: "Right Sleeve Insulation",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 72,
    description:
      "Optional insulation layer positioned within the right sleeve.",
  },
  {
    id: "canvas-jacket-back-action-pleat-left",
    name: "Left Back Action Pleat",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 73,
    description:
      "Optional left action-pleat section providing additional shoulder and arm movement.",
  },
  {
    id: "canvas-jacket-back-action-pleat-right",
    name: "Right Back Action Pleat",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 74,
    description:
      "Optional right action-pleat section providing additional shoulder and arm movement.",
  },
  {
    id: "canvas-jacket-underarm-gusset-left",
    name: "Left Underarm Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 75,
    description:
      "Optional gusset improving mobility and reducing seam stress beneath the left arm.",
  },
  {
    id: "canvas-jacket-underarm-gusset-right",
    name: "Right Underarm Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 76,
    description:
      "Optional gusset improving mobility and reducing seam stress beneath the right arm.",
  },
  {
    id: "canvas-jacket-hanger-loop",
    name: "Internal Hanger Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 77,
    description:
      "Optional reinforced fabric loop used to hang the jacket securely.",
  },
  {
    id: "canvas-jacket-label-backing",
    name: "Brand Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 78,
    description:
      "Optional backing patch supporting a woven, leather or printed brand label.",
  },
  {
    id: "canvas-jacket-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 79,
    description:
      "Optional backing patches supporting embroidery, badges, logos, identification marks or heat transfers.",
  },
];

export default canvasJacketPatternMaster;