export const cardiganPatternMaster = [
  {
    id: "cardigan-left-front-body",
    name: "Left Front Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Main left front cardigan body panel including neckline, shoulder, armhole, side seam, centre-front opening and lower-edge shaping.",
  },
  {
    id: "cardigan-right-front-body",
    name: "Right Front Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Main right front cardigan body panel including neckline, shoulder, armhole, side seam, centre-front opening and lower-edge shaping.",
  },
  {
    id: "cardigan-back-body",
    name: "Back Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 3,
    description:
      "Main back cardigan body panel including back neckline, shoulders, armholes, side seams and lower-edge shaping.",
  },
  {
    id: "cardigan-left-back-body",
    name: "Left Back Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional separate left back body panel used for centre-back seamed, panelled or colour-block cardigan construction.",
  },
  {
    id: "cardigan-right-back-body",
    name: "Right Back Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional separate right back body panel used for centre-back seamed, panelled or colour-block cardigan construction.",
  },
  {
    id: "cardigan-left-front-yoke",
    name: "Left Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional upper left front yoke used for shaping, decorative knitting, reinforcement or contrast construction.",
  },
  {
    id: "cardigan-right-front-yoke",
    name: "Right Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Optional upper right front yoke used for shaping, decorative knitting, reinforcement or contrast construction.",
  },
  {
    id: "cardigan-back-yoke",
    name: "Back Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 8,
    description:
      "Optional upper back yoke supporting shoulder shaping, decorative knitting or contrast construction.",
  },
  {
    id: "cardigan-left-front-side-panel",
    name: "Left Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional shaped left front side panel used for fit control, colour blocking or engineered seam placement.",
  },
  {
    id: "cardigan-right-front-side-panel",
    name: "Right Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Optional shaped right front side panel used for fit control, colour blocking or engineered seam placement.",
  },
  {
    id: "cardigan-left-back-side-panel",
    name: "Left Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Optional shaped left back side panel improving contour, mobility and decorative seam positioning.",
  },
  {
    id: "cardigan-right-back-side-panel",
    name: "Right Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Optional shaped right back side panel improving contour, mobility and decorative seam positioning.",
  },
  {
    id: "cardigan-left-set-in-sleeve",
    name: "Left Set-In Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Main left set-in sleeve panel shaped for armhole compatibility, elbow movement and wrist taper.",
  },
  {
    id: "cardigan-right-set-in-sleeve",
    name: "Right Set-In Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Main right set-in sleeve panel shaped for armhole compatibility, elbow movement and wrist taper.",
  },
  {
    id: "cardigan-left-raglan-sleeve",
    name: "Left Raglan Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional left raglan sleeve extending from the neckline to the underarm for relaxed movement and casual styling.",
  },
  {
    id: "cardigan-right-raglan-sleeve",
    name: "Right Raglan Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional right raglan sleeve extending from the neckline to the underarm for relaxed movement and casual styling.",
  },
  {
    id: "cardigan-left-drop-shoulder-sleeve",
    name: "Left Drop-Shoulder Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional left sleeve designed for an extended shoulder seam and relaxed oversized cardigan silhouette.",
  },
  {
    id: "cardigan-right-drop-shoulder-sleeve",
    name: "Right Drop-Shoulder Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional right sleeve designed for an extended shoulder seam and relaxed oversized cardigan silhouette.",
  },
  {
    id: "cardigan-left-upper-sleeve",
    name: "Left Upper Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional upper section of a two-piece left sleeve used for shaping, contrast knitting or ergonomic fit.",
  },
  {
    id: "cardigan-right-upper-sleeve",
    name: "Right Upper Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Optional upper section of a two-piece right sleeve used for shaping, contrast knitting or ergonomic fit.",
  },
  {
    id: "cardigan-left-under-sleeve",
    name: "Left Under Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Optional under section completing a two-piece left sleeve and improving movement.",
  },
  {
    id: "cardigan-right-under-sleeve",
    name: "Right Under Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional under section completing a two-piece right sleeve and improving movement.",
  },
  {
    id: "cardigan-left-elbow-patch",
    name: "Left Elbow Patch",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional reinforcement or decorative patch positioned over the left elbow.",
  },
  {
    id: "cardigan-right-elbow-patch",
    name: "Right Elbow Patch",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional reinforcement or decorative patch positioned over the right elbow.",
  },
  {
    id: "cardigan-left-front-button-band",
    name: "Left Front Button Band",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Left front knitted, ribbed or self-fabric band supporting the buttonholes and finishing the centre-front opening.",
  },
  {
    id: "cardigan-right-front-button-band",
    name: "Right Front Button Band",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Right front knitted, ribbed or self-fabric band supporting the buttons and finishing the centre-front opening.",
  },
  {
    id: "cardigan-left-front-band-interfacing",
    name: "Left Front Band Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional reinforcement stabilising the left front buttonhole band and preventing excessive stretch.",
  },
  {
    id: "cardigan-right-front-band-interfacing",
    name: "Right Front Band Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional reinforcement stabilising the right front button band and fastening positions.",
  },
  {
    id: "cardigan-left-zip-facing",
    name: "Left Front Zip Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional left facing finishing and stabilising one side of a full-length front zip opening.",
  },
  {
    id: "cardigan-right-zip-facing",
    name: "Right Front Zip Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Optional right facing finishing and stabilising the opposite side of a full-length front zip opening.",
  },
  {
    id: "cardigan-inner-zip-guard",
    name: "Inner Zip Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Optional internal guard positioned behind the front zip to improve comfort and prevent snagging.",
  },
  {
    id: "cardigan-chin-guard",
    name: "Chin Guard",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional pair of knitted, fleece or self-fabric pieces protecting the chin from the zip slider.",
  },
  {
    id: "cardigan-continuous-neck-front-band",
    name: "Continuous Neck and Front Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Optional single continuous band extending around the neckline and down both centre-front edges.",
  },
  {
    id: "cardigan-back-neck-band",
    name: "Back Neck Band",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Knitted, ribbed or self-fabric band finishing and stabilising the back neckline between the front bands.",
  },
  {
    id: "cardigan-v-neck-left-band",
    name: "Left V-Neck Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional left band section forming and finishing one side of a V-neck cardigan opening.",
  },
  {
    id: "cardigan-v-neck-right-band",
    name: "Right V-Neck Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional right band section forming and finishing the opposite side of a V-neck cardigan opening.",
  },
  {
    id: "cardigan-v-neck-centre-reinforcement",
    name: "V-Neck Centre Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Optional reinforcement stabilising the lower point where the V-neck front bands meet.",
  },
  {
    id: "cardigan-shawl-collar-left",
    name: "Left Shawl Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Optional shaped left collar extension forming one half of a wide rolled shawl collar.",
  },
  {
    id: "cardigan-shawl-collar-right",
    name: "Right Shawl Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional shaped right collar extension forming the opposite half of a wide rolled shawl collar.",
  },
  {
    id: "cardigan-shawl-collar-back",
    name: "Shawl Collar Back",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 40,
    description:
      "Optional centre-back collar section joining the left and right shawl-collar extensions.",
  },
  {
    id: "cardigan-shawl-collar-inner-left",
    name: "Left Inner Shawl Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional inner left section completing and supporting a double-layer shawl collar.",
  },
  {
    id: "cardigan-shawl-collar-inner-right",
    name: "Right Inner Shawl Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional inner right section completing and supporting a double-layer shawl collar.",
  },
  {
    id: "cardigan-stand-collar-outer",
    name: "Outer Stand Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 43,
    description:
      "Optional outer stand-collar section providing raised neckline coverage and structure.",
  },
  {
    id: "cardigan-stand-collar-inner",
    name: "Inner Stand Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 44,
    description:
      "Optional inner stand-collar section completing and clean-finishing the raised neckline.",
  },
  {
    id: "cardigan-collar-interfacing",
    name: "Collar Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 45,
    description:
      "Optional reinforcement stabilising a structured shawl, stand or tailored cardigan collar.",
  },
  {
    id: "cardigan-left-cuff",
    name: "Left Sleeve Cuff",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Rib-knit, engineered or self-fabric cuff finishing and controlling the left sleeve opening.",
  },
  {
    id: "cardigan-right-cuff",
    name: "Right Sleeve Cuff",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Rib-knit, engineered or self-fabric cuff finishing and controlling the right sleeve opening.",
  },
  {
    id: "cardigan-left-extended-cuff",
    name: "Left Extended Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional long left cuff used for fold-back, thumb-hole or cold-weather cardigan construction.",
  },
  {
    id: "cardigan-right-extended-cuff",
    name: "Right Extended Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional long right cuff used for fold-back, thumb-hole or cold-weather cardigan construction.",
  },
  {
    id: "cardigan-left-thumbhole-cuff-insert",
    name: "Left Thumb-Hole Cuff Insert",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional shaped insert finishing and reinforcing the thumb opening in the left extended cuff.",
  },
  {
    id: "cardigan-right-thumbhole-cuff-insert",
    name: "Right Thumb-Hole Cuff Insert",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional shaped insert finishing and reinforcing the thumb opening in the right extended cuff.",
  },
  {
    id: "cardigan-left-front-hem-band",
    name: "Left Front Hem Band",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Left front lower rib, engineered knit or self-fabric band finishing and controlling the cardigan hem.",
  },
  {
    id: "cardigan-right-front-hem-band",
    name: "Right Front Hem Band",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Right front lower rib, engineered knit or self-fabric band finishing and controlling the cardigan hem.",
  },
  {
    id: "cardigan-back-hem-band",
    name: "Back Hem Band",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Back lower rib, engineered knit or self-fabric band finishing and controlling the cardigan hem.",
  },
  {
    id: "cardigan-continuous-hem-band",
    name: "Continuous Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Optional single continuous lower band used instead of separate front and back hem-band sections.",
  },
  {
    id: "cardigan-left-side-slit-facing",
    name: "Left Side Slit Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Optional pair of facing pieces reinforcing and clean-finishing the left hem side slit.",
  },
  {
    id: "cardigan-right-side-slit-facing",
    name: "Right Side Slit Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Optional pair of facing pieces reinforcing and clean-finishing the right hem side slit.",
  },
  {
    id: "cardigan-left-front-patch-pocket",
    name: "Left Front Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 58,
    description:
      "Optional knitted or self-fabric patch pocket positioned on the lower left front.",
  },
  {
    id: "cardigan-right-front-patch-pocket",
    name: "Right Front Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 59,
    description:
      "Optional knitted or self-fabric patch pocket positioned on the lower right front.",
  },
  {
    id: "cardigan-left-pocket-facing",
    name: "Left Patch Pocket Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 60,
    description:
      "Optional ribbed or self-fabric facing stabilising the opening of the left patch pocket.",
  },
  {
    id: "cardigan-right-pocket-facing",
    name: "Right Patch Pocket Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 61,
    description:
      "Optional ribbed or self-fabric facing stabilising the opening of the right patch pocket.",
  },
  {
    id: "cardigan-left-welt-pocket-welt",
    name: "Left Welt Pocket Welt",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 62,
    description:
      "Optional pair of welt pieces forming a structured left front pocket opening.",
  },
  {
    id: "cardigan-right-welt-pocket-welt",
    name: "Right Welt Pocket Welt",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional pair of welt pieces forming a structured right front pocket opening.",
  },
  {
    id: "cardigan-left-welt-pocket-bag",
    name: "Left Welt Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 64,
    description:
      "Optional pair of pocket-bag sections forming the complete left welt pocket.",
  },
  {
    id: "cardigan-right-welt-pocket-bag",
    name: "Right Welt Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 65,
    description:
      "Optional pair of pocket-bag sections forming the complete right welt pocket.",
  },
  {
    id: "cardigan-left-chest-pocket",
    name: "Left Chest Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 66,
    description:
      "Optional knitted or self-fabric patch pocket positioned on the left chest.",
  },
  {
    id: "cardigan-right-chest-pocket",
    name: "Right Chest Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 67,
    description:
      "Optional knitted or self-fabric patch pocket positioned on the right chest.",
  },
  {
    id: "cardigan-belt",
    name: "Waist Belt",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 68,
    description:
      "Optional knitted, ribbed or self-fabric belt used to close and shape a wrap cardigan.",
  },
  {
    id: "cardigan-left-belt-loop",
    name: "Left Belt Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 69,
    description:
      "Optional loop positioned at the left waist to retain and guide the cardigan belt.",
  },
  {
    id: "cardigan-right-belt-loop",
    name: "Right Belt Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 70,
    description:
      "Optional loop positioned at the right waist to retain and guide the cardigan belt.",
  },
  {
    id: "cardigan-left-internal-tie",
    name: "Left Internal Tie",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 71,
    description:
      "Optional internal tie securing the left front overlap in a wrap cardigan.",
  },
  {
    id: "cardigan-right-internal-tie",
    name: "Right Internal Tie",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 72,
    description:
      "Optional internal tie securing the right front overlap in a wrap cardigan.",
  },
  {
    id: "cardigan-front-lining-left",
    name: "Left Front Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 73,
    description:
      "Optional left front lining panel used in structured, bonded or wind-resistant cardigan construction.",
  },
  {
    id: "cardigan-front-lining-right",
    name: "Right Front Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 74,
    description:
      "Optional right front lining panel used in structured, bonded or wind-resistant cardigan construction.",
  },
  {
    id: "cardigan-back-lining",
    name: "Back Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 75,
    description:
      "Optional back lining panel covering internal construction and improving comfort.",
  },
  {
    id: "cardigan-left-sleeve-lining",
    name: "Left Sleeve Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 76,
    description:
      "Optional left sleeve lining panel providing smooth dressing and internal seam coverage.",
  },
  {
    id: "cardigan-right-sleeve-lining",
    name: "Right Sleeve Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 77,
    description:
      "Optional right sleeve lining panel providing smooth dressing and internal seam coverage.",
  },
  {
    id: "cardigan-left-front-windproof-membrane",
    name: "Left Front Windproof Membrane",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 78,
    description:
      "Optional membrane layer reducing wind penetration through the left front of a technical cardigan.",
  },
  {
    id: "cardigan-right-front-windproof-membrane",
    name: "Right Front Windproof Membrane",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 79,
    description:
      "Optional membrane layer reducing wind penetration through the right front of a technical cardigan.",
  },
  {
    id: "cardigan-back-windproof-membrane",
    name: "Back Windproof Membrane",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 80,
    description:
      "Optional membrane layer reducing wind penetration through the back of a technical cardigan.",
  },
  {
    id: "cardigan-left-shoulder-reinforcement",
    name: "Left Shoulder Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 81,
    description:
      "Optional reinforcement panel protecting the left shoulder from straps, abrasion or repeated wear.",
  },
  {
    id: "cardigan-right-shoulder-reinforcement",
    name: "Right Shoulder Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 82,
    description:
      "Optional reinforcement panel protecting the right shoulder from straps, abrasion or repeated wear.",
  },
  {
    id: "cardigan-left-shoulder-stay",
    name: "Left Shoulder Stay",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 83,
    description:
      "Optional stabilising strip preventing excessive stretch along the left shoulder seam.",
  },
  {
    id: "cardigan-right-shoulder-stay",
    name: "Right Shoulder Stay",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 84,
    description:
      "Optional stabilising strip preventing excessive stretch along the right shoulder seam.",
  },
  {
    id: "cardigan-back-neck-tape",
    name: "Back Neck Tape",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 85,
    description:
      "Optional stabilising tape or self-fabric strip covering and reinforcing the back neckline seam.",
  },
  {
    id: "cardigan-hanger-loop",
    name: "Internal Hanger Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 86,
    description:
      "Optional reinforced loop used to hang the cardigan without stretching the neckline.",
  },
  {
    id: "cardigan-button-backing-strip",
    name: "Button Backing Strip",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 87,
    description:
      "Optional internal support strip positioned behind the button attachment line.",
  },
  {
    id: "cardigan-buttonhole-backing-strip",
    name: "Buttonhole Backing Strip",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 88,
    description:
      "Optional internal support strip positioned behind the buttonhole line to prevent stretching.",
  },
  {
    id: "cardigan-front-decoration-backing",
    name: "Front Decoration Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 89,
    description:
      "Optional backing pieces supporting embroidery, appliqué, badges, logos or decorative motifs on both front panels.",
  },
  {
    id: "cardigan-back-decoration-backing",
    name: "Back Decoration Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 90,
    description:
      "Optional support patch positioned behind back embroidery, branding or decorative application.",
  },
  {
    id: "cardigan-label-backing",
    name: "Brand Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 91,
    description:
      "Optional backing piece supporting a woven, printed, leather or heat-transfer brand label.",
  },
];

export default cardiganPatternMaster;