export const cargoTrouserPatternMaster = [
  {
    id: "cargo-trouser-left-front-leg",
    name: "Left Front Leg",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Main left front leg panel including waist, hip, front rise, thigh, knee, outseam, inseam and hem shaping.",
  },
  {
    id: "cargo-trouser-right-front-leg",
    name: "Right Front Leg",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Main right front leg panel including waist, hip, front rise, thigh, knee, outseam, inseam and hem shaping.",
  },
  {
    id: "cargo-trouser-left-back-leg",
    name: "Left Back Leg",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Main left back leg panel shaped for seat, back rise, thigh, knee and hem.",
  },
  {
    id: "cargo-trouser-right-back-leg",
    name: "Right Back Leg",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Main right back leg panel shaped for seat, back rise, thigh, knee and hem.",
  },
  {
    id: "cargo-trouser-left-front-pocket-facing",
    name: "Left Front Pocket Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Left front pocket facing used to clean-finish and stabilise the slant or curved pocket opening.",
  },
  {
    id: "cargo-trouser-right-front-pocket-facing",
    name: "Right Front Pocket Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Right front pocket facing used to clean-finish and stabilise the slant or curved pocket opening.",
  },
  {
    id: "cargo-trouser-left-front-pocket-bag",
    name: "Left Front Pocket Bag",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Pair of pocket-bag sections forming the complete left front pocket.",
  },
  {
    id: "cargo-trouser-right-front-pocket-bag",
    name: "Right Front Pocket Bag",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Pair of pocket-bag sections forming the complete right front pocket.",
  },
  {
    id: "cargo-trouser-left-pocket-bearer",
    name: "Left Front Pocket Bearer",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Left bearer or shield supporting the pocket opening and restoring visible shell fabric behind it.",
  },
  {
    id: "cargo-trouser-right-pocket-bearer",
    name: "Right Front Pocket Bearer",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Right bearer or shield supporting the pocket opening and restoring visible shell fabric behind it.",
  },
  {
    id: "cargo-trouser-left-cargo-pocket",
    name: "Left Cargo Pocket",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Main left thigh cargo pocket panel used for bellows, box-pleat or plain patch-pocket construction.",
  },
  {
    id: "cargo-trouser-right-cargo-pocket",
    name: "Right Cargo Pocket",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Main right thigh cargo pocket panel used for bellows, box-pleat or plain patch-pocket construction.",
  },
  {
    id: "cargo-trouser-left-cargo-pocket-flap",
    name: "Left Cargo Pocket Flap",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Upper and under flap pieces covering the left cargo-pocket opening.",
  },
  {
    id: "cargo-trouser-right-cargo-pocket-flap",
    name: "Right Cargo Pocket Flap",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Upper and under flap pieces covering the right cargo-pocket opening.",
  },
  {
    id: "cargo-trouser-left-cargo-pocket-gusset",
    name: "Left Cargo Pocket Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional side-and-bottom gusset providing expandable capacity to the left cargo pocket.",
  },
  {
    id: "cargo-trouser-right-cargo-pocket-gusset",
    name: "Right Cargo Pocket Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional side-and-bottom gusset providing expandable capacity to the right cargo pocket.",
  },
  {
    id: "cargo-trouser-left-cargo-pocket-pleat",
    name: "Left Cargo Pocket Box Pleat",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional separate box-pleat insert increasing the capacity of the left cargo pocket.",
  },
  {
    id: "cargo-trouser-right-cargo-pocket-pleat",
    name: "Right Cargo Pocket Box Pleat",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional separate box-pleat insert increasing the capacity of the right cargo pocket.",
  },
  {
    id: "cargo-trouser-left-cargo-pocket-facing",
    name: "Left Cargo Pocket Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional facing reinforcing and clean-finishing the left cargo-pocket opening.",
  },
  {
    id: "cargo-trouser-right-cargo-pocket-facing",
    name: "Right Cargo Pocket Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Optional facing reinforcing and clean-finishing the right cargo-pocket opening.",
  },
  {
    id: "cargo-trouser-left-cargo-pocket-reinforcement",
    name: "Left Cargo Pocket Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Optional reinforcement panel supporting the left cargo pocket and fastening area.",
  },
  {
    id: "cargo-trouser-right-cargo-pocket-reinforcement",
    name: "Right Cargo Pocket Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional reinforcement panel supporting the right cargo pocket and fastening area.",
  },
  {
    id: "cargo-trouser-left-back-pocket",
    name: "Left Back Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional left back patch pocket for workwear, military or utility styles.",
  },
  {
    id: "cargo-trouser-right-back-pocket",
    name: "Right Back Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional right back patch pocket for workwear, military or utility styles.",
  },
  {
    id: "cargo-trouser-left-back-pocket-flap",
    name: "Left Back Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional upper and under flap pieces covering the left back pocket.",
  },
  {
    id: "cargo-trouser-right-back-pocket-flap",
    name: "Right Back Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional upper and under flap pieces covering the right back pocket.",
  },
  {
    id: "cargo-trouser-left-waistband",
    name: "Left Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Left shaped waistband section extending from centre back to centre front.",
  },
  {
    id: "cargo-trouser-right-waistband",
    name: "Right Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Right shaped waistband section extending from centre back to centre front.",
  },
  {
    id: "cargo-trouser-left-inner-waistband",
    name: "Left Inner Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Left inner waistband or curtain section used to finish and reinforce the waist.",
  },
  {
    id: "cargo-trouser-right-inner-waistband",
    name: "Right Inner Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Right inner waistband or curtain section used to finish and reinforce the waist.",
  },
  {
    id: "cargo-trouser-waistband-interfacing",
    name: "Waistband Interfacing",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Pair of reinforcement sections supporting the left and right waistbands.",
  },
  {
    id: "cargo-trouser-front-fly",
    name: "Front Fly",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Outer fly extension supporting the front zip or button fastening.",
  },
  {
    id: "cargo-trouser-fly-shield",
    name: "Fly Shield",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Internal fly shield protecting the wearer and concealing the fastening.",
  },
  {
    id: "cargo-trouser-fly-interfacing",
    name: "Fly Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional reinforcement supporting the fly shape and zip installation.",
  },
  {
    id: "cargo-trouser-belt-loop-strip",
    name: "Belt Loop Strip",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Continuous strip used to produce the complete set of waistband belt loops.",
  },
  {
    id: "cargo-trouser-left-knee-panel",
    name: "Left Knee Reinforcement Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional articulated or double-layer reinforcement panel protecting the left knee.",
  },
  {
    id: "cargo-trouser-right-knee-panel",
    name: "Right Knee Reinforcement Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Optional articulated or double-layer reinforcement panel protecting the right knee.",
  },
  {
    id: "cargo-trouser-left-knee-pad-pocket",
    name: "Left Knee Pad Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Optional internal or external pocket used to hold a removable left knee pad.",
  },
  {
    id: "cargo-trouser-right-knee-pad-pocket",
    name: "Right Knee Pad Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional internal or external pocket used to hold a removable right knee pad.",
  },
  {
    id: "cargo-trouser-left-knee-pad-pocket-flap",
    name: "Left Knee Pad Pocket Flap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional closure flap securing the removable left knee pad.",
  },
  {
    id: "cargo-trouser-right-knee-pad-pocket-flap",
    name: "Right Knee Pad Pocket Flap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional closure flap securing the removable right knee pad.",
  },
  {
    id: "cargo-trouser-seat-reinforcement",
    name: "Seat Reinforcement Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 42,
    description:
      "Optional double-layer seat panel for heavy-duty workwear and military applications.",
  },
  {
    id: "cargo-trouser-crotch-gusset",
    name: "Crotch Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional diamond or shaped gusset improving mobility and reducing crotch-seam stress.",
  },
  {
    id: "cargo-trouser-left-ankle-cuff",
    name: "Left Ankle Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional adjustable or elasticated cuff finishing the left leg opening.",
  },
  {
    id: "cargo-trouser-right-ankle-cuff",
    name: "Right Ankle Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional adjustable or elasticated cuff finishing the right leg opening.",
  },
  {
    id: "cargo-trouser-left-hem-drawcord-channel",
    name: "Left Hem Drawcord Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional casing or channel used to house a drawcord at the left leg opening.",
  },
  {
    id: "cargo-trouser-right-hem-drawcord-channel",
    name: "Right Hem Drawcord Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional casing or channel used to house a drawcord at the right leg opening.",
  },
  {
    id: "cargo-trouser-left-hammer-loop",
    name: "Left Hammer Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional reinforced loop positioned on the left side for tools or workwear equipment.",
  },
  {
    id: "cargo-trouser-right-hammer-loop",
    name: "Right Hammer Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional reinforced loop positioned on the right side for tools or workwear equipment.",
  },
  {
    id: "cargo-trouser-tool-pocket",
    name: "Tool Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional narrow utility pocket designed for tools, rulers or work accessories.",
  },
  {
    id: "cargo-trouser-mobile-pocket",
    name: "Mobile Phone Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional fitted pocket designed to securely carry a mobile phone.",
  },
  {
    id: "cargo-trouser-radio-pocket",
    name: "Radio Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Optional reinforced pocket for a radio or communication device.",
  },
  {
    id: "cargo-trouser-radio-strap",
    name: "Radio Retention Strap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Optional strap securing a radio or communication device inside its pocket.",
  },
  {
    id: "cargo-trouser-reflective-strip-left",
    name: "Left Reflective Strip",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Optional reflective strip positioned around or along the left leg for visibility.",
  },
  {
    id: "cargo-trouser-reflective-strip-right",
    name: "Right Reflective Strip",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Optional reflective strip positioned around or along the right leg for visibility.",
  },
  {
    id: "cargo-trouser-left-pocket-fastener-reinforcement",
    name: "Left Pocket Fastener Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Optional reinforcement patches supporting snaps, hook-and-loop tape or buttons on left cargo and back pockets.",
  },
  {
    id: "cargo-trouser-right-pocket-fastener-reinforcement",
    name: "Right Pocket Fastener Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Optional reinforcement patches supporting snaps, hook-and-loop tape or buttons on right cargo and back pockets.",
  },
  {
    id: "cargo-trouser-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 58,
    description:
      "Optional backing supporting embroidery, badge, heat transfer, identification or branding.",
  },
];

export default cargoTrouserPatternMaster;