export const childrenTshirtPatternMaster = [
  {
    id: "children-tshirt-front-body",
    name: "Front Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 1,
    description:
      "Primary front body panel forming the chest, abdomen, front neckline, armholes and front hem of the children's T-shirt.",
  },
  {
    id: "children-tshirt-back-body",
    name: "Back Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 2,
    description:
      "Primary back body panel forming the upper back, lower back, rear neckline, armholes and back hem.",
  },
  {
    id: "children-tshirt-left-front-body",
    name: "Left Front Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Optional left front body panel used in centre-front opening, asymmetric, wrap or colour-blocked T-shirt construction.",
  },
  {
    id: "children-tshirt-right-front-body",
    name: "Right Front Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional right front body panel used in centre-front opening, asymmetric, wrap or colour-blocked T-shirt construction.",
  },
  {
    id: "children-tshirt-left-back-body",
    name: "Left Back Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional left back body panel used in centre-back seam, opening-back or shaped construction.",
  },
  {
    id: "children-tshirt-right-back-body",
    name: "Right Back Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional right back body panel used in centre-back seam, opening-back or shaped construction.",
  },
  {
    id: "children-tshirt-front-yoke",
    name: "Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 7,
    description:
      "Optional upper front yoke used for styling, reinforcement, contrast fabric, print placement or shoulder shaping.",
  },
  {
    id: "children-tshirt-back-yoke",
    name: "Back Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 8,
    description:
      "Optional upper back yoke providing shoulder stability, decorative styling or contrast construction.",
  },
  {
    id: "children-tshirt-left-front-yoke",
    name: "Left Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional left front yoke used in asymmetric, panelled or colour-blocked children's T-shirts.",
  },
  {
    id: "children-tshirt-right-front-yoke",
    name: "Right Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Optional right front yoke used in asymmetric, panelled or colour-blocked children's T-shirts.",
  },
  {
    id: "children-tshirt-centre-front-panel",
    name: "Centre Front Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Optional central front insert used for colour blocking, print placement, ventilation or opening construction.",
  },
  {
    id: "children-tshirt-centre-back-panel",
    name: "Centre Back Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Optional central back insert used for shaping, ventilation, branding or decorative styling.",
  },
  {
    id: "children-tshirt-left-side-panel",
    name: "Left Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional left side body panel used for fit shaping, contrast fabric, ventilation or mobility.",
  },
  {
    id: "children-tshirt-right-side-panel",
    name: "Right Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Optional right side body panel used for fit shaping, contrast fabric, ventilation or mobility.",
  },
  {
    id: "children-tshirt-front-shoulder-panel",
    name: "Front Shoulder Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional shoulder inserts extending over the front upper body for reinforcement or contrast styling.",
  },
  {
    id: "children-tshirt-back-shoulder-panel",
    name: "Back Shoulder Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional rear shoulder inserts providing reinforcement or decorative contrast.",
  },
  {
    id: "children-tshirt-front-lower-panel",
    name: "Front Lower Body Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 17,
    description:
      "Optional lower front body panel used for colour blocking, pocket integration or style variation.",
  },
  {
    id: "children-tshirt-back-lower-panel",
    name: "Back Lower Body Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 18,
    description:
      "Optional lower back body panel used for colour blocking, shaping or extended hem construction.",
  },
  {
    id: "children-tshirt-front-curved-panel",
    name: "Front Curved Insert Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 19,
    description:
      "Optional curved front insert used for activewear styling, ventilation or visual segmentation.",
  },
  {
    id: "children-tshirt-back-curved-panel",
    name: "Back Curved Insert Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 20,
    description:
      "Optional curved back insert used for activewear styling, ventilation or ergonomic shaping.",
  },
  {
    id: "children-tshirt-short-sleeves",
    name: "Short Sleeves",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Primary pair of short sleeves providing standard upper-arm coverage.",
  },
  {
    id: "children-tshirt-left-short-sleeve",
    name: "Left Short Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional individually shaped left short sleeve used in directional or asymmetric construction.",
  },
  {
    id: "children-tshirt-right-short-sleeve",
    name: "Right Short Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional individually shaped right short sleeve used in directional or asymmetric construction.",
  },
  {
    id: "children-tshirt-long-sleeves",
    name: "Long Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional pair of long sleeves providing full arm coverage.",
  },
  {
    id: "children-tshirt-left-long-sleeve",
    name: "Left Long Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional individually shaped left long sleeve used in directional, technical or colour-blocked styles.",
  },
  {
    id: "children-tshirt-right-long-sleeve",
    name: "Right Long Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional individually shaped right long sleeve used in directional, technical or colour-blocked styles.",
  },
  {
    id: "children-tshirt-three-quarter-sleeves",
    name: "Three-Quarter Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional sleeves ending between the elbow and wrist.",
  },
  {
    id: "children-tshirt-cap-sleeves",
    name: "Cap Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional short sleeve sections extending slightly over the shoulders.",
  },
  {
    id: "children-tshirt-raglan-sleeves",
    name: "Raglan Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional pair of raglan sleeves extending to the neckline for comfort and increased movement.",
  },
  {
    id: "children-tshirt-left-raglan-sleeve",
    name: "Left Raglan Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Optional individually shaped left raglan sleeve used in directional or contrast construction.",
  },
  {
    id: "children-tshirt-right-raglan-sleeve",
    name: "Right Raglan Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Optional individually shaped right raglan sleeve used in directional or contrast construction.",
  },
  {
    id: "children-tshirt-drop-shoulder-sleeves",
    name: "Drop-Shoulder Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional sleeves attached below the natural shoulder line for a relaxed silhouette.",
  },
  {
    id: "children-tshirt-dolman-sleeve-body",
    name: "Dolman Sleeve Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 33,
    description:
      "Optional combined body-and-sleeve panel forming a loose dolman or batwing T-shirt silhouette.",
  },
  {
    id: "children-tshirt-flutter-sleeves",
    name: "Flutter Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional lightweight flared sleeves creating a soft flutter effect.",
  },
  {
    id: "children-tshirt-puff-sleeves",
    name: "Puff Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional sleeves with added fullness gathered at the sleeve head, opening or both.",
  },
  {
    id: "children-tshirt-bell-sleeves",
    name: "Bell Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional sleeves widening toward the lower opening.",
  },
  {
    id: "children-tshirt-upper-sleeve-panels",
    name: "Upper Sleeve Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Optional upper-arm sleeve panels used for contrast styling, reinforcement or branding.",
  },
  {
    id: "children-tshirt-lower-sleeve-panels",
    name: "Lower Sleeve Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Optional lower-arm panels used for colour blocking, shaping or abrasion resistance.",
  },
  {
    id: "children-tshirt-front-sleeve-panels",
    name: "Front Sleeve Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional front sleeve sections used for articulation, contrast fabric or technical styling.",
  },
  {
    id: "children-tshirt-back-sleeve-panels",
    name: "Back Sleeve Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional rear sleeve sections supporting movement, shaping and reinforcement.",
  },
  {
    id: "children-tshirt-elbow-panels",
    name: "Elbow Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional shaped elbow inserts used for articulation or contrast styling.",
  },
  {
    id: "children-tshirt-elbow-reinforcements",
    name: "Elbow Reinforcements",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional abrasion-resistant patches protecting both elbow areas.",
  },
  {
    id: "children-tshirt-short-sleeve-cuffs",
    name: "Short Sleeve Cuffs",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional rib-knit or self-fabric cuffs finishing short sleeve openings.",
  },
  {
    id: "children-tshirt-long-sleeve-cuffs",
    name: "Long Sleeve Cuffs",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional rib-knit or self-fabric cuffs finishing long sleeve openings.",
  },
  {
    id: "children-tshirt-thumbhole-cuffs",
    name: "Thumbhole Cuffs",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional extended sleeve cuffs containing thumb openings for warmth and sleeve stability.",
  },
  {
    id: "children-tshirt-thumbhole-inserts",
    name: "Thumbhole Inserts",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional shaped pieces forming and reinforcing thumb openings.",
  },
  {
    id: "children-tshirt-thumbhole-reinforcements",
    name: "Thumbhole Reinforcements",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional support pieces protecting thumbhole edges from stretch and wear.",
  },
  {
    id: "children-tshirt-foldover-mitten-cuffs",
    name: "Foldover Mitten Cuffs",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional extended cuffs that fold over the hands for additional warmth.",
  },
  {
    id: "children-tshirt-foldover-mitten-linings",
    name: "Foldover Mitten Linings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional soft inner pieces completing foldover mitten cuffs.",
  },
  {
    id: "children-tshirt-crew-neckband",
    name: "Crew Neckband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Primary rib-knit or self-fabric band finishing a standard round crew neckline.",
  },
  {
    id: "children-tshirt-wide-neckband",
    name: "Wide Neckband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional wider band finishing a broad round, boat or fashion neckline.",
  },
  {
    id: "children-tshirt-v-neckband-left",
    name: "Left V-Neckband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Optional left neckband section forming one side of a V-neckline.",
  },
  {
    id: "children-tshirt-v-neckband-right",
    name: "Right V-Neckband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Optional right neckband section forming the opposite side of a V-neckline.",
  },
  {
    id: "children-tshirt-v-neck-centre-reinforcement",
    name: "V-Neck Centre Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Optional reinforcement patch stabilising the lower point of a V-neck opening.",
  },
  {
    id: "children-tshirt-scoop-neckband",
    name: "Scoop Neckband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Optional stretch band finishing a deeper rounded scoop neckline.",
  },
  {
    id: "children-tshirt-boat-neck-front-facing",
    name: "Boat Neck Front Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 56,
    description:
      "Optional shaped facing clean-finishing and stabilising the front of a boat neckline.",
  },
  {
    id: "children-tshirt-boat-neck-back-facing",
    name: "Boat Neck Back Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 57,
    description:
      "Optional shaped facing clean-finishing and stabilising the back of a boat neckline.",
  },
  {
    id: "children-tshirt-front-neck-facing",
    name: "Front Neck Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 58,
    description:
      "Optional shaped facing clean-finishing and stabilising the front neckline.",
  },
  {
    id: "children-tshirt-back-neck-facing",
    name: "Back Neck Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 59,
    description:
      "Optional shaped facing clean-finishing and stabilising the back neckline.",
  },
  {
    id: "children-tshirt-neck-binding",
    name: "Neck Binding",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 60,
    description:
      "Optional stretch or bias binding strip finishing the neckline.",
  },
  {
    id: "children-tshirt-envelope-neck-left",
    name: "Left Envelope Shoulder Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 61,
    description:
      "Optional overlapping left shoulder section used in envelope-neck T-shirts for younger children.",
  },
  {
    id: "children-tshirt-envelope-neck-right",
    name: "Right Envelope Shoulder Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 62,
    description:
      "Optional overlapping right shoulder section used in envelope-neck T-shirts for younger children.",
  },
  {
    id: "children-tshirt-envelope-neck-facings",
    name: "Envelope Shoulder Facings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional facings stabilising and clean-finishing overlapping envelope shoulder sections.",
  },
  {
    id: "children-tshirt-turtle-neck",
    name: "Turtleneck Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 64,
    description:
      "Optional deep knitted neckband extending upward and folding over the neck.",
  },
  {
    id: "children-tshirt-mock-neck-band",
    name: "Mock Neck Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 65,
    description:
      "Optional raised neckband providing partial neck coverage without folding.",
  },
  {
    id: "children-tshirt-polo-collar-upper",
    name: "Upper Polo Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 66,
    description:
      "Optional upper collar panel forming a polo-style collar.",
  },
  {
    id: "children-tshirt-polo-collar-under",
    name: "Under Polo Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 67,
    description:
      "Optional under-collar panel completing a cut-and-sew polo collar.",
  },
  {
    id: "children-tshirt-polo-collar-interfacing",
    name: "Polo Collar Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 68,
    description:
      "Optional lightweight reinforcement stabilising a cut-and-sew polo collar.",
  },
  {
    id: "children-tshirt-henley-left-placket",
    name: "Left Henley Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 69,
    description:
      "Optional left placket section forming one side of a Henley neck opening.",
  },
  {
    id: "children-tshirt-henley-right-placket",
    name: "Right Henley Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 70,
    description:
      "Optional right placket section forming the opposite side of a Henley neck opening.",
  },
  {
    id: "children-tshirt-henley-underlay",
    name: "Henley Placket Underlay",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 71,
    description:
      "Optional underlay positioned beneath a Henley button or snap placket.",
  },
  {
    id: "children-tshirt-henley-placket-interfacing",
    name: "Henley Placket Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 72,
    description:
      "Optional reinforcement stabilising both sides of the Henley placket.",
  },
  {
    id: "children-tshirt-half-zip-left-placket",
    name: "Half-Zip Left Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 73,
    description:
      "Optional left placket section forming one side of a half-zip neckline.",
  },
  {
    id: "children-tshirt-half-zip-right-placket",
    name: "Half-Zip Right Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 74,
    description:
      "Optional right placket section forming the opposite side of a half-zip neckline.",
  },
  {
    id: "children-tshirt-half-zip-underlay",
    name: "Half-Zip Underlay",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 75,
    description:
      "Optional protective underlay positioned behind a half-zip opening.",
  },
  {
    id: "children-tshirt-half-zip-chin-guard",
    name: "Half-Zip Chin Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 76,
    description:
      "Optional soft guard covering the upper zip end near the child's chin.",
  },
  {
    id: "children-tshirt-left-shoulder-placket",
    name: "Left Shoulder Placket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 77,
    description:
      "Optional paired placket sections forming a button or snap opening at the left shoulder.",
  },
  {
    id: "children-tshirt-right-shoulder-placket",
    name: "Right Shoulder Placket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 78,
    description:
      "Optional paired placket sections forming a button or snap opening at the right shoulder.",
  },
  {
    id: "children-tshirt-shoulder-placket-reinforcements",
    name: "Shoulder Placket Reinforcements",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 79,
    description:
      "Optional reinforcement pieces supporting button, snap and buttonhole positions on shoulder plackets.",
  },
  {
    id: "children-tshirt-back-neck-opening-left-placket",
    name: "Left Back Neck Opening Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 80,
    description:
      "Optional left placket section forming one side of a centre-back neck opening.",
  },
  {
    id: "children-tshirt-back-neck-opening-right-placket",
    name: "Right Back Neck Opening Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 81,
    description:
      "Optional right placket section forming the opposite side of a centre-back neck opening.",
  },
  {
    id: "children-tshirt-back-neck-placket-interfacing",
    name: "Back Neck Placket Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 82,
    description:
      "Optional reinforcement stabilising a centre-back button or snap opening.",
  },
  {
    id: "children-tshirt-chest-pocket",
    name: "Chest Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 83,
    description:
      "Optional patch pocket positioned on the front chest.",
  },
  {
    id: "children-tshirt-chest-pocket-facing",
    name: "Chest Pocket Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 84,
    description:
      "Optional facing stabilising and clean-finishing the chest pocket opening.",
  },
  {
    id: "children-tshirt-chest-pocket-flap-upper",
    name: "Chest Pocket Flap Upper",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 85,
    description:
      "Optional upper panel forming a decorative or functional chest pocket flap.",
  },
  {
    id: "children-tshirt-chest-pocket-flap-under",
    name: "Chest Pocket Flap Under",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 86,
    description:
      "Optional under panel completing the chest pocket flap.",
  },
  {
    id: "children-tshirt-chest-pocket-flap-interfacing",
    name: "Chest Pocket Flap Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 87,
    description:
      "Optional lightweight reinforcement stabilising the chest pocket flap.",
  },
  {
    id: "children-tshirt-kangaroo-pocket",
    name: "Kangaroo Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 88,
    description:
      "Optional large front pocket with openings at both sides in casual long-sleeve T-shirts.",
  },
  {
    id: "children-tshirt-kangaroo-pocket-left-facing",
    name: "Left Kangaroo Pocket Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 89,
    description:
      "Optional facing reinforcing and finishing the left kangaroo pocket opening.",
  },
  {
    id: "children-tshirt-kangaroo-pocket-right-facing",
    name: "Right Kangaroo Pocket Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 90,
    description:
      "Optional facing reinforcing and finishing the right kangaroo pocket opening.",
  },
  {
    id: "children-tshirt-left-side-pocket",
    name: "Left Side Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 91,
    description:
      "Optional small utility or storage pocket positioned on the left side body.",
  },
  {
    id: "children-tshirt-right-side-pocket",
    name: "Right Side Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 92,
    description:
      "Optional small utility or storage pocket positioned on the right side body.",
  },
  {
    id: "children-tshirt-hem-band",
    name: "Bottom Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 93,
    description:
      "Optional rib-knit or self-fabric band finishing and controlling the lower body opening.",
  },
  {
    id: "children-tshirt-front-hem-band",
    name: "Front Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 94,
    description:
      "Optional separate front section of a divided bottom hem band.",
  },
  {
    id: "children-tshirt-back-hem-band",
    name: "Back Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 95,
    description:
      "Optional separate back section of a divided bottom hem band.",
  },
  {
    id: "children-tshirt-front-curved-hem-facing",
    name: "Front Curved Hem Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 96,
    description:
      "Optional shaped facing clean-finishing a curved or high-low front hem.",
  },
  {
    id: "children-tshirt-back-curved-hem-facing",
    name: "Back Curved Hem Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 97,
    description:
      "Optional shaped facing clean-finishing a curved, dropped or high-low back hem.",
  },
  {
    id: "children-tshirt-side-split-facings",
    name: "Side Split Facings",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 98,
    description:
      "Optional facing pieces reinforcing and clean-finishing both side-hem openings.",
  },
  {
    id: "children-tshirt-back-drop-tail-panel",
    name: "Back Drop-Tail Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 99,
    description:
      "Optional elongated rear body panel providing additional back coverage.",
  },
  {
    id: "children-tshirt-front-body-lining",
    name: "Front Body Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 100,
    description:
      "Optional soft lining panel covering the inside front body.",
  },
  {
    id: "children-tshirt-back-body-lining",
    name: "Back Body Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 101,
    description:
      "Optional soft lining panel covering the inside back body.",
  },
  {
    id: "children-tshirt-sleeve-linings",
    name: "Sleeve Linings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 102,
    description:
      "Optional soft lining pieces covering the inside of both sleeves.",
  },
  {
    id: "children-tshirt-front-thermal-lining",
    name: "Front Thermal Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 103,
    description:
      "Optional insulating layer positioned inside the front body of a winter T-shirt.",
  },
  {
    id: "children-tshirt-back-thermal-lining",
    name: "Back Thermal Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 104,
    description:
      "Optional insulating layer positioned inside the back body of a winter T-shirt.",
  },
  {
    id: "children-tshirt-sleeve-thermal-linings",
    name: "Sleeve Thermal Linings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 105,
    description:
      "Optional insulating inner layers providing additional warmth through both sleeves.",
  },
  {
    id: "children-tshirt-front-windproof-membrane",
    name: "Front Windproof Membrane",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 106,
    description:
      "Optional membrane layer reducing wind penetration through the front body.",
  },
  {
    id: "children-tshirt-back-windproof-membrane",
    name: "Back Windproof Membrane",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 107,
    description:
      "Optional membrane layer reducing wind penetration through the back body.",
  },
  {
    id: "children-tshirt-sleeve-windproof-membranes",
    name: "Sleeve Windproof Membranes",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 108,
    description:
      "Optional membrane layers reducing wind penetration through both sleeves.",
  },
  {
    id: "children-tshirt-front-mesh-panel",
    name: "Front Mesh Ventilation Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 109,
    description:
      "Optional breathable mesh insert improving airflow through the front body.",
  },
  {
    id: "children-tshirt-back-mesh-panel",
    name: "Back Mesh Ventilation Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 110,
    description:
      "Optional breathable mesh insert improving airflow through the back body.",
  },
  {
    id: "children-tshirt-side-mesh-panels",
    name: "Side Mesh Ventilation Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 111,
    description:
      "Optional breathable panels positioned along both side bodies.",
  },
  {
    id: "children-tshirt-underarm-mesh-panels",
    name: "Underarm Mesh Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 112,
    description:
      "Optional breathable inserts positioned beneath both arms for moisture and heat management.",
  },
  {
    id: "children-tshirt-back-neck-tape",
    name: "Back Neck Tape",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 113,
    description:
      "Optional soft tape covering and stabilising the back neckline seam.",
  },
  {
    id: "children-tshirt-shoulder-seam-covers",
    name: "Shoulder Seam Covers",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 114,
    description:
      "Optional internal strips covering shoulder seams for comfort and durability.",
  },
  {
    id: "children-tshirt-side-seam-covers",
    name: "Side Seam Covers",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 115,
    description:
      "Optional internal strips covering side seams to reduce irritation.",
  },
  {
    id: "children-tshirt-armhole-seam-covers",
    name: "Armhole Seam Covers",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 116,
    description:
      "Optional soft strips covering armhole seams for comfort and clean finishing.",
  },
  {
    id: "children-tshirt-sleeve-seam-covers",
    name: "Sleeve Seam Covers",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 117,
    description:
      "Optional internal strips covering longitudinal sleeve seams.",
  },
  {
    id: "children-tshirt-front-logo-backing",
    name: "Front Logo Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 118,
    description:
      "Optional internal support patch positioned behind front embroidery, appliqué, print or branding.",
  },
  {
    id: "children-tshirt-back-logo-backing",
    name: "Back Logo Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 119,
    description:
      "Optional internal support patch positioned behind back embroidery, appliqué or branding.",
  },
  {
    id: "children-tshirt-sleeve-logo-backings",
    name: "Sleeve Logo Backings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 120,
    description:
      "Optional support patches positioned behind logos, badges or decorative applications on both sleeves.",
  },
  {
    id: "children-tshirt-front-print-backing",
    name: "Front Print Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 121,
    description:
      "Optional stabilising layer supporting heavy, textured or embroidered front graphic applications.",
  },
  {
    id: "children-tshirt-back-print-backing",
    name: "Back Print Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 122,
    description:
      "Optional stabilising layer supporting heavy, textured or embroidered back graphic applications.",
  },
  {
    id: "children-tshirt-sequin-decoration-backing",
    name: "Sequin Decoration Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 123,
    description:
      "Optional support layer positioned behind sequin, bead or decorative surface applications.",
  },
  {
    id: "children-tshirt-applique-backing",
    name: "Appliqué Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 124,
    description:
      "Optional backing patches supporting front, back or sleeve appliqué.",
  },
  {
    id: "children-tshirt-reflective-front-panel",
    name: "Reflective Front Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 125,
    description:
      "Optional reflective or high-visibility panel positioned on the front body.",
  },
  {
    id: "children-tshirt-reflective-back-panel",
    name: "Reflective Back Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 126,
    description:
      "Optional reflective or high-visibility panel positioned on the back body.",
  },
  {
    id: "children-tshirt-reflective-sleeve-panels",
    name: "Reflective Sleeve Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 127,
    description:
      "Optional reflective panels positioned on both sleeves for improved visibility.",
  },
  {
    id: "children-tshirt-name-label-backing",
    name: "Name Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 128,
    description:
      "Optional support piece for a child's name, school or identification label.",
  },
  {
    id: "children-tshirt-brand-label-backing",
    name: "Brand Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 129,
    description:
      "Optional support piece for a woven, printed or heat-transfer brand label.",
  },
  {
    id: "children-tshirt-size-label-backing",
    name: "Size Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 130,
    description:
      "Optional support piece for a separate size label.",
  },
  {
    id: "children-tshirt-care-label-backing",
    name: "Care Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 131,
    description:
      "Optional internal support piece for care, fibre-content and country-of-origin labels.",
  },
  {
    id: "children-tshirt-button-backing",
    name: "Button Attachment Backing",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 132,
    description:
      "Optional reinforcement patches positioned behind button attachment points.",
  },
  {
    id: "children-tshirt-buttonhole-backing",
    name: "Buttonhole Backing",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 133,
    description:
      "Optional reinforcement patches stabilising buttonhole positions.",
  },
  {
    id: "children-tshirt-snap-backing",
    name: "Snap Fastener Backing",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 134,
    description:
      "Optional reinforcement patches supporting snap-fastener installation.",
  },
  {
    id: "children-tshirt-sensor-pocket",
    name: "Sensor Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 135,
    description:
      "Optional small internal or external pocket supporting a fitness, safety or medical sensor.",
  },
  {
    id: "children-tshirt-sensor-pocket-facing",
    name: "Sensor Pocket Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 136,
    description:
      "Optional facing stabilising and clean-finishing the sensor pocket opening.",
  },
  {
    id: "children-tshirt-headphone-channel",
    name: "Headphone Cable Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 137,
    description:
      "Optional narrow fabric channel routing an earphone or communication cable inside the garment.",
  },
  {
    id: "children-tshirt-headphone-loop",
    name: "Headphone Cable Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 138,
    description:
      "Optional small loop securing a headphone or communication cable near the neckline.",
  },
];

export default childrenTshirtPatternMaster;