export const childrenDressPatternMaster = [
  {
    id: "children-dress-front-bodice",
    name: "Front Bodice",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 1,
    description:
      "Primary front upper-body panel forming the chest, waist and front armhole sections of the children's dress.",
  },
  {
    id: "children-dress-back-bodice",
    name: "Back Bodice",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 2,
    description:
      "Primary back upper-body panel forming the back neckline, shoulders, waist and rear armholes.",
  },
  {
    id: "children-dress-left-front-bodice",
    name: "Left Front Bodice",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Optional left front bodice panel used in centre-front opening, wrap, asymmetric or panelled dress construction.",
  },
  {
    id: "children-dress-right-front-bodice",
    name: "Right Front Bodice",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional right front bodice panel used in centre-front opening, wrap, asymmetric or panelled dress construction.",
  },
  {
    id: "children-dress-left-back-bodice",
    name: "Left Back Bodice",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional left back bodice panel used in centre-back zip, button or shaped back construction.",
  },
  {
    id: "children-dress-right-back-bodice",
    name: "Right Back Bodice",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional right back bodice panel used in centre-back zip, button or shaped back construction.",
  },
  {
    id: "children-dress-front-yoke",
    name: "Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 7,
    description:
      "Optional upper front yoke used for gathering, smocking, contrast fabric, embroidery or structural shaping.",
  },
  {
    id: "children-dress-back-yoke",
    name: "Back Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 8,
    description:
      "Optional upper back yoke providing shoulder stability, gathering support or decorative styling.",
  },
  {
    id: "children-dress-left-front-yoke",
    name: "Left Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional left front yoke used in asymmetric, opening-front or colour-blocked children's dresses.",
  },
  {
    id: "children-dress-right-front-yoke",
    name: "Right Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Optional right front yoke used in asymmetric, opening-front or colour-blocked children's dresses.",
  },
  {
    id: "children-dress-centre-front-bodice-panel",
    name: "Centre Front Bodice Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Optional central bodice panel used for princess shaping, decoration, smocking or opening construction.",
  },
  {
    id: "children-dress-centre-back-bodice-panel",
    name: "Centre Back Bodice Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Optional central back panel used for shaping, zip installation or decorative construction.",
  },
  {
    id: "children-dress-left-front-princess-panel",
    name: "Left Front Princess Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional shaped left front panel creating princess-line contour from the armhole or shoulder to the waist.",
  },
  {
    id: "children-dress-right-front-princess-panel",
    name: "Right Front Princess Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Optional shaped right front panel creating princess-line contour from the armhole or shoulder to the waist.",
  },
  {
    id: "children-dress-left-back-princess-panel",
    name: "Left Back Princess Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional shaped left back panel providing rear contour and fitted princess-line construction.",
  },
  {
    id: "children-dress-right-back-princess-panel",
    name: "Right Back Princess Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional shaped right back panel providing rear contour and fitted princess-line construction.",
  },
  {
    id: "children-dress-left-side-bodice-panel",
    name: "Left Side Bodice Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional left side bodice insert used for shaping, contrast fabric or ventilation.",
  },
  {
    id: "children-dress-right-side-bodice-panel",
    name: "Right Side Bodice Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional right side bodice insert used for shaping, contrast fabric or ventilation.",
  },
  {
    id: "children-dress-front-empire-panel",
    name: "Front Empire Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 19,
    description:
      "Optional upper front panel ending beneath the chest for empire-line dress construction.",
  },
  {
    id: "children-dress-back-empire-panel",
    name: "Back Empire Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 20,
    description:
      "Optional upper back panel joining the skirt at an elevated empire seam.",
  },
  {
    id: "children-dress-front-smocked-panel",
    name: "Front Smocked Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 21,
    description:
      "Optional front panel prepared for hand or machine smocking across the chest or waist.",
  },
  {
    id: "children-dress-back-smocked-panel",
    name: "Back Smocked Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 22,
    description:
      "Optional back panel prepared for elastic shirring or decorative smocking.",
  },
  {
    id: "children-dress-front-waist-panel",
    name: "Front Waist Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 23,
    description:
      "Optional front waist section joining the bodice and skirt while providing fit control.",
  },
  {
    id: "children-dress-back-waist-panel",
    name: "Back Waist Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 24,
    description:
      "Optional back waist section joining the bodice and skirt and supporting closure construction.",
  },
  {
    id: "children-dress-waistband",
    name: "Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional continuous waistband separating the bodice and skirt and supporting elastic or decorative treatment.",
  },
  {
    id: "children-dress-waistband-outer",
    name: "Outer Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional outer layer of a structured or lined waistband.",
  },
  {
    id: "children-dress-waistband-inner",
    name: "Inner Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional inner waistband layer providing clean finishing and structural support.",
  },
  {
    id: "children-dress-waistband-interfacing",
    name: "Waistband Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional lightweight reinforcement stabilising the waistband.",
  },
  {
    id: "children-dress-waist-elastic-casing",
    name: "Waist Elastic Casing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional casing containing inserted elastic around the waist.",
  },
  {
    id: "children-dress-front-skirt",
    name: "Front Skirt",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 30,
    description:
      "Primary front skirt panel forming the lower front portion of the children's dress.",
  },
  {
    id: "children-dress-back-skirt",
    name: "Back Skirt",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 31,
    description:
      "Primary back skirt panel forming the lower rear portion of the children's dress.",
  },
  {
    id: "children-dress-left-front-skirt",
    name: "Left Front Skirt",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional left front skirt panel used in centre-front opening, wrap, pleated or panelled dress construction.",
  },
  {
    id: "children-dress-right-front-skirt",
    name: "Right Front Skirt",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Optional right front skirt panel used in centre-front opening, wrap, pleated or panelled dress construction.",
  },
  {
    id: "children-dress-left-back-skirt",
    name: "Left Back Skirt",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional left back skirt panel used in centre-back opening, shaped or panelled dress construction.",
  },
  {
    id: "children-dress-right-back-skirt",
    name: "Right Back Skirt",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional right back skirt panel used in centre-back opening, shaped or panelled dress construction.",
  },
  {
    id: "children-dress-circle-skirt",
    name: "Full Circle Skirt",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 36,
    description:
      "Optional circular skirt panel providing maximum flare and movement.",
  },
  {
    id: "children-dress-half-circle-skirt-front",
    name: "Half-Circle Front Skirt",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 37,
    description:
      "Optional flared front skirt panel based on half-circle construction.",
  },
  {
    id: "children-dress-half-circle-skirt-back",
    name: "Half-Circle Back Skirt",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 38,
    description:
      "Optional flared back skirt panel based on half-circle construction.",
  },
  {
    id: "children-dress-a-line-front-skirt",
    name: "A-Line Front Skirt",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 39,
    description:
      "Optional front skirt panel gradually widening from the waist or hip to the hem.",
  },
  {
    id: "children-dress-a-line-back-skirt",
    name: "A-Line Back Skirt",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 40,
    description:
      "Optional back skirt panel gradually widening from the waist or hip to the hem.",
  },
  {
    id: "children-dress-front-centre-skirt-panel",
    name: "Centre Front Skirt Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional centre front skirt panel used in panelled, pleated or decorative dress construction.",
  },
  {
    id: "children-dress-back-centre-skirt-panel",
    name: "Centre Back Skirt Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional centre back skirt panel used for shaping, closure integration or decorative styling.",
  },
  {
    id: "children-dress-left-side-skirt-panel",
    name: "Left Side Skirt Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional left side skirt panel used for flare distribution, shaping or colour blocking.",
  },
  {
    id: "children-dress-right-side-skirt-panel",
    name: "Right Side Skirt Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional right side skirt panel used for flare distribution, shaping or colour blocking.",
  },
  {
    id: "children-dress-left-godet",
    name: "Left Skirt Godet",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional triangular insert increasing flare and movement at the left side of the skirt.",
  },
  {
    id: "children-dress-right-godet",
    name: "Right Skirt Godet",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional triangular insert increasing flare and movement at the right side of the skirt.",
  },
  {
    id: "children-dress-front-godet",
    name: "Front Skirt Godet",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional front triangular insert adding flare or decorative contrast.",
  },
  {
    id: "children-dress-back-godet",
    name: "Back Skirt Godet",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional rear triangular insert adding flare and movement.",
  },
  {
    id: "children-dress-first-tier",
    name: "First Skirt Tier",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional upper gathered tier forming the first section of a tiered dress skirt.",
  },
  {
    id: "children-dress-second-tier",
    name: "Second Skirt Tier",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional middle gathered tier providing additional volume and length.",
  },
  {
    id: "children-dress-third-tier",
    name: "Third Skirt Tier",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional lower gathered tier completing a three-tier dress skirt.",
  },
  {
    id: "children-dress-fourth-tier",
    name: "Fourth Skirt Tier",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Optional additional lower tier used in long or highly gathered children's dresses.",
  },
  {
    id: "children-dress-front-box-pleat-panel",
    name: "Front Box Pleat Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Optional front insert forming a central box pleat.",
  },
  {
    id: "children-dress-back-box-pleat-panel",
    name: "Back Box Pleat Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Optional rear insert forming a central box pleat.",
  },
  {
    id: "children-dress-front-inverted-pleat-panel",
    name: "Front Inverted Pleat Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Optional front panel forming an inverted pleat for movement and style.",
  },
  {
    id: "children-dress-side-pleat-panels",
    name: "Side Pleat Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Optional left and right panels forming side pleats in the skirt.",
  },
  {
    id: "children-dress-wrap-left-skirt",
    name: "Left Wrap Skirt",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Optional outer left skirt panel forming the overlapping portion of a wrap dress.",
  },
  {
    id: "children-dress-wrap-right-skirt",
    name: "Right Wrap Skirt",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 58,
    description:
      "Optional right underlap skirt panel completing wrap-dress construction.",
  },
  {
    id: "children-dress-front-high-low-skirt",
    name: "High-Low Front Skirt",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 59,
    description:
      "Optional shorter front skirt panel used in high-low dress silhouettes.",
  },
  {
    id: "children-dress-back-high-low-skirt",
    name: "High-Low Back Skirt",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 60,
    description:
      "Optional elongated back skirt panel creating a dipped or high-low hem.",
  },
  {
    id: "children-dress-peplum-front",
    name: "Front Peplum",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 61,
    description:
      "Optional flared front waist extension positioned over the skirt.",
  },
  {
    id: "children-dress-peplum-back",
    name: "Back Peplum",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 62,
    description:
      "Optional flared back waist extension completing a peplum silhouette.",
  },
  {
    id: "children-dress-skirt-ruffle",
    name: "Skirt Hem Ruffle",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional gathered or circular ruffle attached around the skirt hem.",
  },
  {
    id: "children-dress-front-neck-ruffle",
    name: "Front Neck Ruffle",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 64,
    description:
      "Optional decorative ruffle attached around the front neckline.",
  },
  {
    id: "children-dress-back-neck-ruffle",
    name: "Back Neck Ruffle",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 65,
    description:
      "Optional decorative ruffle attached around the back neckline.",
  },
  {
    id: "children-dress-shoulder-ruffles",
    name: "Shoulder Ruffles",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 66,
    description:
      "Optional decorative ruffles positioned over both shoulders.",
  },
  {
    id: "children-dress-armhole-ruffles",
    name: "Armhole Ruffles",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 67,
    description:
      "Optional ruffles finishing sleeveless armholes or creating flutter sleeves.",
  },
  {
    id: "children-dress-waist-ruffle",
    name: "Waist Ruffle",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 68,
    description:
      "Optional gathered ruffle inserted at the waist seam.",
  },
  {
    id: "children-dress-front-neck-facing",
    name: "Front Neck Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 69,
    description:
      "Optional shaped facing clean-finishing and stabilising the front neckline.",
  },
  {
    id: "children-dress-back-neck-facing",
    name: "Back Neck Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 70,
    description:
      "Optional shaped facing clean-finishing and stabilising the back neckline.",
  },
  {
    id: "children-dress-neckband",
    name: "Neckband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 71,
    description:
      "Optional knitted or self-fabric band finishing a round, scoop or stretch neckline.",
  },
  {
    id: "children-dress-neck-binding",
    name: "Neck Binding",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 72,
    description:
      "Optional bias or stretch binding strip clean-finishing the neckline.",
  },
  {
    id: "children-dress-peter-pan-collar-upper-left",
    name: "Left Peter Pan Collar Upper",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 73,
    description:
      "Optional upper left collar section forming one half of a rounded Peter Pan collar.",
  },
  {
    id: "children-dress-peter-pan-collar-upper-right",
    name: "Right Peter Pan Collar Upper",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 74,
    description:
      "Optional upper right collar section forming the other half of a rounded Peter Pan collar.",
  },
  {
    id: "children-dress-peter-pan-collar-under-left",
    name: "Left Peter Pan Collar Under",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 75,
    description:
      "Optional under-collar piece completing the left side of a Peter Pan collar.",
  },
  {
    id: "children-dress-peter-pan-collar-under-right",
    name: "Right Peter Pan Collar Under",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 76,
    description:
      "Optional under-collar piece completing the right side of a Peter Pan collar.",
  },
  {
    id: "children-dress-collar-interfacing",
    name: "Collar Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 77,
    description:
      "Optional lightweight reinforcement stabilising collar sections.",
  },
  {
    id: "children-dress-shirt-collar-upper",
    name: "Upper Shirt Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 78,
    description:
      "Optional upper collar panel forming a conventional shirt-style collar.",
  },
  {
    id: "children-dress-shirt-collar-under",
    name: "Under Shirt Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 79,
    description:
      "Optional under-collar panel completing the shirt-style collar.",
  },
  {
    id: "children-dress-collar-stand-outer",
    name: "Outer Collar Stand",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 80,
    description:
      "Optional outer stand supporting a shirt collar around the neckline.",
  },
  {
    id: "children-dress-collar-stand-inner",
    name: "Inner Collar Stand",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 81,
    description:
      "Optional inner stand completing and lining the collar stand.",
  },
  {
    id: "children-dress-sailor-collar",
    name: "Sailor Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 82,
    description:
      "Optional wide collar extending across the shoulders and upper back in sailor-style dresses.",
  },
  {
    id: "children-dress-sailor-collar-facing",
    name: "Sailor Collar Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 83,
    description:
      "Optional under layer completing and clean-finishing the sailor collar.",
  },
  {
    id: "children-dress-cap-sleeves",
    name: "Cap Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 84,
    description:
      "Optional short sleeves extending slightly over the shoulder.",
  },
  {
    id: "children-dress-short-sleeves",
    name: "Short Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 85,
    description:
      "Optional pair of standard short sleeves providing upper-arm coverage.",
  },
  {
    id: "children-dress-long-sleeves",
    name: "Long Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 86,
    description:
      "Optional pair of long sleeves providing full arm coverage.",
  },
  {
    id: "children-dress-three-quarter-sleeves",
    name: "Three-Quarter Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 87,
    description:
      "Optional sleeves ending below the elbow and above the wrist.",
  },
  {
    id: "children-dress-puff-sleeves",
    name: "Puff Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 88,
    description:
      "Optional sleeves with added fullness gathered at the sleeve head, cuff or both.",
  },
  {
    id: "children-dress-flutter-sleeves",
    name: "Flutter Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 89,
    description:
      "Optional flared lightweight sleeves creating a soft fluttering effect.",
  },
  {
    id: "children-dress-bell-sleeves",
    name: "Bell Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 90,
    description:
      "Optional sleeves widening toward the lower opening.",
  },
  {
    id: "children-dress-raglan-sleeves",
    name: "Raglan Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 91,
    description:
      "Optional sleeves extending to the neckline for comfort and casual styling.",
  },
  {
    id: "children-dress-sleeve-cuffs",
    name: "Sleeve Cuffs",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 92,
    description:
      "Optional cuffs finishing and controlling long or gathered sleeve openings.",
  },
  {
    id: "children-dress-sleeve-cuff-interfacing",
    name: "Sleeve Cuff Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 93,
    description:
      "Optional lightweight reinforcement stabilising both sleeve cuffs.",
  },
  {
    id: "children-dress-sleeve-elastic-casings",
    name: "Sleeve Elastic Casings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 94,
    description:
      "Optional casings containing elastic at the sleeve openings.",
  },
  {
    id: "children-dress-armhole-bindings",
    name: "Armhole Bindings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 95,
    description:
      "Optional bias or stretch binding strips finishing sleeveless armholes.",
  },
  {
    id: "children-dress-front-button-placket-left",
    name: "Left Front Button Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 96,
    description:
      "Optional left front placket supporting buttons or buttonholes in an opening-front dress.",
  },
  {
    id: "children-dress-front-button-placket-right",
    name: "Right Front Button Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 97,
    description:
      "Optional right front placket forming the matching side of an opening-front dress.",
  },
  {
    id: "children-dress-front-placket-interfacing",
    name: "Front Placket Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 98,
    description:
      "Optional reinforcement stabilising front button or snap plackets.",
  },
  {
    id: "children-dress-back-button-placket-left",
    name: "Left Back Button Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 99,
    description:
      "Optional left back placket forming one side of a centre-back button opening.",
  },
  {
    id: "children-dress-back-button-placket-right",
    name: "Right Back Button Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 100,
    description:
      "Optional right back placket forming the opposite side of a centre-back button opening.",
  },
  {
    id: "children-dress-back-placket-interfacing",
    name: "Back Placket Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 101,
    description:
      "Optional reinforcement stabilising the centre-back button plackets.",
  },
  {
    id: "children-dress-back-zip-left-facing",
    name: "Left Back Zip Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 102,
    description:
      "Optional facing stabilising and finishing the left side of a centre-back zip opening.",
  },
  {
    id: "children-dress-back-zip-right-facing",
    name: "Right Back Zip Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 103,
    description:
      "Optional facing stabilising and finishing the right side of a centre-back zip opening.",
  },
  {
    id: "children-dress-inner-zip-guard",
    name: "Inner Zip Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 104,
    description:
      "Optional soft protective strip positioned behind the zip to prevent skin contact.",
  },
  {
    id: "children-dress-zip-top-guard",
    name: "Zip Top Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 105,
    description:
      "Optional small guard covering the upper zip end near the neckline.",
  },
  {
    id: "children-dress-left-shoulder-placket",
    name: "Left Shoulder Placket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 106,
    description:
      "Optional paired placket sections forming a button or snap opening at the left shoulder.",
  },
  {
    id: "children-dress-right-shoulder-placket",
    name: "Right Shoulder Placket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 107,
    description:
      "Optional paired placket sections forming a button or snap opening at the right shoulder.",
  },
  {
    id: "children-dress-shoulder-placket-reinforcements",
    name: "Shoulder Placket Reinforcements",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 108,
    description:
      "Optional support pieces reinforcing fastener positions on shoulder plackets.",
  },
  {
    id: "children-dress-left-waist-tie",
    name: "Left Waist Tie",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 109,
    description:
      "Optional tie attached at the left waist for fit adjustment or decorative bow formation.",
  },
  {
    id: "children-dress-right-waist-tie",
    name: "Right Waist Tie",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 110,
    description:
      "Optional tie attached at the right waist for fit adjustment or decorative bow formation.",
  },
  {
    id: "children-dress-front-belt",
    name: "Front Belt",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 111,
    description:
      "Optional front belt section used as part of a fitted or decorative waist belt.",
  },
  {
    id: "children-dress-back-belt",
    name: "Back Belt",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 112,
    description:
      "Optional back belt section completing a fitted or adjustable waist belt.",
  },
  {
    id: "children-dress-belt-loops",
    name: "Belt Loops",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 113,
    description:
      "Optional narrow loops supporting a removable belt at the waist.",
  },
  {
    id: "children-dress-bow-centre",
    name: "Bow Centre",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 114,
    description:
      "Optional decorative central bow section used at the waist, neckline or back.",
  },
  {
    id: "children-dress-bow-left-loop",
    name: "Bow Left Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 115,
    description:
      "Optional left loop forming one side of a decorative fabric bow.",
  },
  {
    id: "children-dress-bow-right-loop",
    name: "Bow Right Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 116,
    description:
      "Optional right loop forming the opposite side of a decorative fabric bow.",
  },
  {
    id: "children-dress-bow-left-tail",
    name: "Bow Left Tail",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 117,
    description:
      "Optional left decorative tail extending from a fabric bow.",
  },
  {
    id: "children-dress-bow-right-tail",
    name: "Bow Right Tail",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 118,
    description:
      "Optional right decorative tail extending from a fabric bow.",
  },
  {
    id: "children-dress-left-patch-pocket",
    name: "Left Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 119,
    description:
      "Optional patch pocket positioned on the left front skirt or bodice.",
  },
  {
    id: "children-dress-right-patch-pocket",
    name: "Right Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 120,
    description:
      "Optional patch pocket positioned on the right front skirt or bodice.",
  },
  {
    id: "children-dress-left-pocket-flap-upper",
    name: "Left Pocket Flap Upper",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 121,
    description:
      "Optional upper flap panel covering the left pocket opening.",
  },
  {
    id: "children-dress-left-pocket-flap-under",
    name: "Left Pocket Flap Under",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 122,
    description:
      "Optional under-flap panel completing the left pocket flap.",
  },
  {
    id: "children-dress-right-pocket-flap-upper",
    name: "Right Pocket Flap Upper",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 123,
    description:
      "Optional upper flap panel covering the right pocket opening.",
  },
  {
    id: "children-dress-right-pocket-flap-under",
    name: "Right Pocket Flap Under",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 124,
    description:
      "Optional under-flap panel completing the right pocket flap.",
  },
  {
    id: "children-dress-side-seam-pocket-bags",
    name: "Side-Seam Pocket Bags",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 125,
    description:
      "Optional pocket-bag pieces forming concealed pockets in both side seams.",
  },
  {
    id: "children-dress-kangaroo-pocket",
    name: "Kangaroo Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 126,
    description:
      "Optional large front pocket with openings at both sides in casual or hooded dresses.",
  },
  {
    id: "children-dress-kangaroo-pocket-facings",
    name: "Kangaroo Pocket Opening Facings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 127,
    description:
      "Optional facings reinforcing and clean-finishing both kangaroo pocket openings.",
  },
  {
    id: "children-dress-hood-left",
    name: "Left Hood Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 128,
    description:
      "Optional left panel forming one side of a two-piece hood.",
  },
  {
    id: "children-dress-hood-right",
    name: "Right Hood Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 129,
    description:
      "Optional right panel forming the opposite side of a two-piece hood.",
  },
  {
    id: "children-dress-hood-centre",
    name: "Hood Centre Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 130,
    description:
      "Optional centre panel creating crown depth in three-piece hood construction.",
  },
  {
    id: "children-dress-hood-lining-left",
    name: "Left Hood Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 131,
    description:
      "Optional soft lining panel covering the inside left side of the hood.",
  },
  {
    id: "children-dress-hood-lining-right",
    name: "Right Hood Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 132,
    description:
      "Optional soft lining panel covering the inside right side of the hood.",
  },
  {
    id: "children-dress-hood-lining-centre",
    name: "Hood Centre Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 133,
    description:
      "Optional lining panel covering the centre section of a three-piece hood.",
  },
  {
    id: "children-dress-hood-opening-band",
    name: "Hood Opening Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 134,
    description:
      "Optional self-fabric or knitted band finishing the hood opening.",
  },
  {
    id: "children-dress-front-bodice-lining",
    name: "Front Bodice Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 135,
    description:
      "Optional lining panel covering the inside front bodice.",
  },
  {
    id: "children-dress-back-bodice-lining",
    name: "Back Bodice Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 136,
    description:
      "Optional lining panel covering the inside back bodice.",
  },
  {
    id: "children-dress-front-skirt-lining",
    name: "Front Skirt Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 137,
    description:
      "Optional lining panel providing opacity, comfort and clean finishing inside the front skirt.",
  },
  {
    id: "children-dress-back-skirt-lining",
    name: "Back Skirt Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 138,
    description:
      "Optional lining panel providing opacity, comfort and clean finishing inside the back skirt.",
  },
  {
    id: "children-dress-sleeve-linings",
    name: "Sleeve Linings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 139,
    description:
      "Optional lining pieces covering the inside of both sleeves.",
  },
  {
    id: "children-dress-petticoat-front",
    name: "Petticoat Front",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 140,
    description:
      "Optional front under-skirt panel supporting skirt volume and opacity.",
  },
  {
    id: "children-dress-petticoat-back",
    name: "Petticoat Back",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 141,
    description:
      "Optional back under-skirt panel supporting skirt volume and opacity.",
  },
  {
    id: "children-dress-petticoat-ruffle",
    name: "Petticoat Ruffle",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 142,
    description:
      "Optional gathered ruffle increasing volume at the lower edge of the petticoat.",
  },
  {
    id: "children-dress-tulle-upper-layer",
    name: "Upper Tulle Skirt Layer",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 143,
    description:
      "Optional upper tulle layer providing lightweight volume in party and occasion dresses.",
  },
  {
    id: "children-dress-tulle-middle-layer",
    name: "Middle Tulle Skirt Layer",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 144,
    description:
      "Optional middle tulle layer increasing fullness and structure.",
  },
  {
    id: "children-dress-tulle-lower-layer",
    name: "Lower Tulle Skirt Layer",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 145,
    description:
      "Optional lower tulle layer completing a multi-layer party skirt.",
  },
  {
    id: "children-dress-front-insulation",
    name: "Front Bodice Insulation",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 146,
    description:
      "Optional lightweight insulation layer positioned inside the front bodice of a winter dress.",
  },
  {
    id: "children-dress-back-insulation",
    name: "Back Bodice Insulation",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 147,
    description:
      "Optional lightweight insulation layer positioned inside the back bodice.",
  },
  {
    id: "children-dress-sleeve-insulation",
    name: "Sleeve Insulation",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 148,
    description:
      "Optional insulating layers positioned inside both sleeves.",
  },
  {
    id: "children-dress-front-apron-panel",
    name: "Front Pinafore Apron Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 149,
    description:
      "Optional front apron-style panel used in pinafore and school dress construction.",
  },
  {
    id: "children-dress-back-pinafore-panel",
    name: "Back Pinafore Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 150,
    description:
      "Optional back upper panel completing a pinafore dress.",
  },
  {
    id: "children-dress-left-pinafore-strap",
    name: "Left Pinafore Strap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 151,
    description:
      "Optional left shoulder strap connecting the front and back sections of a pinafore dress.",
  },
  {
    id: "children-dress-right-pinafore-strap",
    name: "Right Pinafore Strap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 152,
    description:
      "Optional right shoulder strap connecting the front and back sections of a pinafore dress.",
  },
  {
    id: "children-dress-pinafore-strap-facings",
    name: "Pinafore Strap Facings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 153,
    description:
      "Optional inner pieces clean-finishing and reinforcing pinafore shoulder straps.",
  },
  {
    id: "children-dress-front-bib",
    name: "Front Bib",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 154,
    description:
      "Optional front bib panel used in apron, pinafore or decorative dress construction.",
  },
  {
    id: "children-dress-front-bib-facing",
    name: "Front Bib Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 155,
    description:
      "Optional inner facing clean-finishing the upper and side edges of the front bib.",
  },
  {
    id: "children-dress-front-chest-logo-backing",
    name: "Front Chest Logo Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 156,
    description:
      "Optional internal support patch positioned behind chest embroidery, appliqué or branding.",
  },
  {
    id: "children-dress-back-logo-backing",
    name: "Back Logo Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 157,
    description:
      "Optional internal support patch positioned behind back embroidery or decorative branding.",
  },
  {
    id: "children-dress-skirt-decoration-backing",
    name: "Skirt Decoration Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 158,
    description:
      "Optional stabilising patches supporting appliqué, embroidery, sequins or decorative motifs on the skirt.",
  },
  {
    id: "children-dress-neckline-decoration-backing",
    name: "Neckline Decoration Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 159,
    description:
      "Optional internal support piece for embroidery, beading or appliqué around the neckline.",
  },
  {
    id: "children-dress-name-label-backing",
    name: "Name Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 160,
    description:
      "Optional backing piece supporting a child's name, school or identification label.",
  },
  {
    id: "children-dress-brand-label-backing",
    name: "Brand Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 161,
    description:
      "Optional support piece for a woven, printed or heat-transfer brand label.",
  },
  {
    id: "children-dress-care-label-backing",
    name: "Care Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 162,
    description:
      "Optional internal support piece for care, size and fibre-content labels.",
  },
  {
    id: "children-dress-button-backing",
    name: "Button Attachment Backing",
    required: false,
    cutQuantity: 6,
    cutOnFold: false,
    custom: false,
    sequence: 163,
    description:
      "Optional reinforcement patches positioned behind button attachment points.",
  },
  {
    id: "children-dress-buttonhole-backing",
    name: "Buttonhole Backing",
    required: false,
    cutQuantity: 6,
    cutOnFold: false,
    custom: false,
    sequence: 164,
    description:
      "Optional reinforcement patches stabilising buttonhole positions.",
  },
  {
    id: "children-dress-snap-backing",
    name: "Snap Fastener Backing",
    required: false,
    cutQuantity: 6,
    cutOnFold: false,
    custom: false,
    sequence: 165,
    description:
      "Optional reinforcement patches supporting snap-fastener installation.",
  },
  {
    id: "children-dress-neck-seam-cover",
    name: "Back Neck Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 166,
    description:
      "Optional soft tape or binding covering the back neck seam.",
  },
  {
    id: "children-dress-shoulder-seam-covers",
    name: "Shoulder Seam Covers",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 167,
    description:
      "Optional internal strips covering shoulder seams for comfort and clean finishing.",
  },
  {
    id: "children-dress-side-seam-covers",
    name: "Side Seam Covers",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 168,
    description:
      "Optional internal strips covering side seams to reduce irritation.",
  },
  {
    id: "children-dress-waist-seam-cover",
    name: "Waist Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 169,
    description:
      "Optional internal strip covering the bodice-to-skirt joining seam.",
  },
  {
    id: "children-dress-hem-facing-front",
    name: "Front Hem Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 170,
    description:
      "Optional shaped facing clean-finishing a curved, structured or high-low front hem.",
  },
  {
    id: "children-dress-hem-facing-back",
    name: "Back Hem Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 171,
    description:
      "Optional shaped facing clean-finishing a curved, structured or high-low back hem.",
  },
];

export default childrenDressPatternMaster;