export const childrenHoodiePatternMaster = [
  {
    id: "children-hoodie-front-body",
    name: "Front Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 1,
    description:
      "Primary front body panel forming the chest, abdomen and front hem of a pullover children's hoodie.",
  },
  {
    id: "children-hoodie-back-body",
    name: "Back Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 2,
    description:
      "Primary back body panel forming the upper back, lower back and rear hem of the hoodie.",
  },
  {
    id: "children-hoodie-left-front-body",
    name: "Left Front Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Optional left front body panel used in full-zip, half-zip, asymmetric or panelled hoodie construction.",
  },
  {
    id: "children-hoodie-right-front-body",
    name: "Right Front Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional right front body panel used in full-zip, half-zip, asymmetric or panelled hoodie construction.",
  },
  {
    id: "children-hoodie-left-back-body",
    name: "Left Back Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional left back panel used in centre-back seam, colour-blocked or ergonomically shaped hoodie construction.",
  },
  {
    id: "children-hoodie-right-back-body",
    name: "Right Back Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional right back panel used in centre-back seam, colour-blocked or ergonomically shaped hoodie construction.",
  },
  {
    id: "children-hoodie-front-yoke",
    name: "Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 7,
    description:
      "Optional upper-front yoke used for styling, reinforcement, contrast fabric or shoulder shaping.",
  },
  {
    id: "children-hoodie-back-yoke",
    name: "Back Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 8,
    description:
      "Optional upper-back yoke providing shoulder stability, styling or contrast construction.",
  },
  {
    id: "children-hoodie-left-front-yoke",
    name: "Left Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional left front yoke used in asymmetric, zip-front or colour-blocked children's hoodies.",
  },
  {
    id: "children-hoodie-right-front-yoke",
    name: "Right Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Optional right front yoke used in asymmetric, zip-front or colour-blocked children's hoodies.",
  },
  {
    id: "children-hoodie-centre-front-panel",
    name: "Centre Front Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Optional central panel used for a zip opening, decorative construction, print placement or colour blocking.",
  },
  {
    id: "children-hoodie-centre-back-panel",
    name: "Centre Back Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Optional central back insert used for shaping, branding, ventilation or decorative styling.",
  },
  {
    id: "children-hoodie-left-side-panel",
    name: "Left Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional left side panel used for body shaping, contrast fabric, ventilation or mobility.",
  },
  {
    id: "children-hoodie-right-side-panel",
    name: "Right Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Optional right side panel used for body shaping, contrast fabric, ventilation or mobility.",
  },
  {
    id: "children-hoodie-front-lower-panel",
    name: "Front Lower Body Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 15,
    description:
      "Optional lower front panel used for colour blocking, pocket integration or reinforced construction.",
  },
  {
    id: "children-hoodie-back-lower-panel",
    name: "Back Lower Body Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 16,
    description:
      "Optional lower back panel used for colour blocking, durability or shaped hem construction.",
  },
  {
    id: "children-hoodie-left-shoulder-panel",
    name: "Left Shoulder Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional left shoulder insert used for reinforcement, contrast styling or ergonomic shaping.",
  },
  {
    id: "children-hoodie-right-shoulder-panel",
    name: "Right Shoulder Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional right shoulder insert used for reinforcement, contrast styling or ergonomic shaping.",
  },
  {
    id: "children-hoodie-set-in-sleeves",
    name: "Set-In Sleeves",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Primary pair of set-in sleeves providing standard arm coverage and shoulder shaping.",
  },
  {
    id: "children-hoodie-left-set-in-sleeve",
    name: "Left Set-In Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Optional anatomically or decoratively shaped left sleeve used in directional hoodie construction.",
  },
  {
    id: "children-hoodie-right-set-in-sleeve",
    name: "Right Set-In Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Optional anatomically or decoratively shaped right sleeve used in directional hoodie construction.",
  },
  {
    id: "children-hoodie-raglan-sleeves",
    name: "Raglan Sleeves",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional pair of raglan sleeves extending to the neckline for improved movement and comfort.",
  },
  {
    id: "children-hoodie-left-raglan-sleeve",
    name: "Left Raglan Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional individually shaped left raglan sleeve for directional or colour-blocked construction.",
  },
  {
    id: "children-hoodie-right-raglan-sleeve",
    name: "Right Raglan Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional individually shaped right raglan sleeve for directional or colour-blocked construction.",
  },
  {
    id: "children-hoodie-front-sleeve-panels",
    name: "Front Sleeve Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional front sleeve sections used for articulation, contrast styling or reinforcement.",
  },
  {
    id: "children-hoodie-back-sleeve-panels",
    name: "Back Sleeve Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional rear sleeve sections supporting elbow shaping, movement and durability.",
  },
  {
    id: "children-hoodie-upper-sleeve-panels",
    name: "Upper Sleeve Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional upper-arm panels used for colour blocking, logos or reinforced shoulder construction.",
  },
  {
    id: "children-hoodie-lower-sleeve-panels",
    name: "Lower Sleeve Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional lower-arm panels used for contrast fabric, shaping or abrasion resistance.",
  },
  {
    id: "children-hoodie-elbow-panels",
    name: "Elbow Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional shaped panels positioned at both elbows for articulation or style definition.",
  },
  {
    id: "children-hoodie-elbow-reinforcements",
    name: "Elbow Reinforcements",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Optional abrasion-resistant patches protecting both elbow areas during active use.",
  },
  {
    id: "children-hoodie-sleeve-cuffs",
    name: "Sleeve Cuffs",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Primary rib-knit or self-fabric cuffs finishing both sleeve openings.",
  },
  {
    id: "children-hoodie-left-sleeve-cuff",
    name: "Left Sleeve Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional individually shaped left cuff used in directional or asymmetrical hoodie construction.",
  },
  {
    id: "children-hoodie-right-sleeve-cuff",
    name: "Right Sleeve Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Optional individually shaped right cuff used in directional or asymmetrical hoodie construction.",
  },
  {
    id: "children-hoodie-thumbhole-cuffs",
    name: "Thumbhole Sleeve Cuffs",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional extended cuffs containing thumb openings for warmth and sleeve stability.",
  },
  {
    id: "children-hoodie-thumbhole-cuff-inserts",
    name: "Thumbhole Cuff Inserts",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional shaped inserts forming and reinforcing the thumb openings.",
  },
  {
    id: "children-hoodie-thumbhole-reinforcements",
    name: "Thumbhole Reinforcements",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional support pieces protecting thumbhole edges from stretch and wear.",
  },
  {
    id: "children-hoodie-foldover-mitten-cuffs",
    name: "Foldover Mitten Cuffs",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Optional extended cuffs that fold over the hands to provide additional warmth.",
  },
  {
    id: "children-hoodie-mitten-cuff-linings",
    name: "Foldover Mitten Cuff Linings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Optional soft inner pieces completing and lining foldover mitten cuffs.",
  },
  {
    id: "children-hoodie-two-piece-hood-left",
    name: "Left Hood Panel",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Primary left panel forming one side of a standard two-piece children's hood.",
  },
  {
    id: "children-hoodie-two-piece-hood-right",
    name: "Right Hood Panel",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Primary right panel forming the opposite side of a standard two-piece children's hood.",
  },
  {
    id: "children-hoodie-three-piece-hood-centre",
    name: "Hood Centre Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional centre hood panel providing additional crown depth and improved three-dimensional shape.",
  },
  {
    id: "children-hoodie-three-piece-hood-left",
    name: "Three-Piece Hood Left Side",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional left side panel used with a centre panel in three-piece hood construction.",
  },
  {
    id: "children-hoodie-three-piece-hood-right",
    name: "Three-Piece Hood Right Side",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional right side panel used with a centre panel in three-piece hood construction.",
  },
  {
    id: "children-hoodie-hood-front-extension-left",
    name: "Left Hood Front Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional extended left hood edge providing additional face coverage and overlap.",
  },
  {
    id: "children-hoodie-hood-front-extension-right",
    name: "Right Hood Front Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional extended right hood edge providing additional face coverage and overlap.",
  },
  {
    id: "children-hoodie-hood-opening-band",
    name: "Hood Opening Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional rib-knit or self-fabric band finishing and stabilising the hood opening.",
  },
  {
    id: "children-hoodie-hood-facing-left",
    name: "Left Hood Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional facing clean-finishing the left side of the hood opening.",
  },
  {
    id: "children-hoodie-hood-facing-right",
    name: "Right Hood Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional facing clean-finishing the right side of the hood opening.",
  },
  {
    id: "children-hoodie-hood-lining-left",
    name: "Left Hood Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional soft lining panel covering the inside left side of the hood.",
  },
  {
    id: "children-hoodie-hood-lining-right",
    name: "Right Hood Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional soft lining panel covering the inside right side of the hood.",
  },
  {
    id: "children-hoodie-hood-lining-centre",
    name: "Hood Centre Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional lining panel covering the centre section of a three-piece hood.",
  },
  {
    id: "children-hoodie-hood-neck-seam-cover",
    name: "Hood Neck Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Optional soft tape or binding covering the hood-to-neckline attachment seam.",
  },
  {
    id: "children-hoodie-hood-drawcord-channel",
    name: "Hood Drawcord Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Optional casing around the hood opening containing an adjustment cord.",
  },
  {
    id: "children-hoodie-hood-eyelet-reinforcements",
    name: "Hood Eyelet Reinforcements",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Optional support patches stabilising hood drawcord eyelets or cord exits.",
  },
  {
    id: "children-hoodie-hood-cord-lock-backing",
    name: "Hood Cord-Lock Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Optional reinforcement pieces supporting child-safe hood adjustment components.",
  },
  {
    id: "children-hoodie-hood-ear-upper-pieces",
    name: "Decorative Hood Ear Upper Pieces",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Optional upper pieces forming decorative animal ears attached to the hood.",
  },
  {
    id: "children-hoodie-hood-ear-under-pieces",
    name: "Decorative Hood Ear Under Pieces",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Optional under pieces completing decorative hood ears.",
  },
  {
    id: "children-hoodie-hood-ear-interfacing",
    name: "Decorative Hood Ear Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 58,
    description:
      "Optional lightweight reinforcement stabilising decorative hood ears.",
  },
  {
    id: "children-hoodie-kangaroo-pocket",
    name: "Kangaroo Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 59,
    description:
      "Optional large front pocket with openings at both sides for hand warming and storage.",
  },
  {
    id: "children-hoodie-kangaroo-pocket-left",
    name: "Left Split Kangaroo Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 60,
    description:
      "Optional left half of a split kangaroo pocket used with a centre-front zip.",
  },
  {
    id: "children-hoodie-kangaroo-pocket-right",
    name: "Right Split Kangaroo Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 61,
    description:
      "Optional right half of a split kangaroo pocket used with a centre-front zip.",
  },
  {
    id: "children-hoodie-kangaroo-pocket-facing-left",
    name: "Left Kangaroo Pocket Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 62,
    description:
      "Optional facing reinforcing and clean-finishing the left kangaroo pocket opening.",
  },
  {
    id: "children-hoodie-kangaroo-pocket-facing-right",
    name: "Right Kangaroo Pocket Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional facing reinforcing and clean-finishing the right kangaroo pocket opening.",
  },
  {
    id: "children-hoodie-left-patch-pocket",
    name: "Left Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 64,
    description:
      "Optional separate patch pocket positioned on the left front body.",
  },
  {
    id: "children-hoodie-right-patch-pocket",
    name: "Right Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 65,
    description:
      "Optional separate patch pocket positioned on the right front body.",
  },
  {
    id: "children-hoodie-left-welt-pocket-bag",
    name: "Left Welt Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 66,
    description:
      "Optional pair of bag pieces forming the internal left welt pocket.",
  },
  {
    id: "children-hoodie-right-welt-pocket-bag",
    name: "Right Welt Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 67,
    description:
      "Optional pair of bag pieces forming the internal right welt pocket.",
  },
  {
    id: "children-hoodie-left-welt",
    name: "Left Pocket Welt",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 68,
    description:
      "Optional welt strip forming and stabilising the left pocket opening.",
  },
  {
    id: "children-hoodie-right-welt",
    name: "Right Pocket Welt",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 69,
    description:
      "Optional welt strip forming and stabilising the right pocket opening.",
  },
  {
    id: "children-hoodie-pocket-zip-guards",
    name: "Pocket Zip Guards",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 70,
    description:
      "Optional protective strips positioned behind zipped pocket openings.",
  },
  {
    id: "children-hoodie-chest-pocket",
    name: "Chest Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 71,
    description:
      "Optional small patch, welt or zipped pocket positioned on the front chest.",
  },
  {
    id: "children-hoodie-chest-pocket-flap-upper",
    name: "Chest Pocket Flap Upper",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 72,
    description:
      "Optional upper flap panel covering the chest pocket opening.",
  },
  {
    id: "children-hoodie-chest-pocket-flap-under",
    name: "Chest Pocket Flap Under",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 73,
    description:
      "Optional under-flap panel completing the chest pocket flap.",
  },
  {
    id: "children-hoodie-chest-pocket-flap-interfacing",
    name: "Chest Pocket Flap Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 74,
    description:
      "Optional lightweight reinforcement stabilising the chest pocket flap.",
  },
  {
    id: "children-hoodie-front-zip-left-facing",
    name: "Left Front Zip Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 75,
    description:
      "Optional facing stabilising and finishing the left side of a centre-front zip opening.",
  },
  {
    id: "children-hoodie-front-zip-right-facing",
    name: "Right Front Zip Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 76,
    description:
      "Optional facing stabilising and finishing the right side of a centre-front zip opening.",
  },
  {
    id: "children-hoodie-inner-zip-guard",
    name: "Inner Front Zip Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 77,
    description:
      "Optional protective strip positioned behind the front zip to prevent skin contact and snagging.",
  },
  {
    id: "children-hoodie-zip-chin-guard",
    name: "Zip Chin Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 78,
    description:
      "Optional soft guard covering the upper zip end near the child's chin.",
  },
  {
    id: "children-hoodie-zip-top-reinforcement",
    name: "Front Zip Top Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 79,
    description:
      "Optional support patch reinforcing the upper front zip termination.",
  },
  {
    id: "children-hoodie-zip-bottom-reinforcement",
    name: "Front Zip Bottom Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 80,
    description:
      "Optional support patch reinforcing the lower front zip termination.",
  },
  {
    id: "children-hoodie-half-zip-placket-left",
    name: "Half-Zip Left Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 81,
    description:
      "Optional left placket panel forming one side of a half-zip neck opening.",
  },
  {
    id: "children-hoodie-half-zip-placket-right",
    name: "Half-Zip Right Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 82,
    description:
      "Optional right placket panel forming the opposite side of a half-zip neck opening.",
  },
  {
    id: "children-hoodie-half-zip-underlay",
    name: "Half-Zip Underlay",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 83,
    description:
      "Optional protective underlay positioned behind a half-zip opening.",
  },
  {
    id: "children-hoodie-neckband",
    name: "Neckband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 84,
    description:
      "Optional rib-knit or self-fabric band finishing the neckline in hoodless or removable-hood styles.",
  },
  {
    id: "children-hoodie-stand-collar-outer",
    name: "Outer Stand Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 85,
    description:
      "Optional outer collar panel forming a raised neck section beneath or instead of the hood.",
  },
  {
    id: "children-hoodie-stand-collar-inner",
    name: "Inner Stand Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 86,
    description:
      "Optional inner collar panel completing and lining the stand collar.",
  },
  {
    id: "children-hoodie-collar-interfacing",
    name: "Stand Collar Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 87,
    description:
      "Optional lightweight reinforcement stabilising the stand collar.",
  },
  {
    id: "children-hoodie-hem-band",
    name: "Bottom Hem Band",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 88,
    description:
      "Primary rib-knit or self-fabric band finishing and controlling the lower body opening.",
  },
  {
    id: "children-hoodie-front-hem-band",
    name: "Front Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 89,
    description:
      "Optional separate front section of a divided hem band.",
  },
  {
    id: "children-hoodie-back-hem-band",
    name: "Back Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 90,
    description:
      "Optional separate back section of a divided hem band.",
  },
  {
    id: "children-hoodie-left-front-hem-band",
    name: "Left Front Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 91,
    description:
      "Optional left front hem-band section used in full-zip hoodie construction.",
  },
  {
    id: "children-hoodie-right-front-hem-band",
    name: "Right Front Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 92,
    description:
      "Optional right front hem-band section used in full-zip hoodie construction.",
  },
  {
    id: "children-hoodie-shaped-front-hem-facing",
    name: "Shaped Front Hem Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 93,
    description:
      "Optional facing clean-finishing a curved, dipped or split front hem.",
  },
  {
    id: "children-hoodie-shaped-back-hem-facing",
    name: "Shaped Back Hem Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 94,
    description:
      "Optional facing clean-finishing a curved, dropped or shaped back hem.",
  },
  {
    id: "children-hoodie-side-split-facings",
    name: "Side Split Facings",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 95,
    description:
      "Optional facing pieces reinforcing and finishing side-hem openings.",
  },
  {
    id: "children-hoodie-front-body-lining",
    name: "Front Body Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 96,
    description:
      "Optional lining panel covering the inside front body for comfort, warmth or clean finishing.",
  },
  {
    id: "children-hoodie-back-body-lining",
    name: "Back Body Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 97,
    description:
      "Optional lining panel covering the inside back body.",
  },
  {
    id: "children-hoodie-sleeve-linings",
    name: "Sleeve Linings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 98,
    description:
      "Optional pair of lining pieces covering the inside of both sleeves.",
  },
  {
    id: "children-hoodie-fleece-body-lining-front",
    name: "Front Fleece Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 99,
    description:
      "Optional fleece lining panel providing additional warmth inside the front body.",
  },
  {
    id: "children-hoodie-fleece-body-lining-back",
    name: "Back Fleece Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 100,
    description:
      "Optional fleece lining panel providing additional warmth inside the back body.",
  },
  {
    id: "children-hoodie-thermal-sleeve-linings",
    name: "Thermal Sleeve Linings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 101,
    description:
      "Optional insulated lining pieces providing additional warmth through both sleeves.",
  },
  {
    id: "children-hoodie-front-insulation",
    name: "Front Body Insulation",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 102,
    description:
      "Optional lightweight insulation layer positioned between the front shell and lining.",
  },
  {
    id: "children-hoodie-back-insulation",
    name: "Back Body Insulation",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 103,
    description:
      "Optional lightweight insulation layer positioned between the back shell and lining.",
  },
  {
    id: "children-hoodie-sleeve-insulation",
    name: "Sleeve Insulation",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 104,
    description:
      "Optional insulation layers positioned between the sleeve shell and lining.",
  },
  {
    id: "children-hoodie-windproof-front-membrane",
    name: "Windproof Front Membrane",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 105,
    description:
      "Optional membrane layer reducing wind penetration through the front body.",
  },
  {
    id: "children-hoodie-windproof-back-membrane",
    name: "Windproof Back Membrane",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 106,
    description:
      "Optional membrane layer reducing wind penetration through the back body.",
  },
  {
    id: "children-hoodie-windproof-sleeve-membranes",
    name: "Windproof Sleeve Membranes",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 107,
    description:
      "Optional membrane layers reducing wind penetration through both sleeves.",
  },
  {
    id: "children-hoodie-neck-tape",
    name: "Back Neck Tape",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 108,
    description:
      "Optional soft tape covering and stabilising the back neckline seam.",
  },
  {
    id: "children-hoodie-shoulder-seam-covers",
    name: "Shoulder Seam Covers",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 109,
    description:
      "Optional internal strips covering the shoulder seams for comfort and durability.",
  },
  {
    id: "children-hoodie-side-seam-covers",
    name: "Side Seam Covers",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 110,
    description:
      "Optional internal strips covering body side seams for comfort and clean finishing.",
  },
  {
    id: "children-hoodie-armhole-seam-covers",
    name: "Armhole Seam Covers",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 111,
    description:
      "Optional soft strips covering armhole seams to reduce bulk and irritation.",
  },
  {
    id: "children-hoodie-front-logo-backing",
    name: "Front Logo Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 112,
    description:
      "Optional internal support patch positioned behind chest or centre-front branding.",
  },
  {
    id: "children-hoodie-back-logo-backing",
    name: "Back Logo Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 113,
    description:
      "Optional internal support patch positioned behind back embroidery, appliqué or branding.",
  },
  {
    id: "children-hoodie-sleeve-logo-backing",
    name: "Sleeve Logo Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 114,
    description:
      "Optional support patches positioned behind sleeve logos, badges or decorative applications.",
  },
  {
    id: "children-hoodie-reflective-front-panel",
    name: "Reflective Front Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 115,
    description:
      "Optional reflective or high-visibility panel positioned on the front body.",
  },
  {
    id: "children-hoodie-reflective-back-panel",
    name: "Reflective Back Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 116,
    description:
      "Optional reflective or high-visibility panel positioned on the back body.",
  },
  {
    id: "children-hoodie-reflective-sleeve-panels",
    name: "Reflective Sleeve Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 117,
    description:
      "Optional reflective panels positioned on both sleeves for improved visibility.",
  },
  {
    id: "children-hoodie-name-label-backing",
    name: "Name Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 118,
    description:
      "Optional support piece for a child's name label, school label or identification patch.",
  },
  {
    id: "children-hoodie-brand-label-backing",
    name: "Brand Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 119,
    description:
      "Optional support piece for a woven, printed or heat-transfer brand label.",
  },
  {
    id: "children-hoodie-care-label-backing",
    name: "Care Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 120,
    description:
      "Optional internal support piece for care, size and fibre-content labels.",
  },
  {
    id: "children-hoodie-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 121,
    description:
      "Optional backing patches supporting embroidery, appliqué, badges, transfers or decorative attachments.",
  },
];

export default childrenHoodiePatternMaster;