export const chinoPatternMaster = [
  {
    id: "chino-left-front-leg",
    name: "Left Front Leg",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Main left front trouser panel including waist, hip, front rise, inseam, outseam and hem shaping.",
  },
  {
    id: "chino-right-front-leg",
    name: "Right Front Leg",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Main right front trouser panel including waist, hip, front rise, inseam, outseam and hem shaping.",
  },
  {
    id: "chino-left-back-leg",
    name: "Left Back Leg",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Main left back trouser panel shaped for seat, back rise, thigh, knee and hem.",
  },
  {
    id: "chino-right-back-leg",
    name: "Right Back Leg",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Main right back trouser panel shaped for seat, back rise, thigh, knee and hem.",
  },
  {
    id: "chino-left-front-pocket-facing",
    name: "Left Front Pocket Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Left slant-pocket facing used to clean-finish and stabilise the front pocket opening.",
  },
  {
    id: "chino-right-front-pocket-facing",
    name: "Right Front Pocket Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Right slant-pocket facing used to clean-finish and stabilise the front pocket opening.",
  },
  {
    id: "chino-left-front-pocket-bag",
    name: "Left Front Pocket Bag",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Pair of pocket-bag sections forming the complete left front pocket.",
  },
  {
    id: "chino-right-front-pocket-bag",
    name: "Right Front Pocket Bag",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Pair of pocket-bag sections forming the complete right front pocket.",
  },
  {
    id: "chino-left-pocket-bearer",
    name: "Left Front Pocket Bearer",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Left pocket bearer or shield supporting the pocket opening and restoring the visible body fabric behind it.",
  },
  {
    id: "chino-right-pocket-bearer",
    name: "Right Front Pocket Bearer",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Right pocket bearer or shield supporting the pocket opening and restoring the visible body fabric behind it.",
  },
  {
    id: "chino-left-back-pocket-welt",
    name: "Left Back Pocket Welt",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Pair of welt pieces forming the optional left back pocket opening.",
  },
  {
    id: "chino-right-back-pocket-welt",
    name: "Right Back Pocket Welt",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Pair of welt pieces forming the optional right back pocket opening.",
  },
  {
    id: "chino-left-back-pocket-bag",
    name: "Left Back Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Upper and lower bag sections forming the optional left back pocket.",
  },
  {
    id: "chino-right-back-pocket-bag",
    name: "Right Back Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Upper and lower bag sections forming the optional right back pocket.",
  },
  {
    id: "chino-left-back-pocket-button-loop",
    name: "Left Back Pocket Button Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional loop used to secure the left back welt pocket with a button.",
  },
  {
    id: "chino-right-back-pocket-button-loop",
    name: "Right Back Pocket Button Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional loop used to secure the right back welt pocket with a button.",
  },
  {
    id: "chino-left-waistband",
    name: "Left Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Left shaped waistband section extending from centre back to centre front.",
  },
  {
    id: "chino-right-waistband",
    name: "Right Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Right shaped waistband section extending from centre back to centre front.",
  },
  {
    id: "chino-left-inner-waistband",
    name: "Left Inner Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Left inner waistband or curtain section used to finish and reinforce the waist.",
  },
  {
    id: "chino-right-inner-waistband",
    name: "Right Inner Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Right inner waistband or curtain section used to finish and reinforce the waist.",
  },
  {
    id: "chino-waistband-interfacing",
    name: "Waistband Interfacing",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Pair of fusible or non-fusible reinforcement sections supporting the left and right waistbands.",
  },
  {
    id: "chino-front-fly",
    name: "Front Fly",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Outer fly extension supporting the front zip or button fastening.",
  },
  {
    id: "chino-fly-shield",
    name: "Fly Shield",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Internal fly shield protecting the wearer and concealing the fastening.",
  },
  {
    id: "chino-fly-interfacing",
    name: "Fly Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional reinforcement supporting the fly shape and zip installation.",
  },
  {
    id: "chino-belt-loop",
    name: "Belt Loop Strip",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Continuous strip used to produce the complete set of waistband belt loops.",
  },
  {
    id: "chino-front-coin-pocket",
    name: "Front Coin Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional small coin or ticket pocket positioned inside a front pocket opening.",
  },
  {
    id: "chino-coin-pocket-facing",
    name: "Coin Pocket Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional facing used to clean-finish and reinforce the coin-pocket opening.",
  },
  {
    id: "chino-left-front-crease-reinforcement",
    name: "Left Front Crease Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional narrow reinforcement supporting a permanent pressed crease on the left front leg.",
  },
  {
    id: "chino-right-front-crease-reinforcement",
    name: "Right Front Crease Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional narrow reinforcement supporting a permanent pressed crease on the right front leg.",
  },
  {
    id: "chino-left-knee-lining",
    name: "Left Knee Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Optional left knee lining reducing friction and improving formal trouser drape.",
  },
  {
    id: "chino-right-knee-lining",
    name: "Right Knee Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Optional right knee lining reducing friction and improving formal trouser drape.",
  },
  {
    id: "chino-left-hem-kick-tape",
    name: "Left Hem Kick Tape",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional protective tape reinforcing the inside of the left trouser hem.",
  },
  {
    id: "chino-right-hem-kick-tape",
    name: "Right Hem Kick Tape",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Optional protective tape reinforcing the inside of the right trouser hem.",
  },
  {
    id: "chino-crotch-reinforcement",
    name: "Crotch Reinforcement Patch",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional internal reinforcement patch supporting the crotch intersection in workwear or heavy-duty chino styles.",
  },
  {
    id: "chino-back-waist-extension",
    name: "Back Waist Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional shaped centre-back extension improving waist fit and adjustment.",
  },
  {
    id: "chino-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional backing supporting embroidery, badge, heat transfer or branding.",
  },
];

export default chinoPatternMaster;