import { PatternLibraryItem } from "./index";

export const hoodiePatternMaster: PatternLibraryItem[] = [
  {
    id: "hoodie-front",
    name: "Hoodie Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 1,
    description:
      "Main front body panel extending from the neckline and shoulders to the lower hem.",
  },
  {
    id: "hoodie-back",
    name: "Hoodie Back",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 2,
    description:
      "Main back body panel extending from the back neckline and shoulders to the lower hem.",
  },
  {
    id: "hoodie-sleeve",
    name: "Sleeve",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Left and right sleeve panels forming the main arm construction of the hoodie.",
  },
  {
    id: "hoodie-left-hood",
    name: "Left Hood Panel",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Left outer hood panel forming one side of the standard two-piece hood construction.",
  },
  {
    id: "hoodie-right-hood",
    name: "Right Hood Panel",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Right outer hood panel joined to the left hood panel along the centre hood seam.",
  },
  {
    id: "hoodie-centre-hood-panel",
    name: "Centre Hood Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional centre panel used in three-piece hood construction to improve shape and head fitting.",
  },
  {
    id: "hoodie-left-hood-lining",
    name: "Left Hood Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Left internal hood lining panel providing comfort, coverage and a clean internal finish.",
  },
  {
    id: "hoodie-right-hood-lining",
    name: "Right Hood Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Right internal hood lining panel joined to the left hood lining along the centre seam.",
  },
  {
    id: "hoodie-hood-facing",
    name: "Hood Opening Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Facing components used to reinforce and finish the front opening edge of the hood.",
  },
  {
    id: "hoodie-neck-binding",
    name: "Back Neck Binding",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Binding strip used to cover, reinforce and finish the back neckline seam.",
  },
  {
    id: "hoodie-kangaroo-pocket",
    name: "Kangaroo Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 11,
    description:
      "Single front patch pocket with openings at both sides, commonly used on pullover hoodies.",
  },
  {
    id: "hoodie-kangaroo-pocket-facing",
    name: "Kangaroo Pocket Opening Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Facing components used to reinforce and finish both hand openings of the kangaroo pocket.",
  },
  {
    id: "hoodie-zip-pocket-bag",
    name: "Front Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Separate left and right pocket bags used mainly for full-zip hoodie construction.",
  },
  {
    id: "hoodie-pocket-facing",
    name: "Front Pocket Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Facing components used to finish and stabilise the openings of separate front pockets.",
  },
  {
    id: "hoodie-sleeve-rib-cuff",
    name: "Sleeve Rib Cuff",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Knitted rib components fitted to the left and right sleeve openings.",
  },
  {
    id: "hoodie-bottom-rib-band",
    name: "Bottom Rib Band",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Knitted rib band attached around the lower edge of the hoodie body.",
  },
  {
    id: "hoodie-drawcord-channel",
    name: "Hood Drawcord Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Channel strip or extension forming the tunnel through which the hood drawcord passes.",
  },
  {
    id: "hoodie-eyelet-reinforcement",
    name: "Eyelet Reinforcement Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Small reinforcement patches positioned behind the hood drawcord eyelets.",
  },
  {
    id: "hoodie-zipper-facing",
    name: "Front Zipper Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Left and right internal facings used to reinforce and finish a full-length front zipper opening.",
  },
  {
    id: "hoodie-zipper-guard",
    name: "Zipper Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Internal protective strip positioned beneath the front zipper for comfort and garment protection.",
  },
  {
    id: "hoodie-thumb-cuff",
    name: "Thumb-Hole Cuff",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Extended cuff components containing thumb openings for sportswear or cold-weather hoodie styles.",
  },
  {
    id: "hoodie-shoulder-reinforcement-tape",
    name: "Shoulder Reinforcement Tape",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Reinforcement tape applied along both shoulder seams to improve stability and durability.",
  },
  {
    id: "hoodie-back-neck-patch",
    name: "Back Neck Reinforcement Patch",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 23,
    description:
      "Internal reinforcement patch supporting the back neckline and hood attachment area.",
  },
  {
    id: "hoodie-elbow-patch",
    name: "Elbow Reinforcement Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional reinforcement patches positioned over the sleeve elbow areas for workwear or heavy-duty styles.",
  },
  {
    id: "hoodie-care-label-guide",
    name: "Care Label Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Reference guide identifying the approved position for the garment care label.",
  },
  {
    id: "hoodie-brand-label-guide",
    name: "Brand Label Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Reference guide identifying the standard brand label position at the back neckline.",
  },
  {
    id: "hoodie-chest-print-guide",
    name: "Chest Print Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Reference guide used to control embroidery, screen print or heat-transfer placement on the front body.",
  },
  {
    id: "hoodie-back-print-guide",
    name: "Back Print Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Reference guide used to control print, embroidery or transfer placement on the back body panel.",
  },
];