import { PatternLibraryItem } from "./index";

export const industrialCoverallPatternMaster: PatternLibraryItem[] = [
  {
    id: "industrial-coverall-left-front",
    name: "Left Front Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Main left front body panel extending from the shoulder to the lower leg area.",
  },
  {
    id: "industrial-coverall-right-front",
    name: "Right Front Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Main right front body panel forming the opposite side of the coverall front.",
  },
  {
    id: "industrial-coverall-left-back",
    name: "Left Back Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Left back body panel extending from the shoulder and back waist to the lower leg.",
  },
  {
    id: "industrial-coverall-right-back",
    name: "Right Back Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Right back body panel joined to the left back along the centre-back seam.",
  },
  {
    id: "industrial-coverall-action-back-left",
    name: "Left Action Back Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional expansion panel allowing additional movement across the left shoulder and upper back.",
  },
  {
    id: "industrial-coverall-action-back-right",
    name: "Right Action Back Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional expansion panel allowing additional movement across the right shoulder and upper back.",
  },
  {
    id: "industrial-coverall-back-yoke",
    name: "Back Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 7,
    description:
      "Upper back reinforcement and shaping panel positioned across the shoulder area.",
  },
  {
    id: "industrial-coverall-front-yoke-left",
    name: "Left Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Optional upper-left front panel used for styling, reinforcement or colour blocking.",
  },
  {
    id: "industrial-coverall-front-yoke-right",
    name: "Right Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional upper-right front panel used for styling, reinforcement or colour blocking.",
  },
  {
    id: "industrial-coverall-sleeve-left",
    name: "Left Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Main left sleeve panel extending from the armhole to the wrist opening.",
  },
  {
    id: "industrial-coverall-sleeve-right",
    name: "Right Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Main right sleeve panel extending from the armhole to the wrist opening.",
  },
  {
    id: "industrial-coverall-elbow-patch-left",
    name: "Left Elbow Reinforcement Patch",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Reinforcement patch positioned over the left elbow to improve abrasion resistance.",
  },
  {
    id: "industrial-coverall-elbow-patch-right",
    name: "Right Elbow Reinforcement Patch",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Reinforcement patch positioned over the right elbow to improve abrasion resistance.",
  },
  {
    id: "industrial-coverall-sleeve-cuff-left",
    name: "Left Sleeve Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Left wrist cuff component used for an adjustable or buttoned sleeve opening.",
  },
  {
    id: "industrial-coverall-sleeve-cuff-right",
    name: "Right Sleeve Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Right wrist cuff component used for an adjustable or buttoned sleeve opening.",
  },
  {
    id: "industrial-coverall-collar",
    name: "Collar",
    required: true,
    cutQuantity: 2,
    cutOnFold: true,
    custom: false,
    sequence: 16,
    description:
      "Upper and under collar components forming the main neckline collar construction.",
  },
  {
    id: "industrial-coverall-collar-stand",
    name: "Collar Stand",
    required: false,
    cutQuantity: 2,
    cutOnFold: true,
    custom: false,
    sequence: 17,
    description:
      "Inner and outer collar stand components supporting the collar around the neckline.",
  },
  {
    id: "industrial-coverall-front-zipper-facing-left",
    name: "Left Front Zipper Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Internal left facing used to reinforce and finish the centre-front zipper opening.",
  },
  {
    id: "industrial-coverall-front-zipper-facing-right",
    name: "Right Front Zipper Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Internal right facing used to reinforce and finish the centre-front zipper opening.",
  },
  {
    id: "industrial-coverall-zipper-guard",
    name: "Front Zipper Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Protective strip positioned beneath the front zipper to improve comfort and safety.",
  },
  {
    id: "industrial-coverall-storm-flap",
    name: "Front Storm Flap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "External flap covering the front zipper for additional protection from dust, wind or moisture.",
  },
  {
    id: "industrial-coverall-waist-casing",
    name: "Waist Elastic Casing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Internal or external casing component holding elastic at the back or full waist.",
  },
  {
    id: "industrial-coverall-waist-tab-left",
    name: "Left Waist Adjustment Tab",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Adjustable left waist tab used to control fit at the side waist.",
  },
  {
    id: "industrial-coverall-waist-tab-right",
    name: "Right Waist Adjustment Tab",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Adjustable right waist tab used to control fit at the side waist.",
  },
  {
    id: "industrial-coverall-chest-pocket-left",
    name: "Left Chest Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Left chest patch pocket used for tools, identification or personal items.",
  },
  {
    id: "industrial-coverall-chest-pocket-right",
    name: "Right Chest Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Right chest patch pocket used for tools, identification or personal items.",
  },
  {
    id: "industrial-coverall-chest-pocket-flap-left",
    name: "Left Chest Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Upper and under flap components covering the left chest pocket opening.",
  },
  {
    id: "industrial-coverall-chest-pocket-flap-right",
    name: "Right Chest Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Upper and under flap components covering the right chest pocket opening.",
  },
  {
    id: "industrial-coverall-side-pocket-left",
    name: "Left Side Pocket Bag",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Pocket bag components forming the left side-entry waist pocket.",
  },
  {
    id: "industrial-coverall-side-pocket-right",
    name: "Right Side Pocket Bag",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Pocket bag components forming the right side-entry waist pocket.",
  },
  {
    id: "industrial-coverall-side-pocket-facing-left",
    name: "Left Side Pocket Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Facing component used to reinforce and finish the left side pocket opening.",
  },
  {
    id: "industrial-coverall-side-pocket-facing-right",
    name: "Right Side Pocket Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Facing component used to reinforce and finish the right side pocket opening.",
  },
  {
    id: "industrial-coverall-back-pocket-left",
    name: "Left Back Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Patch pocket positioned on the left back trouser section.",
  },
  {
    id: "industrial-coverall-back-pocket-right",
    name: "Right Back Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Patch pocket positioned on the right back trouser section.",
  },
  {
    id: "industrial-coverall-cargo-pocket-left",
    name: "Left Cargo Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Large utility pocket positioned on the left thigh area.",
  },
  {
    id: "industrial-coverall-cargo-pocket-right",
    name: "Right Cargo Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Large utility pocket positioned on the right thigh area.",
  },
  {
    id: "industrial-coverall-cargo-pocket-flap-left",
    name: "Left Cargo Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Upper and under flap components covering the left cargo pocket.",
  },
  {
    id: "industrial-coverall-cargo-pocket-flap-right",
    name: "Right Cargo Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Upper and under flap components covering the right cargo pocket.",
  },
  {
    id: "industrial-coverall-tool-pocket",
    name: "Tool Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Narrow utility pocket designed to hold tools, rulers or similar equipment.",
  },
  {
    id: "industrial-coverall-hammer-loop",
    name: "Hammer Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Reinforced loop component used to carry a hammer or comparable hand tool.",
  },
  {
    id: "industrial-coverall-knee-patch-left",
    name: "Left Knee Reinforcement Patch",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Reinforcement panel positioned over the left knee for improved durability.",
  },
  {
    id: "industrial-coverall-knee-patch-right",
    name: "Right Knee Reinforcement Patch",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Reinforcement panel positioned over the right knee for improved durability.",
  },
  {
    id: "industrial-coverall-knee-pad-pocket-left",
    name: "Left Knee Pad Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional pocket positioned at the left knee to hold a removable protective knee pad.",
  },
  {
    id: "industrial-coverall-knee-pad-pocket-right",
    name: "Right Knee Pad Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional pocket positioned at the right knee to hold a removable protective knee pad.",
  },
  {
    id: "industrial-coverall-leg-hem-facing-left",
    name: "Left Leg Hem Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Facing component used to reinforce or finish the left leg opening.",
  },
  {
    id: "industrial-coverall-leg-hem-facing-right",
    name: "Right Leg Hem Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Facing component used to reinforce or finish the right leg opening.",
  },
  {
    id: "industrial-coverall-ankle-tab-left",
    name: "Left Ankle Adjustment Tab",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Adjustable tab used to control the width of the left leg opening.",
  },
  {
    id: "industrial-coverall-ankle-tab-right",
    name: "Right Ankle Adjustment Tab",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Adjustable tab used to control the width of the right leg opening.",
  },
  {
    id: "industrial-coverall-shoulder-reinforcement-left",
    name: "Left Shoulder Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Additional reinforcement panel supporting the left shoulder area.",
  },
  {
    id: "industrial-coverall-shoulder-reinforcement-right",
    name: "Right Shoulder Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Additional reinforcement panel supporting the right shoulder area.",
  },
  {
    id: "industrial-coverall-reflective-tape-chest-guide",
    name: "Chest Reflective Tape Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Reference guide identifying the correct reflective tape position across the chest.",
  },
  {
    id: "industrial-coverall-reflective-tape-back-guide",
    name: "Back Reflective Tape Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Reference guide identifying the correct reflective tape position across the back.",
  },
  {
    id: "industrial-coverall-reflective-tape-sleeve-guide",
    name: "Sleeve Reflective Tape Placement Guide",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Reference guides controlling reflective tape placement around both sleeves.",
  },
  {
    id: "industrial-coverall-reflective-tape-leg-guide",
    name: "Leg Reflective Tape Placement Guide",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Reference guides controlling reflective tape placement around both legs.",
  },
  {
    id: "industrial-coverall-bartack-guide",
    name: "Bartack Reinforcement Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Engineering guide identifying high-stress positions requiring bartack reinforcement.",
  },
  {
    id: "industrial-coverall-brand-label-guide",
    name: "Brand Label Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Reference guide identifying the approved position for the main brand label.",
  },
  {
    id: "industrial-coverall-care-label-guide",
    name: "Care Label Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Reference guide identifying the approved position for the garment care label.",
  },
  {
    id: "industrial-coverall-name-badge-guide",
    name: "Name Badge Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 58,
    description:
      "Reference guide identifying the approved position for a worker name badge or identification patch.",
  },
  {
    id: "industrial-coverall-company-logo-guide",
    name: "Company Logo Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 59,
    description:
      "Reference guide controlling embroidery, print or heat-transfer placement for the company logo.",
  },
];