export const jeansPatternMaster = [
  {
    id: "jeans-left-front-leg",
    name: "Left Front Leg",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Main left front denim leg panel including waist, hip, front rise, thigh, knee, inseam, outseam and hem shaping.",
  },
  {
    id: "jeans-right-front-leg",
    name: "Right Front Leg",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Main right front denim leg panel including waist, hip, front rise, thigh, knee, inseam, outseam and hem shaping.",
  },
  {
    id: "jeans-left-back-leg",
    name: "Left Back Leg",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Main left back denim leg panel shaped for seat, back rise, thigh, knee, inseam, outseam and hem.",
  },
  {
    id: "jeans-right-back-leg",
    name: "Right Back Leg",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Main right back denim leg panel shaped for seat, back rise, thigh, knee, inseam, outseam and hem.",
  },
  {
    id: "jeans-left-back-yoke",
    name: "Left Back Yoke",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Left back yoke controlling waist-to-seat shaping and supporting the characteristic jeans silhouette.",
  },
  {
    id: "jeans-right-back-yoke",
    name: "Right Back Yoke",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Right back yoke controlling waist-to-seat shaping and supporting the characteristic jeans silhouette.",
  },
  {
    id: "jeans-left-front-pocket-facing",
    name: "Left Front Pocket Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Left curved-pocket facing used to clean-finish and reinforce the front pocket opening.",
  },
  {
    id: "jeans-right-front-pocket-facing",
    name: "Right Front Pocket Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Right curved-pocket facing used to clean-finish and reinforce the front pocket opening.",
  },
  {
    id: "jeans-left-front-pocket-bag",
    name: "Left Front Pocket Bag",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Pair of pocket-bag sections forming the complete left front pocket.",
  },
  {
    id: "jeans-right-front-pocket-bag",
    name: "Right Front Pocket Bag",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Pair of pocket-bag sections forming the complete right front pocket.",
  },
  {
    id: "jeans-left-pocket-bearer",
    name: "Left Front Pocket Bearer",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Left denim pocket bearer restoring visible shell fabric behind the curved pocket opening.",
  },
  {
    id: "jeans-right-pocket-bearer",
    name: "Right Front Pocket Bearer",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Right denim pocket bearer restoring visible shell fabric behind the curved pocket opening.",
  },
  {
    id: "jeans-coin-pocket",
    name: "Coin Pocket",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Small denim coin or watch pocket positioned inside the right front pocket area.",
  },
  {
    id: "jeans-coin-pocket-facing",
    name: "Coin Pocket Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Optional facing used to clean-finish and reinforce the coin-pocket opening.",
  },
  {
    id: "jeans-left-back-pocket",
    name: "Left Back Patch Pocket",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Left shaped denim patch pocket positioned on the back seat area.",
  },
  {
    id: "jeans-right-back-pocket",
    name: "Right Back Patch Pocket",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Right shaped denim patch pocket positioned on the back seat area.",
  },
  {
    id: "jeans-left-back-pocket-facing",
    name: "Left Back Pocket Hem Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional separate facing reinforcing and finishing the upper edge of the left back pocket.",
  },
  {
    id: "jeans-right-back-pocket-facing",
    name: "Right Back Pocket Hem Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional separate facing reinforcing and finishing the upper edge of the right back pocket.",
  },
  {
    id: "jeans-left-back-pocket-reinforcement",
    name: "Left Back Pocket Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional internal patch reinforcing the left back pocket attachment area.",
  },
  {
    id: "jeans-right-back-pocket-reinforcement",
    name: "Right Back Pocket Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Optional internal patch reinforcing the right back pocket attachment area.",
  },
  {
    id: "jeans-left-waistband",
    name: "Left Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Left waistband section extending from centre back towards the centre-front fastening.",
  },
  {
    id: "jeans-right-waistband",
    name: "Right Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Right waistband section extending from centre back towards the centre-front fastening.",
  },
  {
    id: "jeans-left-inner-waistband",
    name: "Left Inner Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Left inner waistband section used to finish and stabilise the waist.",
  },
  {
    id: "jeans-right-inner-waistband",
    name: "Right Inner Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Right inner waistband section used to finish and stabilise the waist.",
  },
  {
    id: "jeans-waistband-interfacing",
    name: "Waistband Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional pair of reinforcement sections supporting the left and right waistbands.",
  },
  {
    id: "jeans-front-fly",
    name: "Front Fly",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Outer fly piece supporting the centre-front zip or button fastening.",
  },
  {
    id: "jeans-fly-shield",
    name: "Fly Shield",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Internal fly shield protecting the wearer and concealing the fastening components.",
  },
  {
    id: "jeans-fly-interfacing",
    name: "Fly Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional reinforcement supporting the fly shape and zip installation.",
  },
  {
    id: "jeans-button-fly-extension",
    name: "Button Fly Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional extended fly component used in traditional button-fly jeans.",
  },
  {
    id: "jeans-button-fly-shield",
    name: "Button Fly Shield",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Optional inner shield containing the buttonholes or buttons for a button-fly construction.",
  },
  {
    id: "jeans-belt-loop-strip",
    name: "Belt Loop Strip",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Continuous denim strip used to manufacture the full set of waistband belt loops.",
  },
  {
    id: "jeans-centre-back-belt-loop",
    name: "Centre Back Belt Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional separately cut reinforced centre-back belt loop used in premium or heavy-duty jeans.",
  },
  {
    id: "jeans-front-rivet-reinforcement-left",
    name: "Left Front Rivet Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Optional reinforcement patches placed behind left pocket-opening rivet positions.",
  },
  {
    id: "jeans-front-rivet-reinforcement-right",
    name: "Right Front Rivet Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional reinforcement patches placed behind right pocket and coin-pocket rivet positions.",
  },
  {
    id: "jeans-waist-button-reinforcement",
    name: "Waist Button Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional reinforcement patch positioned behind the waistband tack-button attachment.",
  },
  {
    id: "jeans-buttonhole-reinforcement",
    name: "Waist Buttonhole Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional reinforcement patch supporting the waistband buttonhole area.",
  },
  {
    id: "jeans-left-knee-reinforcement",
    name: "Left Knee Reinforcement Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Optional double-layer or shaped reinforcement panel protecting the left knee.",
  },
  {
    id: "jeans-right-knee-reinforcement",
    name: "Right Knee Reinforcement Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Optional double-layer or shaped reinforcement panel protecting the right knee.",
  },
  {
    id: "jeans-seat-reinforcement",
    name: "Seat Reinforcement Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 39,
    description:
      "Optional double-layer seat panel used in workwear, motorcycle or heavy-duty denim styles.",
  },
  {
    id: "jeans-crotch-gusset",
    name: "Crotch Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional diamond or shaped gusset improving mobility and reducing crotch-seam stress.",
  },
  {
    id: "jeans-left-front-thigh-panel",
    name: "Left Front Thigh Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional contrast, reinforced or fashion panel positioned on the left front thigh.",
  },
  {
    id: "jeans-right-front-thigh-panel",
    name: "Right Front Thigh Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional contrast, reinforced or fashion panel positioned on the right front thigh.",
  },
  {
    id: "jeans-left-back-calf-panel",
    name: "Left Back Calf Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional shaped or contrast panel positioned on the left back calf.",
  },
  {
    id: "jeans-right-back-calf-panel",
    name: "Right Back Calf Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional shaped or contrast panel positioned on the right back calf.",
  },
  {
    id: "jeans-left-moto-knee-panel",
    name: "Left Biker Knee Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional articulated or ribbed left knee panel used in biker and fashion denim.",
  },
  {
    id: "jeans-right-moto-knee-panel",
    name: "Right Biker Knee Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional articulated or ribbed right knee panel used in biker and fashion denim.",
  },
  {
    id: "jeans-left-hem-reinforcement",
    name: "Left Hem Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional internal reinforcement protecting the left leg opening from abrasion and repeated wear.",
  },
  {
    id: "jeans-right-hem-reinforcement",
    name: "Right Hem Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional internal reinforcement protecting the right leg opening from abrasion and repeated wear.",
  },
  {
    id: "jeans-left-side-seam-reinforcement",
    name: "Left Side-Seam Reinforcement Strip",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional reinforcement strip supporting the left outseam in heavy-duty or workwear jeans.",
  },
  {
    id: "jeans-right-side-seam-reinforcement",
    name: "Right Side-Seam Reinforcement Strip",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional reinforcement strip supporting the right outseam in heavy-duty or workwear jeans.",
  },
  {
    id: "jeans-leather-label-backing",
    name: "Waist Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional backing or mounting patch for a leather, synthetic or fabric waistband brand label.",
  },
  {
    id: "jeans-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Optional backing patches supporting embroidery, appliqué, distress repair, badge or heat-transfer decoration.",
  },
];

export default jeansPatternMaster;