export const knittedCapPatternMaster = [
  {
    id: "knitted-cap-front-crown",
    name: "Front Crown Panel",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Main front crown panel forming the front portion of the knitted cap from the lower edge to the crown.",
  },
  {
    id: "knitted-cap-back-crown",
    name: "Back Crown Panel",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Main back crown panel forming the rear portion of the knitted cap from the lower edge to the crown.",
  },
  {
    id: "knitted-cap-left-crown",
    name: "Left Crown Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Optional left crown panel used in multi-panel, shaped or colour-block knitted cap construction.",
  },
  {
    id: "knitted-cap-right-crown",
    name: "Right Crown Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional right crown panel used in multi-panel, shaped or colour-block knitted cap construction.",
  },
  {
    id: "knitted-cap-front-left-crown",
    name: "Front Left Crown Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional front-left section used in four-panel, six-panel or anatomically shaped cap construction.",
  },
  {
    id: "knitted-cap-front-right-crown",
    name: "Front Right Crown Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional front-right section used in four-panel, six-panel or anatomically shaped cap construction.",
  },
  {
    id: "knitted-cap-back-left-crown",
    name: "Back Left Crown Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Optional back-left section supporting shaped multi-panel crown construction.",
  },
  {
    id: "knitted-cap-back-right-crown",
    name: "Back Right Crown Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Optional back-right section supporting shaped multi-panel crown construction.",
  },
  {
    id: "knitted-cap-centre-top-panel",
    name: "Centre Top Crown Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional centre top panel closing the crown and creating a rounded or structured cap shape.",
  },
  {
    id: "knitted-cap-circular-crown",
    name: "Circular Crown Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Optional circular top panel used in flat-top, watch-cap or structured knitted cap construction.",
  },
  {
    id: "knitted-cap-one-piece-body",
    name: "One-Piece Cap Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Optional single rectangular or shaped knitted body panel joined at the centre back and crown.",
  },
  {
    id: "knitted-cap-tubular-body",
    name: "Tubular Cap Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Optional seamless tubular knitted body forming the principal cap shell.",
  },
  {
    id: "knitted-cap-left-side-insert",
    name: "Left Side Insert",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional left side insert used for shaping, contrast knitting, ventilation or branding.",
  },
  {
    id: "knitted-cap-right-side-insert",
    name: "Right Side Insert",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Optional right side insert used for shaping, contrast knitting, ventilation or branding.",
  },
  {
    id: "knitted-cap-front-centre-insert",
    name: "Front Centre Insert",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional front centre panel used for logo placement, decorative knitting or colour blocking.",
  },
  {
    id: "knitted-cap-back-centre-insert",
    name: "Back Centre Insert",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional back centre insert used for shaping, ventilation or contrast construction.",
  },
  {
    id: "knitted-cap-fold-up-cuff",
    name: "Fold-Up Cuff Band",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Main lower knitted band designed to fold upward around the cap for warmth, fit control and branding.",
  },
  {
    id: "knitted-cap-fixed-cuff-outer",
    name: "Outer Fixed Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional outer lower band used in a fixed double-layer cuff construction.",
  },
  {
    id: "knitted-cap-fixed-cuff-inner",
    name: "Inner Fixed Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional inner lower band completing a fixed double-layer cuff and providing additional warmth.",
  },
  {
    id: "knitted-cap-ribbed-lower-band",
    name: "Ribbed Lower Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Optional rib-knit lower band providing stretch, recovery and secure head fit.",
  },
  {
    id: "knitted-cap-elastic-channel",
    name: "Lower Elastic Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Optional casing positioned around the lower cap edge to contain elastic.",
  },
  {
    id: "knitted-cap-lower-band-facing",
    name: "Lower Band Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional inner facing finishing and stabilising the lower edge of the cap.",
  },
  {
    id: "knitted-cap-front-ear-band",
    name: "Front Ear-Warmer Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional front section of a shaped ear-warming band integrated into the lower cap edge.",
  },
  {
    id: "knitted-cap-back-ear-band",
    name: "Back Ear-Warmer Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional rear section of a shaped ear-warming band providing additional back-head coverage.",
  },
  {
    id: "knitted-cap-left-ear-flap",
    name: "Left Ear Flap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional shaped left flap extending downward to protect the ear from cold and wind.",
  },
  {
    id: "knitted-cap-right-ear-flap",
    name: "Right Ear Flap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional shaped right flap extending downward to protect the ear from cold and wind.",
  },
  {
    id: "knitted-cap-left-ear-flap-lining",
    name: "Left Ear Flap Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional lining panel providing warmth and clean internal finishing to the left ear flap.",
  },
  {
    id: "knitted-cap-right-ear-flap-lining",
    name: "Right Ear Flap Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional lining panel providing warmth and clean internal finishing to the right ear flap.",
  },
  {
    id: "knitted-cap-left-ear-flap-insulation",
    name: "Left Ear Flap Insulation",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional thermal insulation layer positioned inside the left ear flap.",
  },
  {
    id: "knitted-cap-right-ear-flap-insulation",
    name: "Right Ear Flap Insulation",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Optional thermal insulation layer positioned inside the right ear flap.",
  },
  {
    id: "knitted-cap-left-chin-tie",
    name: "Left Chin Tie",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Optional knitted or fabric tie extending from the left ear flap for under-chin fastening.",
  },
  {
    id: "knitted-cap-right-chin-tie",
    name: "Right Chin Tie",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional knitted or fabric tie extending from the right ear flap for under-chin fastening.",
  },
  {
    id: "knitted-cap-left-tie-reinforcement",
    name: "Left Chin-Tie Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Optional reinforcement patch supporting the left chin-tie attachment point.",
  },
  {
    id: "knitted-cap-right-tie-reinforcement",
    name: "Right Chin-Tie Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional reinforcement patch supporting the right chin-tie attachment point.",
  },
  {
    id: "knitted-cap-visor-upper",
    name: "Upper Visor",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional upper fabric panel forming the top surface of a knitted cap visor.",
  },
  {
    id: "knitted-cap-visor-under",
    name: "Under Visor",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional lower fabric panel completing the underside of a knitted cap visor.",
  },
  {
    id: "knitted-cap-visor-stiffener",
    name: "Visor Stiffener",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Optional structured insert maintaining the visor shape and projection.",
  },
  {
    id: "knitted-cap-visor-binding",
    name: "Visor Edge Binding",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Optional binding strip finishing and reinforcing the outer edge of the visor.",
  },
  {
    id: "knitted-cap-visor-attachment-facing",
    name: "Visor Attachment Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional internal facing reinforcing the seam where the visor joins the cap body.",
  },
  {
    id: "knitted-cap-brim-upper",
    name: "Upper Full Brim",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional upper circular brim panel extending around the complete cap.",
  },
  {
    id: "knitted-cap-brim-under",
    name: "Under Full Brim",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional lower circular brim panel completing the underside of a full-brim knitted cap.",
  },
  {
    id: "knitted-cap-brim-stiffener",
    name: "Full Brim Stiffener",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional structured insert supporting the shape of a full brim.",
  },
  {
    id: "knitted-cap-crown-lining-front",
    name: "Front Crown Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional lining panel covering the inside of the front crown and improving comfort.",
  },
  {
    id: "knitted-cap-crown-lining-back",
    name: "Back Crown Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional lining panel covering the inside of the back crown and improving comfort.",
  },
  {
    id: "knitted-cap-crown-lining-left",
    name: "Left Crown Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional left lining panel used in a multi-panel lined cap.",
  },
  {
    id: "knitted-cap-crown-lining-right",
    name: "Right Crown Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional right lining panel used in a multi-panel lined cap.",
  },
  {
    id: "knitted-cap-one-piece-lining",
    name: "One-Piece Cap Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional single lining body used inside a one-piece or tubular knitted cap.",
  },
  {
    id: "knitted-cap-fleece-lining",
    name: "Fleece Cap Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional fleece lining layer providing additional warmth and softness.",
  },
  {
    id: "knitted-cap-thermal-lining",
    name: "Thermal Cap Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional thermal knit or insulated lining used in cold-weather cap construction.",
  },
  {
    id: "knitted-cap-windproof-front-membrane",
    name: "Front Windproof Membrane",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional front membrane insert reducing wind penetration across the forehead.",
  },
  {
    id: "knitted-cap-windproof-side-membranes",
    name: "Side Windproof Membranes",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional left and right membrane inserts reducing wind penetration around the ears.",
  },
  {
    id: "knitted-cap-insulation-front",
    name: "Front Crown Insulation",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Optional thermal insulation layer positioned within the front crown.",
  },
  {
    id: "knitted-cap-insulation-back",
    name: "Back Crown Insulation",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Optional thermal insulation layer positioned within the back crown.",
  },
  {
    id: "knitted-cap-pom-pom-base",
    name: "Pom-Pom Base",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Optional fabric or knitted base used to manufacture or attach a pom-pom at the crown.",
  },
  {
    id: "knitted-cap-pom-pom-reinforcement",
    name: "Pom-Pom Attachment Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Optional internal reinforcement supporting the pom-pom attachment point at the crown.",
  },
  {
    id: "knitted-cap-top-knot-left",
    name: "Left Top-Knot Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Optional left crown extension forming part of a tied top-knot cap.",
  },
  {
    id: "knitted-cap-top-knot-right",
    name: "Right Top-Knot Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Optional right crown extension forming the opposite part of a tied top-knot cap.",
  },
  {
    id: "knitted-cap-ponytail-opening-facing",
    name: "Ponytail Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 58,
    description:
      "Optional shaped facing clean-finishing and stabilising a ponytail opening at the back crown.",
  },
  {
    id: "knitted-cap-ponytail-opening-reinforcement",
    name: "Ponytail Opening Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 59,
    description:
      "Optional reinforcement supporting the edge of a ponytail opening.",
  },
  {
    id: "knitted-cap-back-adjustment-tab",
    name: "Back Adjustment Tab",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 60,
    description:
      "Optional upper and under tab pieces used for adjustable back-cap fastening.",
  },
  {
    id: "knitted-cap-back-opening-facing",
    name: "Back Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 61,
    description:
      "Optional facing finishing and stabilising an adjustable back opening.",
  },
  {
    id: "knitted-cap-left-ventilation-panel",
    name: "Left Ventilation Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 62,
    description:
      "Optional breathable mesh or open-knit panel positioned on the left side of the cap.",
  },
  {
    id: "knitted-cap-right-ventilation-panel",
    name: "Right Ventilation Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional breathable mesh or open-knit panel positioned on the right side of the cap.",
  },
  {
    id: "knitted-cap-front-sweatband",
    name: "Front Sweatband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 64,
    description:
      "Optional absorbent front band positioned against the forehead for moisture management.",
  },
  {
    id: "knitted-cap-back-sweatband",
    name: "Back Sweatband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 65,
    description:
      "Optional absorbent rear band completing the internal sweatband construction.",
  },
  {
    id: "knitted-cap-continuous-sweatband",
    name: "Continuous Sweatband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 66,
    description:
      "Optional single continuous inner band providing moisture absorption and fit stability.",
  },
  {
    id: "knitted-cap-reflective-front-panel",
    name: "Reflective Front Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 67,
    description:
      "Optional reflective or high-visibility front insert improving wearer visibility.",
  },
  {
    id: "knitted-cap-reflective-side-panels",
    name: "Reflective Side Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 68,
    description:
      "Optional left and right reflective inserts improving side visibility.",
  },
  {
    id: "knitted-cap-headlamp-opening-facing",
    name: "Headlamp Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 69,
    description:
      "Optional facing finishing an opening or mounting point for an integrated headlamp.",
  },
  {
    id: "knitted-cap-headlamp-backing",
    name: "Headlamp Mount Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 70,
    description:
      "Optional reinforced backing patch supporting an integrated light or removable headlamp mount.",
  },
  {
    id: "knitted-cap-logo-front-backing",
    name: "Front Logo Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 71,
    description:
      "Optional internal support patch positioned behind front embroidery, appliqué or branding.",
  },
  {
    id: "knitted-cap-cuff-logo-backing",
    name: "Cuff Logo Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 72,
    description:
      "Optional reinforcement positioned behind embroidery, badges or labels applied to the fold-up cuff.",
  },
  {
    id: "knitted-cap-side-decoration-backing",
    name: "Side Decoration Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 73,
    description:
      "Optional backing patches supporting decoration or branding on the left and right cap sides.",
  },
  {
    id: "knitted-cap-label-backing",
    name: "Brand Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 74,
    description:
      "Optional backing piece supporting a woven, printed, leather or heat-transfer brand label.",
  },
  {
    id: "knitted-cap-care-label-backing",
    name: "Care Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 75,
    description:
      "Optional internal backing piece supporting care, fibre-content and size labels.",
  },
  {
    id: "knitted-cap-crown-seam-cover",
    name: "Crown Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 76,
    description:
      "Optional internal tape or knitted strip covering and protecting crown seams.",
  },
  {
    id: "knitted-cap-back-seam-cover",
    name: "Back Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 77,
    description:
      "Optional internal strip covering the centre-back seam for comfort and clean finishing.",
  },
  {
    id: "knitted-cap-cuff-seam-cover",
    name: "Cuff Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 78,
    description:
      "Optional internal strip covering the cuff joining seam and reducing wearer irritation.",
  },
  {
    id: "knitted-cap-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 79,
    description:
      "Optional backing patches supporting embroidery, appliqué, badges, logos or decorative attachments.",
  },
];

export default knittedCapPatternMaster;