export const knittedScarfPatternMaster = [
  {
    id: "knitted-scarf-main-body",
    name: "Main Scarf Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Primary rectangular, shaped or fully fashioned knitted panel forming the complete scarf body.",
  },
  {
    id: "knitted-scarf-left-body",
    name: "Left Scarf Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Optional left body section used when the scarf is manufactured from two joined knitted panels.",
  },
  {
    id: "knitted-scarf-right-body",
    name: "Right Scarf Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Optional right body section completing a scarf manufactured from two joined knitted panels.",
  },
  {
    id: "knitted-scarf-centre-body",
    name: "Centre Scarf Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional centre body section used in multi-panel, colour-blocked or engineered scarf construction.",
  },
  {
    id: "knitted-scarf-left-end-panel",
    name: "Left End Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional separate panel forming the left decorative, reinforced or contrast end of the scarf.",
  },
  {
    id: "knitted-scarf-right-end-panel",
    name: "Right End Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional separate panel forming the right decorative, reinforced or contrast end of the scarf.",
  },
  {
    id: "knitted-scarf-left-end-facing",
    name: "Left End Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Optional facing used to clean-finish, stabilise and reinforce the left scarf end.",
  },
  {
    id: "knitted-scarf-right-end-facing",
    name: "Right End Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Optional facing used to clean-finish, stabilise and reinforce the right scarf end.",
  },
  {
    id: "knitted-scarf-left-side-panel",
    name: "Left Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional longitudinal left side panel used for contrast knitting, shaping or decorative construction.",
  },
  {
    id: "knitted-scarf-right-side-panel",
    name: "Right Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Optional longitudinal right side panel used for contrast knitting, shaping or decorative construction.",
  },
  {
    id: "knitted-scarf-centre-insert",
    name: "Centre Decorative Insert",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Optional central longitudinal panel used for cable knitting, jacquard motifs, branding or colour blocking.",
  },
  {
    id: "knitted-scarf-left-border",
    name: "Left Side Border",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Optional knitted, ribbed or self-fabric strip finishing and stabilising the left long edge.",
  },
  {
    id: "knitted-scarf-right-border",
    name: "Right Side Border",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional knitted, ribbed or self-fabric strip finishing and stabilising the right long edge.",
  },
  {
    id: "knitted-scarf-left-end-border",
    name: "Left End Border",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Optional ribbed, rolled or decorative border finishing the left scarf end.",
  },
  {
    id: "knitted-scarf-right-end-border",
    name: "Right End Border",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional ribbed, rolled or decorative border finishing the right scarf end.",
  },
  {
    id: "knitted-scarf-continuous-border",
    name: "Continuous Edge Border",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional continuous knitted or fabric binding finishing all outer scarf edges.",
  },
  {
    id: "knitted-scarf-left-fringe-header",
    name: "Left Fringe Header",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional knitted or woven strip supporting fringe attachment at the left scarf end.",
  },
  {
    id: "knitted-scarf-right-fringe-header",
    name: "Right Fringe Header",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional knitted or woven strip supporting fringe attachment at the right scarf end.",
  },
  {
    id: "knitted-scarf-left-fringe-reinforcement",
    name: "Left Fringe Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional internal reinforcement preventing distortion around the left fringe attachment area.",
  },
  {
    id: "knitted-scarf-right-fringe-reinforcement",
    name: "Right Fringe Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Optional internal reinforcement preventing distortion around the right fringe attachment area.",
  },
  {
    id: "knitted-scarf-left-tassel-base",
    name: "Left Tassel Base",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Optional knitted or fabric base supporting decorative tassels at the left scarf end.",
  },
  {
    id: "knitted-scarf-right-tassel-base",
    name: "Right Tassel Base",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional knitted or fabric base supporting decorative tassels at the right scarf end.",
  },
  {
    id: "knitted-scarf-left-pocket",
    name: "Left End Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional patch pocket positioned near the left scarf end for warming hands or carrying small items.",
  },
  {
    id: "knitted-scarf-right-pocket",
    name: "Right End Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional patch pocket positioned near the right scarf end for warming hands or carrying small items.",
  },
  {
    id: "knitted-scarf-left-pocket-facing",
    name: "Left Pocket Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional facing stabilising and clean-finishing the opening of the left scarf pocket.",
  },
  {
    id: "knitted-scarf-right-pocket-facing",
    name: "Right Pocket Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional facing stabilising and clean-finishing the opening of the right scarf pocket.",
  },
  {
    id: "knitted-scarf-left-pocket-lining",
    name: "Left Pocket Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional lining panel improving comfort and internal finishing inside the left scarf pocket.",
  },
  {
    id: "knitted-scarf-right-pocket-lining",
    name: "Right Pocket Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional lining panel improving comfort and internal finishing inside the right scarf pocket.",
  },
  {
    id: "knitted-scarf-left-hand-warmer-extension",
    name: "Left Hand-Warmer Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional shaped extension providing additional hand coverage at the left scarf end.",
  },
  {
    id: "knitted-scarf-right-hand-warmer-extension",
    name: "Right Hand-Warmer Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Optional shaped extension providing additional hand coverage at the right scarf end.",
  },
  {
    id: "knitted-scarf-loop-closure",
    name: "Scarf Pull-Through Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Optional loop used to pass one scarf end through the other for secure neck positioning.",
  },
  {
    id: "knitted-scarf-loop-closure-facing",
    name: "Pull-Through Loop Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional facing reinforcing and clean-finishing the pull-through loop.",
  },
  {
    id: "knitted-scarf-loop-attachment-reinforcement",
    name: "Loop Attachment Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Optional backing patch supporting the attachment point of the scarf closure loop.",
  },
  {
    id: "knitted-scarf-button-tab",
    name: "Button Closure Tab",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional upper and under tab pieces used to secure the scarf with a button closure.",
  },
  {
    id: "knitted-scarf-button-tab-interfacing",
    name: "Button Tab Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional reinforcement stabilising the scarf button tab and buttonhole position.",
  },
  {
    id: "knitted-scarf-button-backing",
    name: "Button Attachment Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional support patch positioned behind the scarf button attachment point.",
  },
  {
    id: "knitted-scarf-snap-tab",
    name: "Snap Closure Tab",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Optional upper and under tab pieces used for snap-fastened scarf closure.",
  },
  {
    id: "knitted-scarf-snap-reinforcement",
    name: "Snap Closure Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Optional reinforcement patches supporting male and female snap components.",
  },
  {
    id: "knitted-scarf-hook-loop-tab",
    name: "Hook-and-Loop Closure Tab",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional upper and under tab pieces supporting a hook-and-loop scarf closure.",
  },
  {
    id: "knitted-scarf-magnetic-closure-backing",
    name: "Magnetic Closure Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional reinforcement patches supporting concealed magnetic closure components.",
  },
  {
    id: "knitted-scarf-infinity-body",
    name: "Infinity Scarf Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional continuous loop body used for a circular or infinity scarf.",
  },
  {
    id: "knitted-scarf-infinity-seam-cover",
    name: "Infinity Join Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional internal strip covering and protecting the join seam of an infinity scarf.",
  },
  {
    id: "knitted-scarf-mobius-body",
    name: "Möbius Scarf Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional twisted continuous panel forming a Möbius-style loop scarf.",
  },
  {
    id: "knitted-scarf-snood-body",
    name: "Snood Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional deep tubular body forming a neck warmer, snood or convertible hood scarf.",
  },
  {
    id: "knitted-scarf-snood-upper-channel",
    name: "Snood Upper Drawcord Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional casing around the upper snood edge containing a drawcord for adjustment.",
  },
  {
    id: "knitted-scarf-snood-lower-channel",
    name: "Snood Lower Drawcord Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional casing around the lower snood edge containing a drawcord or elastic.",
  },
  {
    id: "knitted-scarf-snood-eyelet-reinforcement",
    name: "Snood Eyelet Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional reinforcement patches supporting drawcord eyelets or cord exits.",
  },
  {
    id: "knitted-scarf-balaclava-neck-panel",
    name: "Balaclava Neck Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional extended knitted panel allowing the scarf to convert into a neck and lower-face covering.",
  },
  {
    id: "knitted-scarf-face-cover-panel",
    name: "Face Cover Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional shaped panel covering the lower face in convertible technical scarf styles.",
  },
  {
    id: "knitted-scarf-face-opening-facing",
    name: "Face Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional facing stabilising and clean-finishing the opening of a convertible face-cover section.",
  },
  {
    id: "knitted-scarf-hood-centre-panel",
    name: "Hood Centre Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional centre hood panel used in a hooded scarf or scarf-hood combination.",
  },
  {
    id: "knitted-scarf-left-hood-side",
    name: "Left Hood Side",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Optional left side panel forming part of an integrated scarf hood.",
  },
  {
    id: "knitted-scarf-right-hood-side",
    name: "Right Hood Side",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Optional right side panel forming part of an integrated scarf hood.",
  },
  {
    id: "knitted-scarf-hood-opening-band",
    name: "Hood Opening Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Optional knitted or ribbed band finishing and controlling the hood face opening.",
  },
  {
    id: "knitted-scarf-main-lining",
    name: "Main Scarf Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Optional full-length lining panel providing warmth, comfort and clean internal finishing.",
  },
  {
    id: "knitted-scarf-left-lining",
    name: "Left Scarf Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Optional left lining section used in a two-piece or panelled lined scarf.",
  },
  {
    id: "knitted-scarf-right-lining",
    name: "Right Scarf Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Optional right lining section completing a two-piece or panelled lined scarf.",
  },
  {
    id: "knitted-scarf-fleece-lining",
    name: "Fleece Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 58,
    description:
      "Optional fleece lining layer providing additional softness and cold-weather insulation.",
  },
  {
    id: "knitted-scarf-thermal-lining",
    name: "Thermal Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 59,
    description:
      "Optional thermal knit or brushed-fabric lining used in winter and technical scarf construction.",
  },
  {
    id: "knitted-scarf-sherpa-lining",
    name: "Sherpa Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 60,
    description:
      "Optional sherpa, pile or faux-shearling lining providing high warmth and loft.",
  },
  {
    id: "knitted-scarf-windproof-membrane",
    name: "Windproof Membrane",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 61,
    description:
      "Optional membrane layer reducing wind penetration through a technical knitted scarf.",
  },
  {
    id: "knitted-scarf-front-neck-insulation",
    name: "Front Neck Insulation",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 62,
    description:
      "Optional insulation insert concentrated around the front neck area for additional warmth.",
  },
  {
    id: "knitted-scarf-back-neck-insulation",
    name: "Back Neck Insulation",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional insulation insert concentrated around the back neck area for additional warmth.",
  },
  {
    id: "knitted-scarf-reflective-left-end-panel",
    name: "Left Reflective End Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 64,
    description:
      "Optional reflective or high-visibility panel positioned near the left scarf end.",
  },
  {
    id: "knitted-scarf-reflective-right-end-panel",
    name: "Right Reflective End Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 65,
    description:
      "Optional reflective or high-visibility panel positioned near the right scarf end.",
  },
  {
    id: "knitted-scarf-reflective-centre-panel",
    name: "Reflective Centre Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 66,
    description:
      "Optional reflective centre insert improving visibility during outdoor or low-light use.",
  },
  {
    id: "knitted-scarf-left-logo-backing",
    name: "Left Logo Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 67,
    description:
      "Optional internal support patch positioned behind branding or embroidery near the left scarf end.",
  },
  {
    id: "knitted-scarf-right-logo-backing",
    name: "Right Logo Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 68,
    description:
      "Optional internal support patch positioned behind branding or embroidery near the right scarf end.",
  },
  {
    id: "knitted-scarf-centre-logo-backing",
    name: "Centre Logo Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 69,
    description:
      "Optional support patch positioned behind a central logo, badge, appliqué or decorative motif.",
  },
  {
    id: "knitted-scarf-applique-backing",
    name: "Appliqué Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 70,
    description:
      "Optional backing patches supporting appliqué, embroidery or decorative knitted motifs.",
  },
  {
    id: "knitted-scarf-label-backing",
    name: "Brand Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 71,
    description:
      "Optional backing piece supporting a woven, printed, leather or heat-transfer brand label.",
  },
  {
    id: "knitted-scarf-care-label-backing",
    name: "Care Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 72,
    description:
      "Optional internal support piece for care, size and fibre-content labels.",
  },
  {
    id: "knitted-scarf-side-seam-cover-left",
    name: "Left Side Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 73,
    description:
      "Optional internal strip covering and protecting the left longitudinal joining seam.",
  },
  {
    id: "knitted-scarf-side-seam-cover-right",
    name: "Right Side Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 74,
    description:
      "Optional internal strip covering and protecting the right longitudinal joining seam.",
  },
  {
    id: "knitted-scarf-centre-seam-cover",
    name: "Centre Join Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 75,
    description:
      "Optional internal tape or knitted strip covering a centre joining seam.",
  },
  {
    id: "knitted-scarf-end-seam-cover-left",
    name: "Left End Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 76,
    description:
      "Optional internal strip covering the seam between the main body and left end panel.",
  },
  {
    id: "knitted-scarf-end-seam-cover-right",
    name: "Right End Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 77,
    description:
      "Optional internal strip covering the seam between the main body and right end panel.",
  },
  {
    id: "knitted-scarf-hanger-loop",
    name: "Hanger Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 78,
    description:
      "Optional reinforced loop used to hang the scarf without stretching or distorting the body.",
  },
  {
    id: "knitted-scarf-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 79,
    description:
      "Optional backing patches supporting embroidery, badges, logos, appliqué or decorative attachments.",
  },
];

export default knittedScarfPatternMaster;