export const legWarmersPatternMaster = [
  {
    id: "leg-warmers-main-body",
    name: "Main Leg Warmer Body",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Primary knitted or stretch-fabric tubular section forming the main body of both leg warmers.",
  },
  {
    id: "leg-warmers-left-body",
    name: "Left Leg Warmer Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Optional anatomically shaped left leg warmer body used for directional, compression or technical construction.",
  },
  {
    id: "leg-warmers-right-body",
    name: "Right Leg Warmer Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Optional anatomically shaped right leg warmer body used for directional, compression or technical construction.",
  },
  {
    id: "leg-warmers-front-panel",
    name: "Front Leg Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional front panel used for decorative knitting, shin protection, compression zoning or colour blocking.",
  },
  {
    id: "leg-warmers-back-panel",
    name: "Back Leg Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional rear panel used for calf shaping, ventilation, reinforcement or ergonomic fit.",
  },
  {
    id: "leg-warmers-inner-leg-panel",
    name: "Inner Leg Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional inner-leg panel used for seam control, stretch management or anti-chafing construction.",
  },
  {
    id: "leg-warmers-outer-leg-panel",
    name: "Outer Leg Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Optional outer-leg panel used for branding, contrast design, ventilation or support.",
  },
  {
    id: "leg-warmers-left-front-panel",
    name: "Left Front Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Optional anatomically shaped left front panel used in technical or directional leg warmers.",
  },
  {
    id: "leg-warmers-right-front-panel",
    name: "Right Front Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional anatomically shaped right front panel used in technical or directional leg warmers.",
  },
  {
    id: "leg-warmers-left-back-panel",
    name: "Left Back Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Optional anatomically shaped left rear panel supporting calf contour and mobility.",
  },
  {
    id: "leg-warmers-right-back-panel",
    name: "Right Back Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Optional anatomically shaped right rear panel supporting calf contour and mobility.",
  },
  {
    id: "leg-warmers-upper-cuff",
    name: "Upper Cuff Band",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Primary upper knitted or elasticated band securing each leg warmer around the upper calf or below the knee.",
  },
  {
    id: "leg-warmers-upper-cuff-outer",
    name: "Outer Upper Cuff",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional outer section forming a fixed or folded double-layer upper cuff.",
  },
  {
    id: "leg-warmers-upper-cuff-inner",
    name: "Inner Upper Cuff",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Optional inner section completing a double-layer upper cuff and covering elastic.",
  },
  {
    id: "leg-warmers-wide-upper-band",
    name: "Wide Upper Support Band",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional deep upper band distributing pressure over a wider area for improved comfort.",
  },
  {
    id: "leg-warmers-soft-upper-band",
    name: "Soft Upper Band",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional low-pressure upper band used for sensitive skin, comfort or non-binding construction.",
  },
  {
    id: "leg-warmers-compression-upper-band",
    name: "Compression Upper Band",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional engineered upper band providing secure positioning in compression or performance leg warmers.",
  },
  {
    id: "leg-warmers-upper-elastic-casing",
    name: "Upper Elastic Casing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional casing containing inserted elastic around the upper opening.",
  },
  {
    id: "leg-warmers-upper-grip-band",
    name: "Upper Internal Grip Band",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional inner band supporting silicone grip or anti-slip application.",
  },
  {
    id: "leg-warmers-upper-cuff-lining",
    name: "Upper Cuff Lining",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Optional soft lining layer improving comfort inside the upper cuff.",
  },
  {
    id: "leg-warmers-lower-cuff",
    name: "Lower Cuff Band",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Primary lower knitted or elasticated band securing each leg warmer around the ankle.",
  },
  {
    id: "leg-warmers-lower-cuff-outer",
    name: "Outer Lower Cuff",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional outer section forming a fixed or folded double-layer lower cuff.",
  },
  {
    id: "leg-warmers-lower-cuff-inner",
    name: "Inner Lower Cuff",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional inner section completing and supporting a double-layer lower cuff.",
  },
  {
    id: "leg-warmers-lower-elastic-casing",
    name: "Lower Elastic Casing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional casing containing elastic around the lower leg-warmer opening.",
  },
  {
    id: "leg-warmers-lower-grip-band",
    name: "Lower Internal Grip Band",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional inner lower band supporting silicone grip and reducing upward movement.",
  },
  {
    id: "leg-warmers-ankle-extension",
    name: "Ankle Extension",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional shaped extension increasing coverage around the ankle and upper foot.",
  },
  {
    id: "leg-warmers-heel-opening-facing",
    name: "Heel Opening Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional shaped facing finishing and stabilising a heel opening.",
  },
  {
    id: "leg-warmers-heel-opening-reinforcement",
    name: "Heel Opening Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional reinforcement protecting the edge of a heel opening from stretch and wear.",
  },
  {
    id: "leg-warmers-stirrup",
    name: "Underfoot Stirrup",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional strap passing beneath the foot to hold each leg warmer securely in position.",
  },
  {
    id: "leg-warmers-left-stirrup",
    name: "Left Underfoot Stirrup",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Optional anatomically positioned strap passing beneath the left foot.",
  },
  {
    id: "leg-warmers-right-stirrup",
    name: "Right Underfoot Stirrup",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Optional anatomically positioned strap passing beneath the right foot.",
  },
  {
    id: "leg-warmers-stirrup-reinforcement",
    name: "Stirrup Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional abrasion-resistant layer protecting the underfoot stirrup area.",
  },
  {
    id: "leg-warmers-upper-foot-panel",
    name: "Upper Foot Extension Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Optional panel extending over the instep for dance, yoga, thermal or fashion leg warmers.",
  },
  {
    id: "leg-warmers-foot-opening-facing",
    name: "Foot Opening Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional facing clean-finishing the forward opening of an extended foot section.",
  },
  {
    id: "leg-warmers-knee-panel",
    name: "Knee Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional shaped or articulated panel improving knee movement, protection or support.",
  },
  {
    id: "leg-warmers-left-knee-panel",
    name: "Left Knee Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional anatomically shaped left knee panel used in directional or technical construction.",
  },
  {
    id: "leg-warmers-right-knee-panel",
    name: "Right Knee Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Optional anatomically shaped right knee panel used in directional or technical construction.",
  },
  {
    id: "leg-warmers-knee-flex-zone",
    name: "Knee Flex Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Optional engineered stretch section positioned around or behind each knee.",
  },
  {
    id: "leg-warmers-knee-reinforcement",
    name: "Knee Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional abrasion-resistant or padded layer protecting the knee area.",
  },
  {
    id: "leg-warmers-shin-panel",
    name: "Shin Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional front lower-leg panel providing protection, support, decoration or thermal insulation.",
  },
  {
    id: "leg-warmers-shin-cushion",
    name: "Shin Cushion Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional padded panel protecting the shin during sport, dance, hiking or boot use.",
  },
  {
    id: "leg-warmers-shin-reinforcement",
    name: "Shin Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional durable layer increasing abrasion resistance over the front lower leg.",
  },
  {
    id: "leg-warmers-calf-panel",
    name: "Calf Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional shaped rear panel accommodating calf contour and controlled stretch.",
  },
  {
    id: "leg-warmers-calf-compression-zone",
    name: "Calf Compression Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional engineered section providing controlled support around the calf.",
  },
  {
    id: "leg-warmers-ankle-compression-zone",
    name: "Ankle Compression Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional higher-control compression section positioned around the ankle.",
  },
  {
    id: "leg-warmers-graduated-compression-lower-zone",
    name: "Graduated Compression Lower Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional lower section engineered to provide the greatest compression near the ankle.",
  },
  {
    id: "leg-warmers-graduated-compression-middle-zone",
    name: "Graduated Compression Middle Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional middle section providing controlled intermediate compression.",
  },
  {
    id: "leg-warmers-graduated-compression-upper-zone",
    name: "Graduated Compression Upper Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional upper section providing reduced compression toward the upper opening.",
  },
  {
    id: "leg-warmers-front-ventilation-panel",
    name: "Front Ventilation Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional open-knit or mesh section improving airflow over the front lower leg.",
  },
  {
    id: "leg-warmers-back-ventilation-panel",
    name: "Back Ventilation Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional breathable section positioned behind the calf or knee.",
  },
  {
    id: "leg-warmers-side-ventilation-panels",
    name: "Side Ventilation Panels",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional inner and outer breathable panels improving airflow along both sides of each leg warmer.",
  },
  {
    id: "leg-warmers-main-lining",
    name: "Main Leg Warmer Lining",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Optional full-length inner layer providing comfort, warmth and clean internal finishing.",
  },
  {
    id: "leg-warmers-fleece-lining",
    name: "Fleece Lining",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Optional fleece inner layer providing softness and cold-weather insulation.",
  },
  {
    id: "leg-warmers-thermal-lining",
    name: "Thermal Lining",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Optional insulating knit or brushed-fabric lining used in winter and outdoor leg warmers.",
  },
  {
    id: "leg-warmers-sherpa-lining",
    name: "Sherpa Lining",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Optional high-loft sherpa or pile lining providing increased warmth.",
  },
  {
    id: "leg-warmers-windproof-front-membrane",
    name: "Windproof Front Membrane",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Optional membrane layer reducing wind penetration through the front of each leg warmer.",
  },
  {
    id: "leg-warmers-windproof-side-membranes",
    name: "Windproof Side Membranes",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Optional membrane inserts reducing wind exposure along the inner and outer leg areas.",
  },
  {
    id: "leg-warmers-waterproof-shell",
    name: "Waterproof Outer Shell",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 58,
    description:
      "Optional waterproof outer layer used in cycling, hiking, skiing or technical outdoor leg warmers.",
  },
  {
    id: "leg-warmers-waterproof-membrane",
    name: "Waterproof Membrane",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 59,
    description:
      "Optional waterproof and breathable internal membrane layer.",
  },
  {
    id: "leg-warmers-seam-seal-cover",
    name: "Membrane Seam Cover",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 60,
    description:
      "Optional internal strip covering and protecting waterproof membrane seams.",
  },
  {
    id: "leg-warmers-reflective-front-panel",
    name: "Reflective Front Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 61,
    description:
      "Optional reflective or high-visibility panel positioned on the front of each leg warmer.",
  },
  {
    id: "leg-warmers-reflective-side-panels",
    name: "Reflective Side Panels",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 62,
    description:
      "Optional reflective inserts positioned along the inner or outer sides for improved visibility.",
  },
  {
    id: "leg-warmers-zip-opening-left",
    name: "Left Leg Zip Opening Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional pair of facing pieces stabilising a zip opening in the left leg warmer.",
  },
  {
    id: "leg-warmers-zip-opening-right",
    name: "Right Leg Zip Opening Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 64,
    description:
      "Optional pair of facing pieces stabilising a zip opening in the right leg warmer.",
  },
  {
    id: "leg-warmers-inner-zip-guards",
    name: "Inner Zip Guards",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 65,
    description:
      "Optional internal guards positioned behind leg-warmer zips to improve comfort and prevent snagging.",
  },
  {
    id: "leg-warmers-zip-end-reinforcements",
    name: "Zip-End Reinforcements",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 66,
    description:
      "Optional reinforcement patches supporting the upper and lower ends of both zip openings.",
  },
  {
    id: "leg-warmers-button-opening-placket",
    name: "Button Opening Placket",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 67,
    description:
      "Optional paired placket sections forming buttoned side openings on both leg warmers.",
  },
  {
    id: "leg-warmers-button-placket-interfacing",
    name: "Button Placket Interfacing",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 68,
    description:
      "Optional reinforcement stabilising button and buttonhole plackets.",
  },
  {
    id: "leg-warmers-snap-opening-placket",
    name: "Snap Opening Placket",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 69,
    description:
      "Optional paired placket sections supporting snap-fastened leg-warmer openings.",
  },
  {
    id: "leg-warmers-snap-reinforcement",
    name: "Snap Reinforcement Patches",
    required: false,
    cutQuantity: 8,
    cutOnFold: false,
    custom: false,
    sequence: 70,
    description:
      "Optional reinforcement patches supporting snap components on both leg warmers.",
  },
  {
    id: "leg-warmers-drawcord-upper-channel",
    name: "Upper Drawcord Channel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 71,
    description:
      "Optional upper casing containing a drawcord for fit adjustment.",
  },
  {
    id: "leg-warmers-drawcord-eyelet-reinforcement",
    name: "Drawcord Eyelet Reinforcement",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 72,
    description:
      "Optional reinforcement patches supporting drawcord eyelets or cord exits.",
  },
  {
    id: "leg-warmers-logo-backing",
    name: "Logo Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 73,
    description:
      "Optional internal support patches positioned behind logos, embroidery or heat-transfer branding.",
  },
  {
    id: "leg-warmers-reflective-transfer-backing",
    name: "Reflective Transfer Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 74,
    description:
      "Optional stabilising layer supporting reflective transfer application.",
  },
  {
    id: "leg-warmers-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 75,
    description:
      "Optional backing patches supporting embroidery, appliqué, badges or decorative attachments.",
  },
  {
    id: "leg-warmers-label-backing",
    name: "Brand Label Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 76,
    description:
      "Optional backing pieces supporting woven, printed, leather or heat-transfer labels.",
  },
  {
    id: "leg-warmers-care-label-backing",
    name: "Care Label Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 77,
    description:
      "Optional internal support pieces for care, fibre-content and size labels.",
  },
  {
    id: "leg-warmers-main-seam-cover",
    name: "Main Seam Cover",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 78,
    description:
      "Optional internal strips covering longitudinal body seams for comfort and clean finishing.",
  },
  {
    id: "leg-warmers-cuff-seam-covers",
    name: "Cuff Seam Covers",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 79,
    description:
      "Optional internal strips covering upper and lower cuff joining seams.",
  },
  {
    id: "leg-warmers-hanger-loops",
    name: "Hanger Loops",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 80,
    description:
      "Optional reinforced loops used to hang or pair the leg warmers during storage or display.",
  },
];

export default legWarmersPatternMaster;