export const parkaPatternMaster = [
  {
    id: "parka-left-front",
    name: "Left Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Main left front parka shell panel including shoulder, armhole, side seam, centre-front opening and extended lower-body shaping.",
  },
  {
    id: "parka-right-front",
    name: "Right Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Main right front parka shell panel including shoulder, armhole, side seam, centre-front opening and extended lower-body shaping.",
  },
  {
    id: "parka-back",
    name: "Back",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 3,
    description:
      "Main back parka shell panel cut on the centre-back fold with shoulder, armhole, side seam and long hem shaping.",
  },
  {
    id: "parka-left-front-side-panel",
    name: "Left Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional shaped left front side panel used for fit control, colour blocking or functional seam placement.",
  },
  {
    id: "parka-right-front-side-panel",
    name: "Right Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional shaped right front side panel used for fit control, colour blocking or functional seam placement.",
  },
  {
    id: "parka-left-back-side-panel",
    name: "Left Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional shaped left back side panel improving body contour, mobility and seam positioning.",
  },
  {
    id: "parka-right-back-side-panel",
    name: "Right Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Optional shaped right back side panel improving body contour, mobility and seam positioning.",
  },
  {
    id: "parka-left-front-yoke",
    name: "Left Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Optional upper left front yoke providing reinforcement, weather protection or contrast styling.",
  },
  {
    id: "parka-right-front-yoke",
    name: "Right Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional upper right front yoke providing reinforcement, weather protection or contrast styling.",
  },
  {
    id: "parka-back-yoke",
    name: "Back Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 10,
    description:
      "Optional upper back yoke supporting shoulder strength, ventilation or storm-cape construction.",
  },
  {
    id: "parka-back-storm-cape",
    name: "Back Storm Cape",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 11,
    description:
      "Optional floating back cape shielding the upper back and protecting a ventilation opening.",
  },
  {
    id: "parka-back-vent-mesh",
    name: "Back Vent Mesh",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 12,
    description:
      "Optional breathable mesh panel positioned beneath the back storm cape.",
  },
  {
    id: "parka-left-upper-sleeve",
    name: "Left Upper Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Main left upper sleeve panel shaped for shoulder fit, cold-weather layering and arm movement.",
  },
  {
    id: "parka-right-upper-sleeve",
    name: "Right Upper Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Main right upper sleeve panel shaped for shoulder fit, cold-weather layering and arm movement.",
  },
  {
    id: "parka-left-under-sleeve",
    name: "Left Under Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Left under-sleeve section completing the two-piece sleeve and supporting ergonomic movement.",
  },
  {
    id: "parka-right-under-sleeve",
    name: "Right Under Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Right under-sleeve section completing the two-piece sleeve and supporting ergonomic movement.",
  },
  {
    id: "parka-left-articulated-elbow-panel",
    name: "Left Articulated Elbow Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional shaped left elbow panel improving sleeve articulation and reducing restriction.",
  },
  {
    id: "parka-right-articulated-elbow-panel",
    name: "Right Articulated Elbow Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional shaped right elbow panel improving sleeve articulation and reducing restriction.",
  },
  {
    id: "parka-left-elbow-reinforcement",
    name: "Left Elbow Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional abrasion-resistant reinforcement protecting the left elbow during outdoor or industrial use.",
  },
  {
    id: "parka-right-elbow-reinforcement",
    name: "Right Elbow Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Optional abrasion-resistant reinforcement protecting the right elbow during outdoor or industrial use.",
  },
  {
    id: "parka-left-shoulder-reinforcement",
    name: "Left Shoulder Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Optional reinforced panel protecting the left shoulder from straps, equipment and repeated abrasion.",
  },
  {
    id: "parka-right-shoulder-reinforcement",
    name: "Right Shoulder Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional reinforced panel protecting the right shoulder from straps, equipment and repeated abrasion.",
  },
  {
    id: "parka-left-front-facing",
    name: "Left Front Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Left front facing finishing and stabilising the centre-front opening, neckline and zip area.",
  },
  {
    id: "parka-right-front-facing",
    name: "Right Front Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Right front facing finishing and stabilising the centre-front opening, neckline and zip area.",
  },
  {
    id: "parka-front-facing-interfacing",
    name: "Front Facing Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional reinforcement supporting both front facings and the centre-front fastening system.",
  },
  {
    id: "parka-outer-storm-flap",
    name: "Outer Storm Flap",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Outer storm flap covering the centre-front zip to reduce wind, snow and rain penetration.",
  },
  {
    id: "parka-inner-storm-flap",
    name: "Inner Storm Flap",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Internal storm flap positioned behind the centre-front zip for additional weather protection.",
  },
  {
    id: "parka-storm-flap-interfacing",
    name: "Storm Flap Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional reinforcement supporting the outer storm flap and its snap or hook-and-loop fastening positions.",
  },
  {
    id: "parka-zip-guard",
    name: "Zip Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional internal guard preventing the zip teeth and slider from contacting the wearer.",
  },
  {
    id: "parka-chin-guard",
    name: "Chin Guard",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Pair of shell, fleece or padded pieces protecting the chin from the centre-front zip.",
  },
  {
    id: "parka-upper-collar",
    name: "Upper Collar",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 31,
    description:
      "Outer collar section providing structured neck coverage and cold-weather protection.",
  },
  {
    id: "parka-under-collar",
    name: "Under Collar",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 32,
    description:
      "Under-collar section completing the collar and supporting its roll and shape.",
  },
  {
    id: "parka-collar-interfacing",
    name: "Collar Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 33,
    description:
      "Optional reinforcement maintaining collar structure during repeated wear and wet conditions.",
  },
  {
    id: "parka-inner-fleece-collar",
    name: "Inner Fleece Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 34,
    description:
      "Optional fleece, brushed tricot or soft-fabric inner collar improving warmth and comfort.",
  },
  {
    id: "parka-hood-centre-panel",
    name: "Hood Centre Panel",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Central hood panel extending over the crown from the face opening to the back neckline.",
  },
  {
    id: "parka-left-hood-side",
    name: "Left Hood Side",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Left hood side panel shaped around the face, crown and neckline.",
  },
  {
    id: "parka-right-hood-side",
    name: "Right Hood Side",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Right hood side panel shaped around the face, crown and neckline.",
  },
  {
    id: "parka-upper-hood-peak",
    name: "Upper Hood Peak",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Optional upper hood-peak panel shielding the face from rain, snow and glare.",
  },
  {
    id: "parka-under-hood-peak",
    name: "Under Hood Peak",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional lower hood-peak panel completing the peak construction.",
  },
  {
    id: "parka-hood-peak-reinforcement",
    name: "Hood Peak Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional stiffening insert maintaining the hood peak shape and projection.",
  },
  {
    id: "parka-hood-facing",
    name: "Hood Opening Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Facing used to clean-finish and stabilise the hood opening around the face.",
  },
  {
    id: "parka-hood-centre-lining",
    name: "Hood Centre Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional central lining or insulation panel positioned inside the hood.",
  },
  {
    id: "parka-left-hood-lining",
    name: "Left Hood Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional left hood lining panel improving warmth, comfort and internal appearance.",
  },
  {
    id: "parka-right-hood-lining",
    name: "Right Hood Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional right hood lining panel improving warmth, comfort and internal appearance.",
  },
  {
    id: "parka-hood-fur-trim-band",
    name: "Hood Fur Trim Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional detachable or fixed band supporting faux-fur or fur trim around the hood edge.",
  },
  {
    id: "parka-hood-fur-trim-backing",
    name: "Hood Fur Trim Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional backing strip reinforcing the hood edge where fur trim is attached.",
  },
  {
    id: "parka-hood-drawcord-channel",
    name: "Hood Drawcord Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional casing strip containing the hood face-adjustment drawcord.",
  },
  {
    id: "parka-hood-eyelet-reinforcement",
    name: "Hood Eyelet Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional reinforcement patches positioned behind hood drawcord eyelets or cord exits.",
  },
  {
    id: "parka-left-chest-pocket-welt",
    name: "Left Chest Pocket Welt",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional pair of welt pieces forming the left chest pocket opening.",
  },
  {
    id: "parka-right-chest-pocket-welt",
    name: "Right Chest Pocket Welt",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional pair of welt pieces forming the right chest pocket opening.",
  },
  {
    id: "parka-left-chest-pocket-bag",
    name: "Left Chest Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional pair of pocket-bag sections forming the complete left chest pocket.",
  },
  {
    id: "parka-right-chest-pocket-bag",
    name: "Right Chest Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Optional pair of pocket-bag sections forming the complete right chest pocket.",
  },
  {
    id: "parka-left-lower-pocket",
    name: "Left Lower Patch Pocket",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Main left lower utility or cargo pocket providing storage and hand protection.",
  },
  {
    id: "parka-right-lower-pocket",
    name: "Right Lower Patch Pocket",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Main right lower utility or cargo pocket providing storage and hand protection.",
  },
  {
    id: "parka-left-lower-pocket-flap",
    name: "Left Lower Pocket Flap",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Upper and under flap pieces protecting the left lower pocket opening.",
  },
  {
    id: "parka-right-lower-pocket-flap",
    name: "Right Lower Pocket Flap",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Upper and under flap pieces protecting the right lower pocket opening.",
  },
  {
    id: "parka-left-lower-pocket-gusset",
    name: "Left Lower Pocket Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Optional expandable gusset increasing the capacity of the left lower pocket.",
  },
  {
    id: "parka-right-lower-pocket-gusset",
    name: "Right Lower Pocket Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 58,
    description:
      "Optional expandable gusset increasing the capacity of the right lower pocket.",
  },
  {
    id: "parka-left-hand-warmer-pocket-bag",
    name: "Left Hand-Warmer Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 59,
    description:
      "Optional pair of fleece or lining pieces forming a side-entry left hand-warmer pocket.",
  },
  {
    id: "parka-right-hand-warmer-pocket-bag",
    name: "Right Hand-Warmer Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 60,
    description:
      "Optional pair of fleece or lining pieces forming a side-entry right hand-warmer pocket.",
  },
  {
    id: "parka-pocket-drainage-patch",
    name: "Pocket Drainage Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 61,
    description:
      "Optional mesh or reinforced pieces allowing moisture to drain from external pockets.",
  },
  {
    id: "parka-left-sleeve-pocket",
    name: "Left Sleeve Utility Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 62,
    description:
      "Optional patch or zipped utility pocket positioned on the left upper sleeve.",
  },
  {
    id: "parka-right-sleeve-pocket",
    name: "Right Sleeve Utility Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional patch or zipped utility pocket positioned on the right upper sleeve.",
  },
  {
    id: "parka-left-cuff-tab",
    name: "Left Cuff Adjustment Tab",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 64,
    description:
      "Optional upper and under tab pieces used to adjust and secure the left sleeve opening.",
  },
  {
    id: "parka-right-cuff-tab",
    name: "Right Cuff Adjustment Tab",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 65,
    description:
      "Optional upper and under tab pieces used to adjust and secure the right sleeve opening.",
  },
  {
    id: "parka-left-inner-storm-cuff",
    name: "Left Inner Storm Cuff",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 66,
    description:
      "Elasticated, rib-knit or stretch inner cuff reducing cold air and snow entry at the left wrist.",
  },
  {
    id: "parka-right-inner-storm-cuff",
    name: "Right Inner Storm Cuff",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 67,
    description:
      "Elasticated, rib-knit or stretch inner cuff reducing cold air and snow entry at the right wrist.",
  },
  {
    id: "parka-waist-drawcord-channel",
    name: "Waist Drawcord Channel",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 68,
    description:
      "Internal casing strip containing the waist drawcord for fit adjustment and heat retention.",
  },
  {
    id: "parka-waist-eyelet-reinforcement",
    name: "Waist Eyelet Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 69,
    description:
      "Optional reinforcement patches supporting waist drawcord eyelets or cord-lock exits.",
  },
  {
    id: "parka-hem-drawcord-channel",
    name: "Hem Drawcord Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 70,
    description:
      "Optional lower-edge casing containing a hem drawcord for wind and snow protection.",
  },
  {
    id: "parka-hem-eyelet-reinforcement",
    name: "Hem Eyelet Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 71,
    description:
      "Optional reinforcement patches supporting hem drawcord exits or cord locks.",
  },
  {
    id: "parka-left-front-lining",
    name: "Left Front Lining",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 72,
    description:
      "Left front lining panel covering internal construction and improving comfort.",
  },
  {
    id: "parka-right-front-lining",
    name: "Right Front Lining",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 73,
    description:
      "Right front lining panel covering internal construction and improving comfort.",
  },
  {
    id: "parka-back-lining",
    name: "Back Lining",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 74,
    description:
      "Back lining panel covering internal seams and supporting cold-weather comfort.",
  },
  {
    id: "parka-left-sleeve-lining",
    name: "Left Sleeve Lining",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 75,
    description:
      "Left sleeve lining panel providing smooth dressing and internal seam coverage.",
  },
  {
    id: "parka-right-sleeve-lining",
    name: "Right Sleeve Lining",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 76,
    description:
      "Right sleeve lining panel providing smooth dressing and internal seam coverage.",
  },
  {
    id: "parka-left-front-insulation",
    name: "Left Front Insulation",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 77,
    description:
      "Thermal insulation layer positioned between the left front shell and lining.",
  },
  {
    id: "parka-right-front-insulation",
    name: "Right Front Insulation",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 78,
    description:
      "Thermal insulation layer positioned between the right front shell and lining.",
  },
  {
    id: "parka-back-insulation",
    name: "Back Insulation",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 79,
    description:
      "Thermal insulation layer positioned between the back shell and lining.",
  },
  {
    id: "parka-left-sleeve-insulation",
    name: "Left Sleeve Insulation",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 80,
    description:
      "Thermal insulation layer positioned inside the left sleeve.",
  },
  {
    id: "parka-right-sleeve-insulation",
    name: "Right Sleeve Insulation",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 81,
    description:
      "Thermal insulation layer positioned inside the right sleeve.",
  },
  {
    id: "parka-snow-skirt",
    name: "Internal Snow Skirt",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 82,
    description:
      "Optional internal barrier around the lower body reducing snow and cold-air entry.",
  },
  {
    id: "parka-snow-skirt-elastic-channel",
    name: "Snow Skirt Elastic Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 83,
    description:
      "Optional casing strip containing elastic or gripper tape at the snow-skirt edge.",
  },
  {
    id: "parka-left-rear-hem-extension",
    name: "Left Rear Hem Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 84,
    description:
      "Optional left portion of a dropped rear hem providing additional seat and weather coverage.",
  },
  {
    id: "parka-right-rear-hem-extension",
    name: "Right Rear Hem Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 85,
    description:
      "Optional right portion of a dropped rear hem providing additional seat and weather coverage.",
  },
  {
    id: "parka-back-vent-left",
    name: "Left Back Vent Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 86,
    description:
      "Optional left back vent extension improving walking, sitting and movement in a long parka.",
  },
  {
    id: "parka-back-vent-right",
    name: "Right Back Vent Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 87,
    description:
      "Optional right back vent extension overlapping or supporting the centre-back vent.",
  },
  {
    id: "parka-reflective-back-panel",
    name: "Reflective Back Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 88,
    description:
      "Optional reflective back panel improving visibility in low-light outdoor or industrial conditions.",
  },
  {
    id: "parka-reflective-sleeve-panels",
    name: "Reflective Sleeve Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 89,
    description:
      "Optional reflective sleeve panels improving side visibility and wearer safety.",
  },
  {
    id: "parka-hanger-loop",
    name: "Internal Hanger Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 90,
    description:
      "Optional reinforced fabric loop used to hang the parka securely.",
  },
  {
    id: "parka-label-backing",
    name: "Brand Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 91,
    description:
      "Optional backing patch supporting a woven, printed, leather or synthetic brand label.",
  },
  {
    id: "parka-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 92,
    description:
      "Optional backing patches supporting embroidery, badges, logos, identification marks or reflective transfers.",
  },
];

export default parkaPatternMaster;