export const raincoatPatternMaster = [
  {
    id: "raincoat-left-front",
    name: "Left Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Main left front raincoat shell panel including shoulder, armhole, side seam, centre-front opening and hem shaping.",
  },
  {
    id: "raincoat-right-front",
    name: "Right Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Main right front raincoat shell panel including shoulder, armhole, side seam, centre-front opening and hem shaping.",
  },
  {
    id: "raincoat-back",
    name: "Back",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 3,
    description:
      "Main back raincoat shell panel cut on the centre-back fold with shoulder, armhole, side seam and hem shaping.",
  },
  {
    id: "raincoat-left-front-side-panel",
    name: "Left Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional shaped left front side panel used for contouring, colour blocking or functional seam placement.",
  },
  {
    id: "raincoat-right-front-side-panel",
    name: "Right Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional shaped right front side panel used for contouring, colour blocking or functional seam placement.",
  },
  {
    id: "raincoat-left-back-side-panel",
    name: "Left Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional shaped left back side panel improving fit, movement or decorative panel construction.",
  },
  {
    id: "raincoat-right-back-side-panel",
    name: "Right Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Optional shaped right back side panel improving fit, movement or decorative panel construction.",
  },
  {
    id: "raincoat-back-yoke",
    name: "Back Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 8,
    description:
      "Optional upper back yoke supporting shoulder shaping, rain protection and cape-vent construction.",
  },
  {
    id: "raincoat-back-cape",
    name: "Back Cape",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 9,
    description:
      "Optional floating back cape shielding the upper back while allowing ventilation beneath.",
  },
  {
    id: "raincoat-back-cape-lining",
    name: "Back Cape Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 10,
    description:
      "Optional lining or mesh layer supporting the floating back cape and ventilation opening.",
  },
  {
    id: "raincoat-left-upper-sleeve",
    name: "Left Upper Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Main left upper sleeve section shaped for shoulder fit, elbow movement and weather protection.",
  },
  {
    id: "raincoat-right-upper-sleeve",
    name: "Right Upper Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Main right upper sleeve section shaped for shoulder fit, elbow movement and weather protection.",
  },
  {
    id: "raincoat-left-under-sleeve",
    name: "Left Under Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Left under-sleeve section completing the two-piece sleeve and supporting ergonomic movement.",
  },
  {
    id: "raincoat-right-under-sleeve",
    name: "Right Under Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Right under-sleeve section completing the two-piece sleeve and supporting ergonomic movement.",
  },
  {
    id: "raincoat-left-sleeve-lining",
    name: "Left Sleeve Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional left sleeve lining providing comfort, smooth dressing and protection of internal seam construction.",
  },
  {
    id: "raincoat-right-sleeve-lining",
    name: "Right Sleeve Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional right sleeve lining providing comfort, smooth dressing and protection of internal seam construction.",
  },
  {
    id: "raincoat-left-front-facing",
    name: "Left Front Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Left front facing finishing and stabilising the centre-front opening, neckline and fastening area.",
  },
  {
    id: "raincoat-right-front-facing",
    name: "Right Front Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Right front facing finishing and stabilising the centre-front opening, neckline and fastening area.",
  },
  {
    id: "raincoat-front-facing-interfacing",
    name: "Front Facing Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional reinforcement pieces supporting both front facings and centre-front fastening components.",
  },
  {
    id: "raincoat-outer-storm-flap",
    name: "Outer Front Storm Flap",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Outer storm flap covering the centre-front zip or fastening to reduce wind and rain penetration.",
  },
  {
    id: "raincoat-inner-storm-flap",
    name: "Inner Front Storm Flap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Optional internal storm flap providing a second barrier behind the centre-front fastening.",
  },
  {
    id: "raincoat-storm-flap-interfacing",
    name: "Storm Flap Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional reinforcement supporting the shape, snap positions and durability of the outer storm flap.",
  },
  {
    id: "raincoat-zip-guard",
    name: "Zip Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional internal guard positioned behind the zip to protect the wearer and reduce wind penetration.",
  },
  {
    id: "raincoat-rain-gutter",
    name: "Front Rain Gutter",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional channel-shaped internal piece directing water away from the centre-front fastening.",
  },
  {
    id: "raincoat-upper-collar",
    name: "Upper Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 25,
    description:
      "Optional outer collar section providing neck coverage and weather protection.",
  },
  {
    id: "raincoat-under-collar",
    name: "Under Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 26,
    description:
      "Optional under-collar section supporting roll, shape and clean collar construction.",
  },
  {
    id: "raincoat-collar-interfacing",
    name: "Collar Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 27,
    description:
      "Optional reinforcement supporting the collar shape and maintaining structure during wet conditions.",
  },
  {
    id: "raincoat-hood-centre-panel",
    name: "Hood Centre Panel",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Central hood panel running from the front edge over the crown to the back neckline.",
  },
  {
    id: "raincoat-left-hood-side",
    name: "Left Hood Side",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Left hood side panel shaped around the face, crown and neckline.",
  },
  {
    id: "raincoat-right-hood-side",
    name: "Right Hood Side",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Right hood side panel shaped around the face, crown and neckline.",
  },
  {
    id: "raincoat-hood-peak",
    name: "Hood Peak",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Optional upper and under hood-peak pieces shielding the face from direct rainfall.",
  },
  {
    id: "raincoat-hood-peak-reinforcement",
    name: "Hood Peak Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional stiffening piece supporting the hood peak and maintaining its projection.",
  },
  {
    id: "raincoat-hood-facing",
    name: "Hood Face Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Facing used to clean-finish and stabilise the hood opening around the face.",
  },
  {
    id: "raincoat-hood-lining-centre",
    name: "Hood Lining Centre Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional central hood lining panel improving comfort and covering internal seams.",
  },
  {
    id: "raincoat-left-hood-lining",
    name: "Left Hood Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional left hood lining side panel shaped to match the outer hood.",
  },
  {
    id: "raincoat-right-hood-lining",
    name: "Right Hood Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional right hood lining side panel shaped to match the outer hood.",
  },
  {
    id: "raincoat-chin-guard",
    name: "Chin Guard",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Optional padded or folded guard protecting the chin from the zip top and closing hardware.",
  },
  {
    id: "raincoat-neck-guard",
    name: "Back Neck Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 38,
    description:
      "Optional internal neck shield improving comfort and protecting the neckline seam.",
  },
  {
    id: "raincoat-left-pocket-welt",
    name: "Left Pocket Welt",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional pair of welt pieces forming and protecting the left pocket opening.",
  },
  {
    id: "raincoat-right-pocket-welt",
    name: "Right Pocket Welt",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional pair of welt pieces forming and protecting the right pocket opening.",
  },
  {
    id: "raincoat-left-pocket-bag",
    name: "Left Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional pair of waterproof or lined pocket-bag sections forming the left pocket.",
  },
  {
    id: "raincoat-right-pocket-bag",
    name: "Right Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional pair of waterproof or lined pocket-bag sections forming the right pocket.",
  },
  {
    id: "raincoat-left-patch-pocket",
    name: "Left Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional left external patch pocket for storage and weather-resistant utility.",
  },
  {
    id: "raincoat-right-patch-pocket",
    name: "Right Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional right external patch pocket for storage and weather-resistant utility.",
  },
  {
    id: "raincoat-left-bellows-pocket-gusset",
    name: "Left Bellows Pocket Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional expandable gusset increasing the capacity of the left utility pocket.",
  },
  {
    id: "raincoat-right-bellows-pocket-gusset",
    name: "Right Bellows Pocket Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional expandable gusset increasing the capacity of the right utility pocket.",
  },
  {
    id: "raincoat-left-pocket-flap",
    name: "Left Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional upper and under flap pieces protecting the left pocket opening from rain.",
  },
  {
    id: "raincoat-right-pocket-flap",
    name: "Right Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional upper and under flap pieces protecting the right pocket opening from rain.",
  },
  {
    id: "raincoat-pocket-drainage-patch",
    name: "Pocket Drainage Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional mesh or reinforced drainage pieces allowing trapped water to escape from external pockets.",
  },
  {
    id: "raincoat-left-cuff-tab",
    name: "Left Cuff Adjustment Tab",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional upper and under tab pieces used to adjust and secure the left sleeve opening.",
  },
  {
    id: "raincoat-right-cuff-tab",
    name: "Right Cuff Adjustment Tab",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional upper and under tab pieces used to adjust and secure the right sleeve opening.",
  },
  {
    id: "raincoat-cuff-tab-reinforcement",
    name: "Cuff Tab Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Optional reinforcement pieces supporting snap, hook-and-loop or buckle attachment on both cuff tabs.",
  },
  {
    id: "raincoat-left-sleeve-placket-facing",
    name: "Left Sleeve Placket Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Optional facing used to clean-finish and reinforce the left sleeve opening or vent.",
  },
  {
    id: "raincoat-right-sleeve-placket-facing",
    name: "Right Sleeve Placket Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Optional facing used to clean-finish and reinforce the right sleeve opening or vent.",
  },
  {
    id: "raincoat-waist-drawcord-channel",
    name: "Waist Drawcord Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Optional casing strip containing a waist drawcord for fit adjustment and improved wind protection.",
  },
  {
    id: "raincoat-waist-eyelet-reinforcement",
    name: "Waist Eyelet Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Optional reinforcement patches positioned behind waist drawcord eyelets or cord exits.",
  },
  {
    id: "raincoat-hem-drawcord-channel",
    name: "Hem Drawcord Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Optional lower-edge casing holding a hem drawcord to reduce wind and rain entry.",
  },
  {
    id: "raincoat-hem-eyelet-reinforcement",
    name: "Hem Eyelet Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 58,
    description:
      "Optional reinforcement patches supporting hem drawcord eyelets or cord-lock exits.",
  },
  {
    id: "raincoat-front-lining-left",
    name: "Left Front Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 59,
    description:
      "Optional left front lining panel improving comfort and covering internal construction.",
  },
  {
    id: "raincoat-front-lining-right",
    name: "Right Front Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 60,
    description:
      "Optional right front lining panel improving comfort and covering internal construction.",
  },
  {
    id: "raincoat-back-lining",
    name: "Back Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 61,
    description:
      "Optional back lining panel providing comfort, internal protection and clean finishing.",
  },
  {
    id: "raincoat-underarm-vent-panel-left",
    name: "Left Underarm Vent Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 62,
    description:
      "Optional mesh or breathable panel improving airflow beneath the left arm.",
  },
  {
    id: "raincoat-underarm-vent-panel-right",
    name: "Right Underarm Vent Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional mesh or breathable panel improving airflow beneath the right arm.",
  },
  {
    id: "raincoat-shoulder-reinforcement-left",
    name: "Left Shoulder Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 64,
    description:
      "Optional reinforcement panel protecting the left shoulder from abrasion, loads or repeated use.",
  },
  {
    id: "raincoat-shoulder-reinforcement-right",
    name: "Right Shoulder Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 65,
    description:
      "Optional reinforcement panel protecting the right shoulder from abrasion, loads or repeated use.",
  },
  {
    id: "raincoat-elbow-reinforcement-left",
    name: "Left Elbow Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 66,
    description:
      "Optional shaped reinforcement panel protecting the left elbow from abrasion.",
  },
  {
    id: "raincoat-elbow-reinforcement-right",
    name: "Right Elbow Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 67,
    description:
      "Optional shaped reinforcement panel protecting the right elbow from abrasion.",
  },
  {
    id: "raincoat-reflective-back-panel",
    name: "Reflective Back Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 68,
    description:
      "Optional high-visibility reflective panel positioned across the back.",
  },
  {
    id: "raincoat-reflective-sleeve-panels",
    name: "Reflective Sleeve Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 69,
    description:
      "Optional reflective sleeve panels improving wearer visibility in low-light conditions.",
  },
  {
    id: "raincoat-seam-reinforcement-strip",
    name: "Waterproof Seam Reinforcement Strip",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 70,
    description:
      "Optional fabric reinforcement strip used beneath highly stressed waterproof seams before sealing.",
  },
  {
    id: "raincoat-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 71,
    description:
      "Optional backing patches supporting logos, embroidery, badges, reflective transfers or identification markings.",
  },
];

export default raincoatPatternMaster;