export const shortsPatternMaster = [
  {
    id: "shorts-left-front",
    name: "Left Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Main left front shorts panel including waist, hip, front rise, thigh, side seam and leg opening shaping.",
  },
  {
    id: "shorts-right-front",
    name: "Right Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Main right front shorts panel including waist, hip, front rise, thigh, side seam and leg opening shaping.",
  },
  {
    id: "shorts-left-back",
    name: "Left Back",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Main left back shorts panel shaped for seat, back rise, thigh, side seam and leg opening.",
  },
  {
    id: "shorts-right-back",
    name: "Right Back",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Main right back shorts panel shaped for seat, back rise, thigh, side seam and leg opening.",
  },
  {
    id: "shorts-left-front-pocket-facing",
    name: "Left Front Pocket Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Left pocket facing used to clean-finish and stabilise a slant or curved front pocket opening.",
  },
  {
    id: "shorts-right-front-pocket-facing",
    name: "Right Front Pocket Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Right pocket facing used to clean-finish and stabilise a slant or curved front pocket opening.",
  },
  {
    id: "shorts-left-front-pocket-bag",
    name: "Left Front Pocket Bag",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Pair of pocket-bag sections forming the complete left front pocket.",
  },
  {
    id: "shorts-right-front-pocket-bag",
    name: "Right Front Pocket Bag",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Pair of pocket-bag sections forming the complete right front pocket.",
  },
  {
    id: "shorts-left-pocket-bearer",
    name: "Left Front Pocket Bearer",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Left bearer or shield restoring visible shell fabric behind the front pocket opening.",
  },
  {
    id: "shorts-right-pocket-bearer",
    name: "Right Front Pocket Bearer",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Right bearer or shield restoring visible shell fabric behind the front pocket opening.",
  },
  {
    id: "shorts-left-back-pocket",
    name: "Left Back Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Optional left back patch pocket for casual, workwear or sports shorts.",
  },
  {
    id: "shorts-right-back-pocket",
    name: "Right Back Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Optional right back patch pocket for casual, workwear or sports shorts.",
  },
  {
    id: "shorts-left-back-pocket-flap",
    name: "Left Back Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional upper and under flap pieces covering the left back pocket.",
  },
  {
    id: "shorts-right-back-pocket-flap",
    name: "Right Back Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Optional upper and under flap pieces covering the right back pocket.",
  },
  {
    id: "shorts-left-waistband",
    name: "Left Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Left waistband section extending from centre back to centre front.",
  },
  {
    id: "shorts-right-waistband",
    name: "Right Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Right waistband section extending from centre back to centre front.",
  },
  {
    id: "shorts-left-inner-waistband",
    name: "Left Inner Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional left inner waistband section used to finish and stabilise the waist.",
  },
  {
    id: "shorts-right-inner-waistband",
    name: "Right Inner Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional right inner waistband section used to finish and stabilise the waist.",
  },
  {
    id: "shorts-waistband-interfacing",
    name: "Waistband Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional reinforcement sections supporting the left and right waistbands.",
  },
  {
    id: "shorts-elastic-waistband",
    name: "Elastic Waistband Casing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 20,
    description:
      "Optional one-piece waistband casing for elasticated casual, sports or sleepwear shorts.",
  },
  {
    id: "shorts-front-fly",
    name: "Front Fly",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Optional outer fly piece supporting a zip or button fastening.",
  },
  {
    id: "shorts-fly-shield",
    name: "Fly Shield",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional internal fly shield protecting the wearer and concealing the fastening.",
  },
  {
    id: "shorts-fly-interfacing",
    name: "Fly Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional reinforcement supporting the fly shape and fastening installation.",
  },
  {
    id: "shorts-belt-loop-strip",
    name: "Belt Loop Strip",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional continuous strip used to manufacture the complete set of waistband belt loops.",
  },
  {
    id: "shorts-drawcord-channel",
    name: "Drawcord Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional internal or external casing used to hold a waist drawcord.",
  },
  {
    id: "shorts-drawcord-eyelet-reinforcement",
    name: "Drawcord Eyelet Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional reinforcement patches placed behind the waistband drawcord eyelets.",
  },
  {
    id: "shorts-left-side-vent-facing",
    name: "Left Side Vent Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional pair of facing sections used to clean-finish a left side-leg vent.",
  },
  {
    id: "shorts-right-side-vent-facing",
    name: "Right Side Vent Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional pair of facing sections used to clean-finish a right side-leg vent.",
  },
  {
    id: "shorts-left-hem-facing",
    name: "Left Hem Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional shaped facing used to finish the left leg opening.",
  },
  {
    id: "shorts-right-hem-facing",
    name: "Right Hem Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Optional shaped facing used to finish the right leg opening.",
  },
  {
    id: "shorts-left-cargo-pocket",
    name: "Left Cargo Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Optional utility or cargo pocket positioned on the left thigh.",
  },
  {
    id: "shorts-right-cargo-pocket",
    name: "Right Cargo Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional utility or cargo pocket positioned on the right thigh.",
  },
  {
    id: "shorts-left-cargo-pocket-flap",
    name: "Left Cargo Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Optional upper and under flap pieces covering the left cargo pocket.",
  },
  {
    id: "shorts-right-cargo-pocket-flap",
    name: "Right Cargo Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional upper and under flap pieces covering the right cargo pocket.",
  },
  {
    id: "shorts-left-cargo-pocket-gusset",
    name: "Left Cargo Pocket Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional gusset providing expandable capacity to the left cargo pocket.",
  },
  {
    id: "shorts-right-cargo-pocket-gusset",
    name: "Right Cargo Pocket Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional gusset providing expandable capacity to the right cargo pocket.",
  },
  {
    id: "shorts-inner-brief-front",
    name: "Inner Brief Front",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 37,
    description:
      "Optional front section of an integrated brief lining used in running, swim or performance shorts.",
  },
  {
    id: "shorts-inner-brief-back",
    name: "Inner Brief Back",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 38,
    description:
      "Optional back section of an integrated brief lining used in running, swim or performance shorts.",
  },
  {
    id: "shorts-inner-leg-left",
    name: "Left Inner Compression Leg",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional left inner compression leg for two-in-one sports shorts.",
  },
  {
    id: "shorts-inner-leg-right",
    name: "Right Inner Compression Leg",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional right inner compression leg for two-in-one sports shorts.",
  },
  {
    id: "shorts-crotch-gusset",
    name: "Crotch Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional diamond or shaped gusset improving mobility and reducing crotch-seam stress.",
  },
  {
    id: "shorts-left-side-panel",
    name: "Left Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional contrast, mesh or performance panel positioned along the left side seam.",
  },
  {
    id: "shorts-right-side-panel",
    name: "Right Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional contrast, mesh or performance panel positioned along the right side seam.",
  },
  {
    id: "shorts-left-reflective-panel",
    name: "Left Reflective Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional reflective panel or insert improving visibility on the left side.",
  },
  {
    id: "shorts-right-reflective-panel",
    name: "Right Reflective Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional reflective panel or insert improving visibility on the right side.",
  },
  {
    id: "shorts-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional backing patches supporting embroidery, logos, badges, numbers or heat-transfer graphics.",
  },
];

export default shortsPatternMaster;