export const skirtPatternMaster = [
  {
    id: "skirt-front",
    name: "Front Skirt",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 1,
    description:
      "Main front skirt panel cut on the centre-front fold, including waist, hip, side seam and hem shaping.",
  },
  {
    id: "skirt-left-back",
    name: "Left Back Skirt",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Main left back skirt panel including waist, hip, centre-back seam, side seam and hem shaping.",
  },
  {
    id: "skirt-right-back",
    name: "Right Back Skirt",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Main right back skirt panel including waist, hip, centre-back seam, side seam and hem shaping.",
  },
  {
    id: "skirt-front-waistband",
    name: "Front Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 4,
    description:
      "Front waistband section shaped to support and finish the front waistline.",
  },
  {
    id: "skirt-left-back-waistband",
    name: "Left Back Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Left back waistband section extending from the side seam to the centre-back opening.",
  },
  {
    id: "skirt-right-back-waistband",
    name: "Right Back Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Right back waistband section extending from the side seam to the centre-back opening.",
  },
  {
    id: "skirt-front-inner-waistband",
    name: "Front Inner Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 7,
    description:
      "Optional front inner waistband section used to clean-finish and stabilise the waist.",
  },
  {
    id: "skirt-left-back-inner-waistband",
    name: "Left Back Inner Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Optional left back inner waistband section used to finish the waist internally.",
  },
  {
    id: "skirt-right-back-inner-waistband",
    name: "Right Back Inner Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional right back inner waistband section used to finish the waist internally.",
  },
  {
    id: "skirt-waistband-interfacing",
    name: "Waistband Interfacing",
    required: true,
    cutQuantity: 3,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Reinforcement sections supporting the front and back waistband components.",
  },
  {
    id: "skirt-front-waist-facing",
    name: "Front Waist Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 11,
    description:
      "Optional shaped front waist facing used in a waistband-free skirt construction.",
  },
  {
    id: "skirt-left-back-waist-facing",
    name: "Left Back Waist Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Optional left back waist facing used to clean-finish a waistband-free skirt.",
  },
  {
    id: "skirt-right-back-waist-facing",
    name: "Right Back Waist Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional right back waist facing used to clean-finish a waistband-free skirt.",
  },
  {
    id: "skirt-front-lining",
    name: "Front Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 14,
    description:
      "Optional front lining panel improving comfort, opacity, drape and internal appearance.",
  },
  {
    id: "skirt-left-back-lining",
    name: "Left Back Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional left back lining panel shaped around the centre-back opening and vent.",
  },
  {
    id: "skirt-right-back-lining",
    name: "Right Back Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional right back lining panel shaped around the centre-back opening and vent.",
  },
  {
    id: "skirt-left-front-pocket-facing",
    name: "Left Front Pocket Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional left pocket facing used to finish and stabilise a slant or curved front pocket opening.",
  },
  {
    id: "skirt-right-front-pocket-facing",
    name: "Right Front Pocket Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional right pocket facing used to finish and stabilise a slant or curved front pocket opening.",
  },
  {
    id: "skirt-left-front-pocket-bag",
    name: "Left Front Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional pair of pocket-bag sections forming the complete left front pocket.",
  },
  {
    id: "skirt-right-front-pocket-bag",
    name: "Right Front Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Optional pair of pocket-bag sections forming the complete right front pocket.",
  },
  {
    id: "skirt-left-pocket-bearer",
    name: "Left Front Pocket Bearer",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Optional left pocket bearer restoring visible shell fabric behind the pocket opening.",
  },
  {
    id: "skirt-right-pocket-bearer",
    name: "Right Front Pocket Bearer",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional right pocket bearer restoring visible shell fabric behind the pocket opening.",
  },
  {
    id: "skirt-left-patch-pocket",
    name: "Left Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional patch pocket positioned on the left front or side of the skirt.",
  },
  {
    id: "skirt-right-patch-pocket",
    name: "Right Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional patch pocket positioned on the right front or side of the skirt.",
  },
  {
    id: "skirt-left-patch-pocket-flap",
    name: "Left Patch Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional upper and under flap pieces covering the left patch pocket.",
  },
  {
    id: "skirt-right-patch-pocket-flap",
    name: "Right Patch Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional upper and under flap pieces covering the right patch pocket.",
  },
  {
    id: "skirt-centre-back-vent-left",
    name: "Left Back Vent Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional left centre-back vent or kick-pleat extension allowing walking movement.",
  },
  {
    id: "skirt-centre-back-vent-right",
    name: "Right Back Vent Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional right centre-back vent or kick-pleat extension overlapping the left vent section.",
  },
  {
    id: "skirt-left-side-vent-facing",
    name: "Left Side Vent Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional pair of shaped facing sections used to finish a left side vent.",
  },
  {
    id: "skirt-right-side-vent-facing",
    name: "Right Side Vent Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Optional pair of shaped facing sections used to finish a right side vent.",
  },
  {
    id: "skirt-front-pleat-panel",
    name: "Front Pleat Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 31,
    description:
      "Optional front inverted, box or knife-pleat panel providing volume and movement.",
  },
  {
    id: "skirt-back-pleat-panel",
    name: "Back Pleat Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 32,
    description:
      "Optional back pleat panel providing additional sweep and movement.",
  },
  {
    id: "skirt-left-side-godet",
    name: "Left Side Godet",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Optional triangular or flared insert increasing sweep at the left side.",
  },
  {
    id: "skirt-right-side-godet",
    name: "Right Side Godet",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional triangular or flared insert increasing sweep at the right side.",
  },
  {
    id: "skirt-front-centre-godet",
    name: "Front Centre Godet",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional front-centre godet providing flare, movement or decorative contrast.",
  },
  {
    id: "skirt-back-centre-godet",
    name: "Back Centre Godet",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional back-centre godet providing additional sweep and movement.",
  },
  {
    id: "skirt-left-flounce",
    name: "Left Flounce Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Optional circular or spiral flounce panel positioned on the left side or hem.",
  },
  {
    id: "skirt-right-flounce",
    name: "Right Flounce Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Optional circular or spiral flounce panel positioned on the right side or hem.",
  },
  {
    id: "skirt-bottom-ruffle",
    name: "Bottom Ruffle",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional gathered, pleated or circular ruffle attached around the lower skirt edge.",
  },
  {
    id: "skirt-wrap-front-left",
    name: "Left Wrap Front",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional left overlapping front panel used in wrap-skirt construction.",
  },
  {
    id: "skirt-wrap-front-right",
    name: "Right Wrap Front",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional right underlapping front panel used in wrap-skirt construction.",
  },
  {
    id: "skirt-wrap-tie-left",
    name: "Left Wrap Tie",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional left waist tie used to secure a wrap skirt.",
  },
  {
    id: "skirt-wrap-tie-right",
    name: "Right Wrap Tie",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional right waist tie used to secure a wrap skirt.",
  },
  {
    id: "skirt-zip-guard",
    name: "Zip Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional internal guard protecting the wearer from the centre-back or side zip.",
  },
  {
    id: "skirt-hook-and-bar-reinforcement",
    name: "Hook-and-Bar Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional reinforcement patches supporting waistband hook-and-bar fastening positions.",
  },
  {
    id: "skirt-hem-facing",
    name: "Hem Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional shaped facing used to clean-finish a curved, shaped or asymmetric hem.",
  },
  {
    id: "skirt-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional backing patches supporting embroidery, appliqué, badges, sequins or heat-transfer decoration.",
  },
];

export default skirtPatternMaster;