export const socksPatternMaster = [
  {
    id: "socks-main-foot-body",
    name: "Main Foot Body",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Primary knitted foot section forming the upper foot, lower foot and side coverage of a standard pair of socks.",
  },
  {
    id: "socks-left-foot-body",
    name: "Left Foot Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Optional anatomically shaped left foot body used in performance, compression or specialist sock construction.",
  },
  {
    id: "socks-right-foot-body",
    name: "Right Foot Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Optional anatomically shaped right foot body used in performance, compression or specialist sock construction.",
  },
  {
    id: "socks-upper-foot-panel",
    name: "Upper Foot Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional upper-foot panel covering the instep and supporting engineered ventilation, compression or decorative knitting.",
  },
  {
    id: "socks-lower-foot-panel",
    name: "Lower Foot Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional sole panel forming the lower foot surface and supporting cushioning, reinforcement or moisture control.",
  },
  {
    id: "socks-left-upper-foot-panel",
    name: "Left Upper Foot Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional anatomically shaped left instep panel used in technical or directional sock construction.",
  },
  {
    id: "socks-right-upper-foot-panel",
    name: "Right Upper Foot Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Optional anatomically shaped right instep panel used in technical or directional sock construction.",
  },
  {
    id: "socks-left-lower-foot-panel",
    name: "Left Lower Foot Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Optional anatomically shaped left sole panel designed for targeted cushioning and support.",
  },
  {
    id: "socks-right-lower-foot-panel",
    name: "Right Lower Foot Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional anatomically shaped right sole panel designed for targeted cushioning and support.",
  },
  {
    id: "socks-leg-body",
    name: "Leg Body",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Main knitted leg section extending upward from the ankle to the required sock height.",
  },
  {
    id: "socks-left-leg-body",
    name: "Left Leg Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Optional anatomically engineered left leg section used in directional, medical or sport sock construction.",
  },
  {
    id: "socks-right-leg-body",
    name: "Right Leg Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Optional anatomically engineered right leg section used in directional, medical or sport sock construction.",
  },
  {
    id: "socks-front-leg-panel",
    name: "Front Leg Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional front leg panel used for decoration, shin protection, ventilation or compression zoning.",
  },
  {
    id: "socks-back-leg-panel",
    name: "Back Leg Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Optional back leg panel used for calf shaping, ventilation, reinforcement or support.",
  },
  {
    id: "socks-left-side-leg-panel",
    name: "Left Side Leg Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional outer or inner left-side leg insert used for colour blocking, support or branding.",
  },
  {
    id: "socks-right-side-leg-panel",
    name: "Right Side Leg Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional outer or inner right-side leg insert used for colour blocking, support or branding.",
  },
  {
    id: "socks-ankle-body",
    name: "Ankle Body",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Knitted transition section joining the foot and leg while allowing ankle movement and controlled fit.",
  },
  {
    id: "socks-front-ankle-panel",
    name: "Front Ankle Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional shaped front ankle insert supporting flexibility and reducing pressure during foot movement.",
  },
  {
    id: "socks-back-ankle-panel",
    name: "Back Ankle Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional shaped rear ankle panel improving Achilles comfort, fit and movement.",
  },
  {
    id: "socks-ankle-flex-zone",
    name: "Ankle Flex Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Optional engineered stretch section positioned across the ankle bend for improved mobility.",
  },
  {
    id: "socks-heel-main",
    name: "Main Heel",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Primary shaped heel section providing fit, durability and three-dimensional foot accommodation.",
  },
  {
    id: "socks-left-heel",
    name: "Left Anatomical Heel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional anatomically shaped left heel used for directional and performance sock construction.",
  },
  {
    id: "socks-right-heel",
    name: "Right Anatomical Heel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional anatomically shaped right heel used for directional and performance sock construction.",
  },
  {
    id: "socks-heel-gore",
    name: "Heel Gore",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional shaped insert increasing heel depth, contour and movement capacity.",
  },
  {
    id: "socks-heel-cup",
    name: "Heel Cup",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional structured or reinforced heel cup improving stability and reducing sock movement.",
  },
  {
    id: "socks-heel-reinforcement",
    name: "Heel Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional abrasion-resistant or cushioned layer protecting the heel from repeated wear.",
  },
  {
    id: "socks-achilles-protector",
    name: "Achilles Protector",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional padded or reinforced extension positioned above the heel to protect the Achilles area.",
  },
  {
    id: "socks-heel-tab",
    name: "Heel Pull Tab",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional tab extending above the heel to assist dressing and reduce shoe-edge rubbing.",
  },
  {
    id: "socks-heel-tab-backing",
    name: "Heel Tab Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional support layer strengthening the heel pull-tab attachment area.",
  },
  {
    id: "socks-toe-main",
    name: "Main Toe",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Primary shaped toe section enclosing the front of the foot and joining the upper and lower foot panels.",
  },
  {
    id: "socks-left-toe",
    name: "Left Anatomical Toe",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Optional anatomically shaped left toe section following the natural toe line.",
  },
  {
    id: "socks-right-toe",
    name: "Right Anatomical Toe",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional anatomically shaped right toe section following the natural toe line.",
  },
  {
    id: "socks-toe-cap",
    name: "Toe Cap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Optional separate cap panel forming and reinforcing the forward toe area.",
  },
  {
    id: "socks-toe-reinforcement",
    name: "Toe Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional abrasion-resistant or cushioned layer protecting the toe area from repeated wear.",
  },
  {
    id: "socks-seamless-toe-cover",
    name: "Seamless Toe Cover",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional smooth inner toe-cover section reducing seam pressure and irritation.",
  },
  {
    id: "socks-big-toe-pocket",
    name: "Big Toe Pocket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional separate pocket enclosing the big toe in split-toe or specialist sock construction.",
  },
  {
    id: "socks-small-toe-pocket",
    name: "Small Toe Group Pocket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Optional pocket enclosing the remaining toes in split-toe sock construction.",
  },
  {
    id: "socks-first-toe-pocket",
    name: "First Toe Pocket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Optional individual pocket for the first toe in five-toe sock construction.",
  },
  {
    id: "socks-second-toe-pocket",
    name: "Second Toe Pocket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional individual pocket for the second toe in five-toe sock construction.",
  },
  {
    id: "socks-third-toe-pocket",
    name: "Third Toe Pocket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional individual pocket for the third toe in five-toe sock construction.",
  },
  {
    id: "socks-fourth-toe-pocket",
    name: "Fourth Toe Pocket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional individual pocket for the fourth toe in five-toe sock construction.",
  },
  {
    id: "socks-fifth-toe-pocket",
    name: "Fifth Toe Pocket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional individual pocket for the fifth toe in five-toe sock construction.",
  },
  {
    id: "socks-cuff-band",
    name: "Cuff Band",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Primary upper band providing stretch, recovery and secure positioning around the ankle or leg.",
  },
  {
    id: "socks-double-layer-cuff-outer",
    name: "Outer Double-Layer Cuff",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional outer cuff section forming a reinforced or folded double-layer top band.",
  },
  {
    id: "socks-double-layer-cuff-inner",
    name: "Inner Double-Layer Cuff",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional inner cuff section completing a double-layer top band.",
  },
  {
    id: "socks-soft-top-band",
    name: "Soft Top Band",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional low-pressure upper band used in diabetic, comfort and circulation-sensitive socks.",
  },
  {
    id: "socks-non-binding-cuff",
    name: "Non-Binding Cuff",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional stretch-controlled cuff designed to reduce pressure marks and constriction.",
  },
  {
    id: "socks-compression-top-band",
    name: "Compression Top Band",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional engineered upper band stabilising graduated compression socks without rolling.",
  },
  {
    id: "socks-grip-top-band",
    name: "Internal Grip Top Band",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional inner upper band supporting silicone grip or anti-slip application.",
  },
  {
    id: "socks-cuff-lining",
    name: "Cuff Lining",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional soft inner cuff layer improving comfort and protecting sensitive skin.",
  },
  {
    id: "socks-arch-support-band",
    name: "Arch Support Band",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional engineered compression band positioned around the midfoot to support the arch.",
  },
  {
    id: "socks-medial-arch-panel",
    name: "Medial Arch Support Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Optional inner-foot support panel providing targeted medial arch control.",
  },
  {
    id: "socks-lateral-arch-panel",
    name: "Lateral Arch Support Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Optional outer-foot support panel stabilising lateral movement.",
  },
  {
    id: "socks-midfoot-compression-zone",
    name: "Midfoot Compression Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Optional engineered zone controlling stretch and improving foot stability around the midfoot.",
  },
  {
    id: "socks-calf-compression-panel",
    name: "Calf Compression Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Optional engineered leg section providing controlled compression around the calf.",
  },
  {
    id: "socks-shin-compression-panel",
    name: "Shin Compression Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Optional front lower-leg compression zone supporting the shin and improving fit stability.",
  },
  {
    id: "socks-ankle-compression-panel",
    name: "Ankle Compression Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Optional high-control compression zone positioned around the ankle.",
  },
  {
    id: "socks-graduated-compression-lower-zone",
    name: "Graduated Compression Lower Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 58,
    description:
      "Optional lower section engineered to provide the highest compression near the ankle.",
  },
  {
    id: "socks-graduated-compression-middle-zone",
    name: "Graduated Compression Middle Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 59,
    description:
      "Optional middle leg section providing controlled intermediate compression.",
  },
  {
    id: "socks-graduated-compression-upper-zone",
    name: "Graduated Compression Upper Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 60,
    description:
      "Optional upper leg section providing reduced compression toward the sock opening.",
  },
  {
    id: "socks-toe-cushion",
    name: "Toe Cushion Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 61,
    description:
      "Optional padded or terry-loop section cushioning the toe and forefoot.",
  },
  {
    id: "socks-ball-of-foot-cushion",
    name: "Ball-of-Foot Cushion",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 62,
    description:
      "Optional targeted cushioning panel positioned beneath the forefoot pressure zone.",
  },
  {
    id: "socks-arch-cushion",
    name: "Arch Cushion Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional cushioning section positioned beneath the arch for comfort and impact control.",
  },
  {
    id: "socks-heel-cushion",
    name: "Heel Cushion Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 64,
    description:
      "Optional padded section positioned beneath and around the heel for impact absorption.",
  },
  {
    id: "socks-full-sole-cushion",
    name: "Full Sole Cushion",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 65,
    description:
      "Optional continuous cushioned sole layer extending from the toe to the heel.",
  },
  {
    id: "socks-full-foot-cushion",
    name: "Full Foot Cushion",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 66,
    description:
      "Optional padded foot construction surrounding the upper, lower and side areas of the foot.",
  },
  {
    id: "socks-shin-cushion",
    name: "Shin Cushion Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 67,
    description:
      "Optional padded front-leg panel used in hiking, skiing, football and protective sport socks.",
  },
  {
    id: "socks-calf-cushion",
    name: "Calf Cushion Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 68,
    description:
      "Optional padded rear-leg section improving comfort inside boots or protective footwear.",
  },
  {
    id: "socks-instep-ventilation-panel",
    name: "Instep Ventilation Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 69,
    description:
      "Optional open-knit or mesh zone improving airflow over the upper foot.",
  },
  {
    id: "socks-side-ventilation-panels",
    name: "Side Ventilation Panels",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 70,
    description:
      "Optional paired side mesh zones improving airflow along both sides of each foot.",
  },
  {
    id: "socks-leg-ventilation-panel",
    name: "Leg Ventilation Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 71,
    description:
      "Optional breathable panel positioned along the front, back or side of the sock leg.",
  },
  {
    id: "socks-moisture-wicking-sole",
    name: "Moisture-Wicking Sole Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 72,
    description:
      "Optional technical sole section designed to transfer moisture away from the foot.",
  },
  {
    id: "socks-inner-liner",
    name: "Inner Sock Liner",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 73,
    description:
      "Optional lightweight inner layer reducing friction, improving moisture transfer and helping prevent blisters.",
  },
  {
    id: "socks-thermal-foot-lining",
    name: "Thermal Foot Lining",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 74,
    description:
      "Optional insulating inner foot layer used in cold-weather and thermal sock construction.",
  },
  {
    id: "socks-thermal-leg-lining",
    name: "Thermal Leg Lining",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 75,
    description:
      "Optional insulating inner leg layer providing additional warmth above the ankle.",
  },
  {
    id: "socks-waterproof-membrane-foot",
    name: "Waterproof Foot Membrane",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 76,
    description:
      "Optional waterproof and breathable membrane layer enclosing the foot section.",
  },
  {
    id: "socks-waterproof-membrane-leg",
    name: "Waterproof Leg Membrane",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 77,
    description:
      "Optional waterproof and breathable membrane layer extending upward through the sock leg.",
  },
  {
    id: "socks-membrane-seam-cover",
    name: "Membrane Seam Cover",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 78,
    description:
      "Optional internal strip covering and protecting membrane joining seams.",
  },
  {
    id: "socks-anti-slip-sole-panel",
    name: "Anti-Slip Sole Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 79,
    description:
      "Optional sole support panel prepared for silicone, rubber or grip-print application.",
  },
  {
    id: "socks-heel-grip-panel",
    name: "Internal Heel Grip Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 80,
    description:
      "Optional inner heel panel supporting silicone grip and reducing sock slippage.",
  },
  {
    id: "socks-toe-seam-cover",
    name: "Toe Seam Cover",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 81,
    description:
      "Optional smooth inner strip covering the toe seam and reducing irritation.",
  },
  {
    id: "socks-heel-seam-cover",
    name: "Heel Seam Cover",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 82,
    description:
      "Optional inner strip covering a heel joining seam for comfort and durability.",
  },
  {
    id: "socks-leg-seam-cover",
    name: "Leg Seam Cover",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 83,
    description:
      "Optional internal strip covering a longitudinal sock-leg seam.",
  },
  {
    id: "socks-sensor-pocket",
    name: "Sensor Pocket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 84,
    description:
      "Optional small pocket supporting a wearable sensor, tracking device or medical-monitoring component.",
  },
  {
    id: "socks-sensor-pocket-facing",
    name: "Sensor Pocket Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 85,
    description:
      "Optional facing stabilising and clean-finishing the sensor pocket opening.",
  },
  {
    id: "socks-reflective-leg-panel",
    name: "Reflective Leg Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 86,
    description:
      "Optional reflective or high-visibility section positioned on the sock leg.",
  },
  {
    id: "socks-logo-backing",
    name: "Logo Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 87,
    description:
      "Optional support patch positioned behind embroidery, badges, transfers or branding.",
  },
  {
    id: "socks-size-label-backing",
    name: "Size Label Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 88,
    description:
      "Optional internal support area for size identification or product coding.",
  },
  {
    id: "socks-grip-print-backing",
    name: "Grip Print Backing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 89,
    description:
      "Optional stabilising sole layer supporting anti-slip print application.",
  },
  {
    id: "socks-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 90,
    description:
      "Optional backing patches supporting logos, embroidery, appliqué, badges or decorative applications.",
  },
];

export default socksPatternMaster;