export const sweaterPatternMaster = [
  {
    id: "sweater-front-body",
    name: "Front Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 1,
    description:
      "Main front sweater body panel including neckline, shoulder, armhole, side seam and lower-edge shaping.",
  },
  {
    id: "sweater-back-body",
    name: "Back Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 2,
    description:
      "Main back sweater body panel including back neckline, shoulder, armhole, side seam and lower-edge shaping.",
  },
  {
    id: "sweater-left-front-body",
    name: "Left Front Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Optional separate left front body panel used for asymmetric, colour-blocked, panelled or engineered knit constructions.",
  },
  {
    id: "sweater-right-front-body",
    name: "Right Front Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional separate right front body panel used for asymmetric, colour-blocked, panelled or engineered knit constructions.",
  },
  {
    id: "sweater-left-back-body",
    name: "Left Back Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional separate left back body panel used where the centre back is seamed or panelled.",
  },
  {
    id: "sweater-right-back-body",
    name: "Right Back Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional separate right back body panel used where the centre back is seamed or panelled.",
  },
  {
    id: "sweater-front-yoke",
    name: "Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 7,
    description:
      "Optional upper front yoke used for shaping, decorative knitting, contrast fabric or seam relocation.",
  },
  {
    id: "sweater-back-yoke",
    name: "Back Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 8,
    description:
      "Optional upper back yoke supporting shoulder shaping, decorative knitting or contrast construction.",
  },
  {
    id: "sweater-left-front-side-panel",
    name: "Left Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional shaped left front side panel used for contouring, colour blocking or engineered seam placement.",
  },
  {
    id: "sweater-right-front-side-panel",
    name: "Right Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Optional shaped right front side panel used for contouring, colour blocking or engineered seam placement.",
  },
  {
    id: "sweater-left-back-side-panel",
    name: "Left Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Optional shaped left back panel improving fit and supporting decorative or structural seam placement.",
  },
  {
    id: "sweater-right-back-side-panel",
    name: "Right Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Optional shaped right back panel improving fit and supporting decorative or structural seam placement.",
  },
  {
    id: "sweater-left-set-in-sleeve",
    name: "Left Set-In Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Main left set-in sleeve panel shaped for armhole compatibility, elbow movement and wrist taper.",
  },
  {
    id: "sweater-right-set-in-sleeve",
    name: "Right Set-In Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Main right set-in sleeve panel shaped for armhole compatibility, elbow movement and wrist taper.",
  },
  {
    id: "sweater-left-raglan-sleeve",
    name: "Left Raglan Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional left raglan sleeve extending from the neckline to the underarm for relaxed movement and athletic styling.",
  },
  {
    id: "sweater-right-raglan-sleeve",
    name: "Right Raglan Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional right raglan sleeve extending from the neckline to the underarm for relaxed movement and athletic styling.",
  },
  {
    id: "sweater-left-drop-shoulder-sleeve",
    name: "Left Drop-Shoulder Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional left sleeve designed for a dropped shoulder seam and relaxed oversized silhouette.",
  },
  {
    id: "sweater-right-drop-shoulder-sleeve",
    name: "Right Drop-Shoulder Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional right sleeve designed for a dropped shoulder seam and relaxed oversized silhouette.",
  },
  {
    id: "sweater-left-upper-sleeve",
    name: "Left Upper Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional upper section of a two-piece left sleeve used for shaping, contrast knitting or ergonomic fit.",
  },
  {
    id: "sweater-right-upper-sleeve",
    name: "Right Upper Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Optional upper section of a two-piece right sleeve used for shaping, contrast knitting or ergonomic fit.",
  },
  {
    id: "sweater-left-under-sleeve",
    name: "Left Under Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Optional under section completing a two-piece left sleeve and improving arm movement.",
  },
  {
    id: "sweater-right-under-sleeve",
    name: "Right Under Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional under section completing a two-piece right sleeve and improving arm movement.",
  },
  {
    id: "sweater-left-elbow-patch",
    name: "Left Elbow Patch",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional reinforcement or decorative patch positioned over the left elbow.",
  },
  {
    id: "sweater-right-elbow-patch",
    name: "Right Elbow Patch",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional reinforcement or decorative patch positioned over the right elbow.",
  },
  {
    id: "sweater-crew-neck-rib",
    name: "Crew Neck Rib",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Circular, folded or joined rib piece finishing a standard round crew neckline.",
  },
  {
    id: "sweater-v-neck-rib-left",
    name: "Left V-Neck Rib",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional left rib section forming one side of a V-neck opening.",
  },
  {
    id: "sweater-v-neck-rib-right",
    name: "Right V-Neck Rib",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional right rib section forming the opposite side of a V-neck opening.",
  },
  {
    id: "sweater-v-neck-centre-reinforcement",
    name: "V-Neck Centre Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional reinforcement piece stabilising the lower point of a V-neck opening.",
  },
  {
    id: "sweater-mock-neck-band",
    name: "Mock Neck Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional shaped or rectangular band forming a short raised mock neckline.",
  },
  {
    id: "sweater-turtleneck-band",
    name: "Turtleneck Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Optional extended neck band designed to fold or roll for warmth and coverage.",
  },
  {
    id: "sweater-funnel-neck-outer",
    name: "Outer Funnel Neck",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Optional outer panel forming a structured funnel neckline.",
  },
  {
    id: "sweater-funnel-neck-inner",
    name: "Inner Funnel Neck",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional inner panel completing and clean-finishing a structured funnel neckline.",
  },
  {
    id: "sweater-polo-collar-upper",
    name: "Upper Polo Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 33,
    description:
      "Optional upper collar section used in knitted polo-neck or collared sweater styles.",
  },
  {
    id: "sweater-polo-collar-under",
    name: "Under Polo Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 34,
    description:
      "Optional under-collar section supporting the roll and shape of a knitted polo collar.",
  },
  {
    id: "sweater-left-neck-facing",
    name: "Left Neck Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional left neckline facing used for stable, clean finishing on structured sweater styles.",
  },
  {
    id: "sweater-right-neck-facing",
    name: "Right Neck Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional right neckline facing used for stable, clean finishing on structured sweater styles.",
  },
  {
    id: "sweater-back-neck-facing",
    name: "Back Neck Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 37,
    description:
      "Optional back neckline facing completing a faced neck opening.",
  },
  {
    id: "sweater-left-shoulder-opening-facing",
    name: "Left Shoulder Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Optional facing reinforcing and clean-finishing a left shoulder button or snap opening.",
  },
  {
    id: "sweater-right-shoulder-opening-facing",
    name: "Right Shoulder Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional facing reinforcing and clean-finishing a right shoulder button or snap opening.",
  },
  {
    id: "sweater-front-neck-placket",
    name: "Front Neck Placket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional pair of placket pieces forming a buttoned, zipped or snap-fastened neck opening.",
  },
  {
    id: "sweater-front-neck-placket-interfacing",
    name: "Front Neck Placket Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional reinforcement pieces stabilising the front neck placket and fastening positions.",
  },
  {
    id: "sweater-quarter-zip-facing-left",
    name: "Left Quarter-Zip Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional left facing finishing and stabilising one side of a quarter-zip opening.",
  },
  {
    id: "sweater-quarter-zip-facing-right",
    name: "Right Quarter-Zip Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional right facing finishing and stabilising the opposite side of a quarter-zip opening.",
  },
  {
    id: "sweater-quarter-zip-guard",
    name: "Quarter-Zip Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional internal guard positioned behind the quarter zip for comfort and clean finishing.",
  },
  {
    id: "sweater-left-cuff",
    name: "Left Sleeve Cuff",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Rib-knit, self-fabric or engineered cuff finishing the left sleeve opening.",
  },
  {
    id: "sweater-right-cuff",
    name: "Right Sleeve Cuff",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Rib-knit, self-fabric or engineered cuff finishing the right sleeve opening.",
  },
  {
    id: "sweater-left-extended-cuff",
    name: "Left Extended Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional long left cuff used for fold-back, thumb-hole or cold-weather sweater construction.",
  },
  {
    id: "sweater-right-extended-cuff",
    name: "Right Extended Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional long right cuff used for fold-back, thumb-hole or cold-weather sweater construction.",
  },
  {
    id: "sweater-left-thumbhole-cuff-insert",
    name: "Left Thumb-Hole Cuff Insert",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional shaped insert finishing and reinforcing the thumb opening in the left extended cuff.",
  },
  {
    id: "sweater-right-thumbhole-cuff-insert",
    name: "Right Thumb-Hole Cuff Insert",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional shaped insert finishing and reinforcing the thumb opening in the right extended cuff.",
  },
  {
    id: "sweater-front-hem-band",
    name: "Front Hem Band",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Front lower rib or self-fabric band finishing and controlling the sweater hem.",
  },
  {
    id: "sweater-back-hem-band",
    name: "Back Hem Band",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Back lower rib or self-fabric band finishing and controlling the sweater hem.",
  },
  {
    id: "sweater-continuous-hem-band",
    name: "Continuous Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Optional single continuous rib or knit band used instead of separate front and back hem bands.",
  },
  {
    id: "sweater-left-side-slit-facing",
    name: "Left Side Slit Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Optional pair of facing pieces reinforcing and clean-finishing the left hem side slit.",
  },
  {
    id: "sweater-right-side-slit-facing",
    name: "Right Side Slit Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Optional pair of facing pieces reinforcing and clean-finishing the right hem side slit.",
  },
  {
    id: "sweater-left-front-pocket",
    name: "Left Front Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Optional knitted or self-fabric patch pocket positioned on the left front.",
  },
  {
    id: "sweater-right-front-pocket",
    name: "Right Front Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Optional knitted or self-fabric patch pocket positioned on the right front.",
  },
  {
    id: "sweater-kangaroo-pocket",
    name: "Kangaroo Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 58,
    description:
      "Optional central front kangaroo pocket with left and right hand-entry openings.",
  },
  {
    id: "sweater-kangaroo-pocket-left-facing",
    name: "Kangaroo Pocket Left Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 59,
    description:
      "Optional facing stabilising and finishing the left hand opening of a kangaroo pocket.",
  },
  {
    id: "sweater-kangaroo-pocket-right-facing",
    name: "Kangaroo Pocket Right Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 60,
    description:
      "Optional facing stabilising and finishing the right hand opening of a kangaroo pocket.",
  },
  {
    id: "sweater-left-welt-pocket-welt",
    name: "Left Welt Pocket Welt",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 61,
    description:
      "Optional pair of welt pieces forming a structured left front pocket opening.",
  },
  {
    id: "sweater-right-welt-pocket-welt",
    name: "Right Welt Pocket Welt",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 62,
    description:
      "Optional pair of welt pieces forming a structured right front pocket opening.",
  },
  {
    id: "sweater-left-welt-pocket-bag",
    name: "Left Welt Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional pair of pocket-bag sections forming the complete left welt pocket.",
  },
  {
    id: "sweater-right-welt-pocket-bag",
    name: "Right Welt Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 64,
    description:
      "Optional pair of pocket-bag sections forming the complete right welt pocket.",
  },
  {
    id: "sweater-chest-pocket",
    name: "Chest Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 65,
    description:
      "Optional knitted or self-fabric patch pocket positioned on the chest.",
  },
  {
    id: "sweater-front-lining",
    name: "Front Body Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 66,
    description:
      "Optional front lining panel used in structured, bonded or wind-resistant sweater constructions.",
  },
  {
    id: "sweater-back-lining",
    name: "Back Body Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 67,
    description:
      "Optional back lining panel used in structured, bonded or wind-resistant sweater constructions.",
  },
  {
    id: "sweater-left-sleeve-lining",
    name: "Left Sleeve Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 68,
    description:
      "Optional left sleeve lining improving comfort and covering internal construction.",
  },
  {
    id: "sweater-right-sleeve-lining",
    name: "Right Sleeve Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 69,
    description:
      "Optional right sleeve lining improving comfort and covering internal construction.",
  },
  {
    id: "sweater-front-windproof-membrane",
    name: "Front Windproof Membrane",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 70,
    description:
      "Optional front membrane layer reducing wind penetration in technical knitted sweaters.",
  },
  {
    id: "sweater-back-windproof-membrane",
    name: "Back Windproof Membrane",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 71,
    description:
      "Optional back membrane layer reducing wind penetration in technical knitted sweaters.",
  },
  {
    id: "sweater-left-shoulder-reinforcement",
    name: "Left Shoulder Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 72,
    description:
      "Optional reinforcement panel protecting the left shoulder from abrasion, straps or repeated wear.",
  },
  {
    id: "sweater-right-shoulder-reinforcement",
    name: "Right Shoulder Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 73,
    description:
      "Optional reinforcement panel protecting the right shoulder from abrasion, straps or repeated wear.",
  },
  {
    id: "sweater-neck-tape",
    name: "Back Neck Tape",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 74,
    description:
      "Optional stabilising tape or self-fabric strip covering and reinforcing the back neckline seam.",
  },
  {
    id: "sweater-hanger-loop",
    name: "Internal Hanger Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 75,
    description:
      "Optional reinforced loop used to hang the sweater without stretching the neckline.",
  },
  {
    id: "sweater-shoulder-stay-left",
    name: "Left Shoulder Stay",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 76,
    description:
      "Optional stabilising strip preventing excessive stretch along the left shoulder seam.",
  },
  {
    id: "sweater-shoulder-stay-right",
    name: "Right Shoulder Stay",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 77,
    description:
      "Optional stabilising strip preventing excessive stretch along the right shoulder seam.",
  },
  {
    id: "sweater-front-applique-backing",
    name: "Front Appliqué Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 78,
    description:
      "Optional support patch positioned behind a front appliqué, badge, embroidery or decorative knit motif.",
  },
  {
    id: "sweater-back-decoration-backing",
    name: "Back Decoration Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 79,
    description:
      "Optional support patch positioned behind back embroidery, branding or decorative application.",
  },
  {
    id: "sweater-label-backing",
    name: "Brand Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 80,
    description:
      "Optional backing piece supporting a woven, printed, leather or heat-transfer brand label.",
  },
  {
    id: "sweater-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 81,
    description:
      "Optional backing patches supporting embroidery, badges, logos, patches or other decorative applications.",
  },
];

export default sweaterPatternMaster;