export const tankTopPatternMaster = [
  {
    id: "tank-top-front-body",
    name: "Front Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 1,
    description:
      "Main front body pattern cut on the centre-front fold, including neckline, shoulder strap, armhole, side seam and hem shaping.",
  },
  {
    id: "tank-top-back-body",
    name: "Back Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 2,
    description:
      "Main back body pattern cut on the centre-back fold, including back neckline, shoulder strap, armhole, side seam and hem shaping.",
  },
  {
    id: "tank-top-neck-binding",
    name: "Neck Binding",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Knitted binding strip used to finish and stabilise the complete neckline.",
  },
  {
    id: "tank-top-armhole-binding",
    name: "Armhole Binding",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Pair of knitted binding strips used to finish and stabilise the left and right armholes.",
  },
  {
    id: "tank-top-front-neck-facing",
    name: "Front Neck Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 5,
    description:
      "Optional front neckline facing used when the tank top has a clean-faced neckline instead of binding.",
  },
  {
    id: "tank-top-back-neck-facing",
    name: "Back Neck Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 6,
    description:
      "Optional back neckline facing paired with the front neckline facing.",
  },
  {
    id: "tank-top-front-armhole-facing-left",
    name: "Left Front Armhole Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Optional left front armhole facing used for a clean-finished armhole construction.",
  },
  {
    id: "tank-top-front-armhole-facing-right",
    name: "Right Front Armhole Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Optional right front armhole facing used for a clean-finished armhole construction.",
  },
  {
    id: "tank-top-back-armhole-facing-left",
    name: "Left Back Armhole Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional left back armhole facing joined with the corresponding front armhole facing.",
  },
  {
    id: "tank-top-back-armhole-facing-right",
    name: "Right Back Armhole Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Optional right back armhole facing joined with the corresponding front armhole facing.",
  },
  {
    id: "tank-top-racerback-body",
    name: "Racerback Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 11,
    description:
      "Optional racerback replacement for the standard back body, shaped narrowly between the shoulder blades.",
  },
  {
    id: "tank-top-y-back-panel",
    name: "Y-Back Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 12,
    description:
      "Optional Y-shaped centre-back panel used in athletic, gym and performance tank-top styles.",
  },
  {
    id: "tank-top-mesh-back-panel",
    name: "Mesh Back Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 13,
    description:
      "Optional breathable mesh panel inserted into the back body for ventilation and moisture management.",
  },
  {
    id: "tank-top-front-mesh-panel",
    name: "Front Mesh Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 14,
    description:
      "Optional front mesh or contrast-fabric panel used for ventilation, styling or colour blocking.",
  },
  {
    id: "tank-top-front-side-panel-left",
    name: "Left Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional left front side panel used for ergonomic shaping, colour blocking or sports construction.",
  },
  {
    id: "tank-top-front-side-panel-right",
    name: "Right Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional right front side panel used for ergonomic shaping, colour blocking or sports construction.",
  },
  {
    id: "tank-top-back-side-panel-left",
    name: "Left Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional left back side panel joined to the front side panel for shaped or colour-blocked construction.",
  },
  {
    id: "tank-top-back-side-panel-right",
    name: "Right Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional right back side panel joined to the front side panel for shaped or colour-blocked construction.",
  },
  {
    id: "tank-top-built-in-bra-front",
    name: "Built-In Bra Front",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 19,
    description:
      "Optional internal front support panel used in women's activewear and support tank-top styles.",
  },
  {
    id: "tank-top-built-in-bra-back",
    name: "Built-In Bra Back",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 20,
    description:
      "Optional internal back support panel joined to the built-in bra front.",
  },
  {
    id: "tank-top-underbust-band",
    name: "Underbust Support Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Optional elasticated or self-fabric support band positioned below an internal bra construction.",
  },
  {
    id: "tank-top-inner-front-lining",
    name: "Inner Front Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 22,
    description:
      "Optional inner front lining used for opacity, support, comfort or clean internal finishing.",
  },
  {
    id: "tank-top-inner-back-lining",
    name: "Inner Back Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 23,
    description:
      "Optional inner back lining used with lined fashion, sports or performance tank tops.",
  },
  {
    id: "tank-top-shoulder-strap-left",
    name: "Left Shoulder Strap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional separate left shoulder strap used when straps are not integrated into the front and back bodies.",
  },
  {
    id: "tank-top-shoulder-strap-right",
    name: "Right Shoulder Strap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional separate right shoulder strap used when straps are not integrated into the front and back bodies.",
  },
  {
    id: "tank-top-strap-loop-left",
    name: "Left Strap Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional loop used with an adjustable left shoulder strap and slider system.",
  },
  {
    id: "tank-top-strap-loop-right",
    name: "Right Strap Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional loop used with an adjustable right shoulder strap and slider system.",
  },
  {
    id: "tank-top-bottom-hem-band",
    name: "Bottom Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional self-fabric or rib-knit band used instead of a conventional turned bottom hem.",
  },
  {
    id: "tank-top-left-side-slit-facing",
    name: "Left Side Slit Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional pair of facing pieces used to clean-finish the front and back edges of the left side slit.",
  },
  {
    id: "tank-top-right-side-slit-facing",
    name: "Right Side Slit Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Optional pair of facing pieces used to clean-finish the front and back edges of the right side slit.",
  },
];

export default tankTopPatternMaster;