export const thermalTopPatternMaster = [
  {
    id: "thermal-top-front-body",
    name: "Front Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 1,
    description:
      "Main front body pattern cut on the centre-front fold including neckline, shoulder, side seam and hem shaping.",
  },
  {
    id: "thermal-top-back-body",
    name: "Back Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 2,
    description:
      "Main back body pattern cut on the centre-back fold including neckline, shoulder, side seam and hem shaping.",
  },
  {
    id: "thermal-top-left-sleeve",
    name: "Left Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Left full-length sleeve pattern shaped for thermal base-layer construction.",
  },
  {
    id: "thermal-top-right-sleeve",
    name: "Right Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Right full-length sleeve pattern shaped for thermal base-layer construction.",
  },
  {
    id: "thermal-top-neck-band",
    name: "Neck Band",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Rib or self-fabric neck band providing stretch, recovery and comfort.",
  },
  {
    id: "thermal-top-left-cuff",
    name: "Left Sleeve Cuff",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Rib or self-fabric cuff attached to the left sleeve opening.",
  },
  {
    id: "thermal-top-right-cuff",
    name: "Right Sleeve Cuff",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Rib or self-fabric cuff attached to the right sleeve opening.",
  },
  {
    id: "thermal-top-bottom-band",
    name: "Bottom Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Optional rib or self-fabric hem band replacing a folded bottom hem.",
  },
  {
    id: "thermal-top-front-yoke",
    name: "Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 9,
    description:
      "Optional front yoke used for ergonomic shaping or contrast panel construction.",
  },
  {
    id: "thermal-top-back-yoke",
    name: "Back Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 10,
    description:
      "Optional back yoke improving fit, mobility and styling.",
  },
  {
    id: "thermal-top-left-side-panel",
    name: "Left Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Optional left ergonomic side panel used in performance thermal garments.",
  },
  {
    id: "thermal-top-right-side-panel",
    name: "Right Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Optional right ergonomic side panel used in performance thermal garments.",
  },
  {
    id: "thermal-top-underarm-gusset-left",
    name: "Left Underarm Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional left underarm gusset improving arm mobility and reducing seam stress.",
  },
  {
    id: "thermal-top-underarm-gusset-right",
    name: "Right Underarm Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Optional right underarm gusset improving arm mobility and reducing seam stress.",
  },
  {
    id: "thermal-top-thumb-hole-extension-left",
    name: "Left Thumb-Hole Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional left sleeve extension incorporating a thumb-hole for cold-weather performance.",
  },
  {
    id: "thermal-top-thumb-hole-extension-right",
    name: "Right Thumb-Hole Extension",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional right sleeve extension incorporating a thumb-hole for cold-weather performance.",
  },
  {
    id: "thermal-top-quarter-zip-placket",
    name: "Quarter Zip Placket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional quarter-length front zip placket for ventilation and layering.",
  },
  {
    id: "thermal-top-zip-guard",
    name: "Zip Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Internal guard protecting the wearer from direct contact with the zip.",
  },
  {
    id: "thermal-top-chest-pocket",
    name: "Chest Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional chest pocket for lightweight storage.",
  },
  {
    id: "thermal-top-pocket-facing",
    name: "Chest Pocket Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Optional facing reinforcing and finishing the pocket opening.",
  },
  {
    id: "thermal-top-back-neck-tape",
    name: "Back Neck Reinforcement Tape",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Neck tape improving comfort, seam stability and appearance.",
  },
  {
    id: "thermal-top-flatlock-reinforcement-strip",
    name: "Flatlock Reinforcement Strip",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional reinforcement strips used in flatlock seam construction.",
  },
  {
    id: "thermal-top-reflective-panel",
    name: "Reflective Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional reflective inserts for outdoor sports and safety garments.",
  },
  {
    id: "thermal-top-inner-front-lining",
    name: "Inner Front Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 24,
    description:
      "Optional front lining providing additional warmth and comfort.",
  },
  {
    id: "thermal-top-inner-back-lining",
    name: "Inner Back Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 25,
    description:
      "Optional back lining improving insulation in cold-weather garments.",
  },
  {
    id: "thermal-top-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional reinforcement backing used behind embroidery, badges or heat-transfer graphics.",
  },
];

export default thermalTopPatternMaster;