export const tightsPatternMaster = [
  {
    id: "tights-main-body",
    name: "Main Tights Body",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Primary knitted body section forming the waist, hip, seat, crotch and upper-leg areas of standard tights.",
  },
  {
    id: "tights-front-body",
    name: "Front Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 2,
    description:
      "Optional separate front body panel covering the abdomen, front hip and front crotch areas.",
  },
  {
    id: "tights-back-body",
    name: "Back Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 3,
    description:
      "Optional separate back body panel providing seat shaping, rear rise and back-waist coverage.",
  },
  {
    id: "tights-left-front-body",
    name: "Left Front Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional anatomically shaped left front body panel used in panelled, compression or maternity tights.",
  },
  {
    id: "tights-right-front-body",
    name: "Right Front Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional anatomically shaped right front body panel used in panelled, compression or maternity tights.",
  },
  {
    id: "tights-left-back-body",
    name: "Left Back Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional anatomically shaped left back body panel providing seat contour and rear support.",
  },
  {
    id: "tights-right-back-body",
    name: "Right Back Body",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Optional anatomically shaped right back body panel providing seat contour and rear support.",
  },
  {
    id: "tights-left-leg",
    name: "Left Leg",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Main left leg section extending from the crotch through the thigh, knee, calf and ankle.",
  },
  {
    id: "tights-right-leg",
    name: "Right Leg",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Main right leg section extending from the crotch through the thigh, knee, calf and ankle.",
  },
  {
    id: "tights-left-front-leg-panel",
    name: "Left Front Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Optional front section of the left leg used for compression zoning, decoration or anatomical shaping.",
  },
  {
    id: "tights-right-front-leg-panel",
    name: "Right Front Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Optional front section of the right leg used for compression zoning, decoration or anatomical shaping.",
  },
  {
    id: "tights-left-back-leg-panel",
    name: "Left Back Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Optional rear section of the left leg supporting calf shaping, reinforcement or ventilation.",
  },
  {
    id: "tights-right-back-leg-panel",
    name: "Right Back Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional rear section of the right leg supporting calf shaping, reinforcement or ventilation.",
  },
  {
    id: "tights-left-inner-leg-panel",
    name: "Left Inner Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Optional inner left leg panel used for seam relocation, anti-chafing construction or reinforcement.",
  },
  {
    id: "tights-right-inner-leg-panel",
    name: "Right Inner Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional inner right leg panel used for seam relocation, anti-chafing construction or reinforcement.",
  },
  {
    id: "tights-left-outer-leg-panel",
    name: "Left Outer Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional outer left leg insert used for colour blocking, side support, ventilation or branding.",
  },
  {
    id: "tights-right-outer-leg-panel",
    name: "Right Outer Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional outer right leg insert used for colour blocking, side support, ventilation or branding.",
  },
  {
    id: "tights-front-crotch-panel",
    name: "Front Crotch Panel",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Shaped front crotch section providing body fit, movement and controlled seam positioning.",
  },
  {
    id: "tights-back-crotch-panel",
    name: "Back Crotch Panel",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Shaped back crotch section providing seat depth, comfort and rear rise accommodation.",
  },
  {
    id: "tights-crotch-gusset",
    name: "Crotch Gusset",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Primary gusset inserted between the legs to improve comfort, hygiene, mobility and seam strength.",
  },
  {
    id: "tights-diamond-crotch-gusset",
    name: "Diamond Crotch Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Optional diamond-shaped gusset providing additional multidirectional stretch and movement.",
  },
  {
    id: "tights-extended-crotch-gusset",
    name: "Extended Crotch Gusset",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional elongated gusset extending toward the front or back rise for comfort and support.",
  },
  {
    id: "tights-crotch-gusset-lining",
    name: "Crotch Gusset Lining",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Soft, breathable or absorbent lining layer positioned inside the crotch gusset.",
  },
  {
    id: "tights-antibacterial-gusset-lining",
    name: "Antibacterial Gusset Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional treated lining layer designed to improve hygiene and odour control.",
  },
  {
    id: "tights-front-rise-support-panel",
    name: "Front Rise Support Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 25,
    description:
      "Optional reinforced front-rise section controlling stretch and supporting the lower abdomen.",
  },
  {
    id: "tights-back-rise-support-panel",
    name: "Back Rise Support Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 26,
    description:
      "Optional reinforced back-rise section improving seat support and garment stability.",
  },
  {
    id: "tights-left-seat-panel",
    name: "Left Seat Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional shaped left seat panel providing contour, lift or reinforcement.",
  },
  {
    id: "tights-right-seat-panel",
    name: "Right Seat Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional shaped right seat panel providing contour, lift or reinforcement.",
  },
  {
    id: "tights-seat-lift-panel",
    name: "Seat Lift Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 29,
    description:
      "Optional engineered panel providing targeted shaping and support across the seat.",
  },
  {
    id: "tights-under-seat-support-panel",
    name: "Under-Seat Support Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 30,
    description:
      "Optional lower seat section providing controlled compression beneath the seat.",
  },
  {
    id: "tights-abdominal-control-panel",
    name: "Abdominal Control Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 31,
    description:
      "Optional front control panel providing targeted support and shaping across the abdomen.",
  },
  {
    id: "tights-lower-abdominal-support-panel",
    name: "Lower Abdominal Support Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 32,
    description:
      "Optional support panel concentrated over the lower abdomen and pelvis.",
  },
  {
    id: "tights-side-waist-control-panels",
    name: "Side Waist Control Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Optional left and right control panels shaping the side waist and hip areas.",
  },
  {
    id: "tights-back-waist-control-panel",
    name: "Back Waist Control Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 34,
    description:
      "Optional rear waist panel providing posture support and improved garment stability.",
  },
  {
    id: "tights-maternity-front-panel",
    name: "Maternity Front Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 35,
    description:
      "Optional high-stretch front panel shaped to accommodate abdominal growth during pregnancy.",
  },
  {
    id: "tights-maternity-under-bump-band",
    name: "Maternity Under-Bump Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional support band positioned beneath the abdomen in maternity tights.",
  },
  {
    id: "tights-maternity-back-support-panel",
    name: "Maternity Back Support Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 37,
    description:
      "Optional rear support panel providing additional lower-back stability during pregnancy.",
  },
  {
    id: "tights-waistband",
    name: "Waistband",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Primary elasticated or knitted band securing the tights around the waist.",
  },
  {
    id: "tights-wide-waistband",
    name: "Wide Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional extended-width waistband distributing pressure and improving comfort.",
  },
  {
    id: "tights-high-waistband",
    name: "High Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional deep waistband extending above the natural waist for coverage and control.",
  },
  {
    id: "tights-low-rise-waistband",
    name: "Low-Rise Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional narrow waistband designed for a low-rise body position.",
  },
  {
    id: "tights-foldover-waistband-outer",
    name: "Outer Foldover Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Optional outer section forming a folded double-layer waistband.",
  },
  {
    id: "tights-foldover-waistband-inner",
    name: "Inner Foldover Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional inner section completing and supporting a folded waistband.",
  },
  {
    id: "tights-waist-elastic-casing",
    name: "Waist Elastic Casing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional casing containing inserted waist elastic.",
  },
  {
    id: "tights-waistband-lining",
    name: "Waistband Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional soft inner waistband layer improving comfort and covering elastic.",
  },
  {
    id: "tights-non-slip-waistband",
    name: "Non-Slip Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional inner waistband panel supporting silicone grip or anti-slip application.",
  },
  {
    id: "tights-drawcord-waist-channel",
    name: "Waist Drawcord Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional casing containing a waist-adjustment drawcord.",
  },
  {
    id: "tights-drawcord-eyelet-reinforcement",
    name: "Drawcord Eyelet Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional reinforcement patches supporting waist drawcord eyelets or cord exits.",
  },
  {
    id: "tights-left-thigh-panel",
    name: "Left Thigh Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional shaped left thigh section used for support, reinforcement, ventilation or colour blocking.",
  },
  {
    id: "tights-right-thigh-panel",
    name: "Right Thigh Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional shaped right thigh section used for support, reinforcement, ventilation or colour blocking.",
  },
  {
    id: "tights-left-inner-thigh-reinforcement",
    name: "Left Inner-Thigh Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional abrasion-resistant panel protecting the left inner thigh from friction.",
  },
  {
    id: "tights-right-inner-thigh-reinforcement",
    name: "Right Inner-Thigh Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Optional abrasion-resistant panel protecting the right inner thigh from friction.",
  },
  {
    id: "tights-thigh-compression-zone",
    name: "Thigh Compression Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Optional engineered sections providing controlled compression around both thighs.",
  },
  {
    id: "tights-left-knee-panel",
    name: "Left Knee Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Optional articulated left knee section improving movement, durability or support.",
  },
  {
    id: "tights-right-knee-panel",
    name: "Right Knee Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Optional articulated right knee section improving movement, durability or support.",
  },
  {
    id: "tights-left-knee-reinforcement",
    name: "Left Knee Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Optional abrasion-resistant or padded panel protecting the left knee.",
  },
  {
    id: "tights-right-knee-reinforcement",
    name: "Right Knee Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Optional abrasion-resistant or padded panel protecting the right knee.",
  },
  {
    id: "tights-left-knee-flex-zone",
    name: "Left Knee Flex Zone",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 58,
    description:
      "Optional engineered stretch zone positioned behind or around the left knee.",
  },
  {
    id: "tights-right-knee-flex-zone",
    name: "Right Knee Flex Zone",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 59,
    description:
      "Optional engineered stretch zone positioned behind or around the right knee.",
  },
  {
    id: "tights-left-calf-panel",
    name: "Left Calf Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 60,
    description:
      "Optional shaped left calf panel providing fit control, ventilation or compression.",
  },
  {
    id: "tights-right-calf-panel",
    name: "Right Calf Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 61,
    description:
      "Optional shaped right calf panel providing fit control, ventilation or compression.",
  },
  {
    id: "tights-calf-compression-zone",
    name: "Calf Compression Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 62,
    description:
      "Optional engineered zones providing controlled compression around both calves.",
  },
  {
    id: "tights-shin-support-zone",
    name: "Shin Support Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional supportive sections positioned along the front lower legs.",
  },
  {
    id: "tights-ankle-compression-zone",
    name: "Ankle Compression Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 64,
    description:
      "Optional high-control zones providing support around both ankles.",
  },
  {
    id: "tights-graduated-compression-lower-zone",
    name: "Graduated Compression Lower Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 65,
    description:
      "Optional lower-leg sections engineered to provide the highest compression near the ankles.",
  },
  {
    id: "tights-graduated-compression-middle-zone",
    name: "Graduated Compression Middle Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 66,
    description:
      "Optional middle-leg sections providing controlled intermediate compression.",
  },
  {
    id: "tights-graduated-compression-upper-zone",
    name: "Graduated Compression Upper Zone",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 67,
    description:
      "Optional upper-leg sections providing reduced compression toward the thighs.",
  },
  {
    id: "tights-left-ankle-cuff",
    name: "Left Ankle Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 68,
    description:
      "Optional cuff finishing the left ankle opening in footless tights.",
  },
  {
    id: "tights-right-ankle-cuff",
    name: "Right Ankle Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 69,
    description:
      "Optional cuff finishing the right ankle opening in footless tights.",
  },
  {
    id: "tights-left-stirrup",
    name: "Left Stirrup",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 70,
    description:
      "Optional strap passing beneath the left foot to hold stirrup tights in position.",
  },
  {
    id: "tights-right-stirrup",
    name: "Right Stirrup",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 71,
    description:
      "Optional strap passing beneath the right foot to hold stirrup tights in position.",
  },
  {
    id: "tights-left-stirrup-reinforcement",
    name: "Left Stirrup Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 72,
    description:
      "Optional abrasion-resistant support layer protecting the left stirrup.",
  },
  {
    id: "tights-right-stirrup-reinforcement",
    name: "Right Stirrup Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 73,
    description:
      "Optional abrasion-resistant support layer protecting the right stirrup.",
  },
  {
    id: "tights-left-foot",
    name: "Left Foot",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 74,
    description:
      "Main left foot section extending from the ankle through the heel, sole, instep and toe.",
  },
  {
    id: "tights-right-foot",
    name: "Right Foot",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 75,
    description:
      "Main right foot section extending from the ankle through the heel, sole, instep and toe.",
  },
  {
    id: "tights-left-heel",
    name: "Left Heel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 76,
    description:
      "Optional separately shaped left heel section providing anatomical fit and durability.",
  },
  {
    id: "tights-right-heel",
    name: "Right Heel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 77,
    description:
      "Optional separately shaped right heel section providing anatomical fit and durability.",
  },
  {
    id: "tights-heel-reinforcement",
    name: "Heel Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 78,
    description:
      "Optional abrasion-resistant layers protecting both heel areas.",
  },
  {
    id: "tights-left-sole-panel",
    name: "Left Sole Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 79,
    description:
      "Optional separate left sole section providing cushioning, reinforcement or moisture control.",
  },
  {
    id: "tights-right-sole-panel",
    name: "Right Sole Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 80,
    description:
      "Optional separate right sole section providing cushioning, reinforcement or moisture control.",
  },
  {
    id: "tights-left-toe",
    name: "Left Toe",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 81,
    description:
      "Shaped left toe section enclosing the front of the left foot.",
  },
  {
    id: "tights-right-toe",
    name: "Right Toe",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 82,
    description:
      "Shaped right toe section enclosing the front of the right foot.",
  },
  {
    id: "tights-toe-reinforcement",
    name: "Toe Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 83,
    description:
      "Optional abrasion-resistant layers protecting both toe areas.",
  },
  {
    id: "tights-open-toe-facing",
    name: "Open-Toe Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 84,
    description:
      "Optional shaped facings finishing the toe openings of open-toe tights.",
  },
  {
    id: "tights-toe-seam-cover",
    name: "Toe Seam Cover",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 85,
    description:
      "Optional smooth inner strips covering the toe seams to reduce irritation.",
  },
  {
    id: "tights-full-foot-cushion",
    name: "Full Foot Cushion",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 86,
    description:
      "Optional cushioned sections surrounding both feet for warmth and impact absorption.",
  },
  {
    id: "tights-sole-grip-panels",
    name: "Sole Grip Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 87,
    description:
      "Optional sole panels prepared for silicone, rubber or anti-slip print application.",
  },
  {
    id: "tights-inner-leg-lining",
    name: "Inner Leg Lining",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 88,
    description:
      "Optional soft inner layers improving warmth, comfort and opacity through both legs.",
  },
  {
    id: "tights-fleece-lining",
    name: "Fleece Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 89,
    description:
      "Optional full-body fleece lining providing additional insulation in winter tights.",
  },
  {
    id: "tights-thermal-body-lining",
    name: "Thermal Body Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 90,
    description:
      "Optional insulating lining covering the waist, hip and seat sections.",
  },
  {
    id: "tights-thermal-leg-lining",
    name: "Thermal Leg Linings",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 91,
    description:
      "Optional insulating inner layers extending through both legs.",
  },
  {
    id: "tights-windproof-front-panel",
    name: "Windproof Front Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 92,
    description:
      "Optional membrane-backed front body panel reducing wind penetration.",
  },
  {
    id: "tights-windproof-thigh-panels",
    name: "Windproof Thigh Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 93,
    description:
      "Optional membrane-backed front-thigh panels providing weather protection.",
  },
  {
    id: "tights-windproof-knee-panels",
    name: "Windproof Knee Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 94,
    description:
      "Optional protective panels reducing wind exposure across both knees.",
  },
  {
    id: "tights-mesh-ventilation-panels",
    name: "Mesh Ventilation Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 95,
    description:
      "Optional breathable panels positioned behind the knees, along the calves or at the side legs.",
  },
  {
    id: "tights-perforated-crotch-panel",
    name: "Perforated Crotch Ventilation Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 96,
    description:
      "Optional breathable panel improving ventilation and moisture management in the crotch area.",
  },
  {
    id: "tights-reflective-left-leg-panel",
    name: "Left Reflective Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 97,
    description:
      "Optional reflective or high-visibility panel positioned on the left leg.",
  },
  {
    id: "tights-reflective-right-leg-panel",
    name: "Right Reflective Leg Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 98,
    description:
      "Optional reflective or high-visibility panel positioned on the right leg.",
  },
  {
    id: "tights-left-side-pocket",
    name: "Left Side Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 99,
    description:
      "Optional stretch pocket positioned on the outer left thigh for a phone, card or small item.",
  },
  {
    id: "tights-right-side-pocket",
    name: "Right Side Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 100,
    description:
      "Optional stretch pocket positioned on the outer right thigh for a phone, card or small item.",
  },
  {
    id: "tights-left-pocket-facing",
    name: "Left Pocket Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 101,
    description:
      "Optional facing stabilising and finishing the left side-pocket opening.",
  },
  {
    id: "tights-right-pocket-facing",
    name: "Right Pocket Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 102,
    description:
      "Optional facing stabilising and finishing the right side-pocket opening.",
  },
  {
    id: "tights-back-waist-pocket",
    name: "Back Waist Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 103,
    description:
      "Optional concealed pocket integrated into the back waistband.",
  },
  {
    id: "tights-back-pocket-facing",
    name: "Back Waist Pocket Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 104,
    description:
      "Optional facing reinforcing and clean-finishing the back waistband pocket opening.",
  },
  {
    id: "tights-sensor-pocket",
    name: "Sensor Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 105,
    description:
      "Optional pocket supporting a fitness, medical or performance-monitoring sensor.",
  },
  {
    id: "tights-sensor-pocket-facing",
    name: "Sensor Pocket Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 106,
    description:
      "Optional facing stabilising and clean-finishing the sensor pocket opening.",
  },
  {
    id: "tights-front-seam-cover",
    name: "Front Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 107,
    description:
      "Optional internal strip covering a centre-front body seam.",
  },
  {
    id: "tights-back-seam-cover",
    name: "Back Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 108,
    description:
      "Optional internal strip covering a centre-back body seam.",
  },
  {
    id: "tights-inner-leg-seam-covers",
    name: "Inner Leg Seam Covers",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 109,
    description:
      "Optional smooth strips covering both inner-leg seams to reduce friction.",
  },
  {
    id: "tights-gusset-seam-cover",
    name: "Gusset Seam Cover",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 110,
    description:
      "Optional soft strip covering the gusset attachment seam for improved comfort.",
  },
  {
    id: "tights-logo-backing",
    name: "Logo Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 111,
    description:
      "Optional internal support patch positioned behind branding, embroidery or heat-transfer decoration.",
  },
  {
    id: "tights-waist-label-backing",
    name: "Waist Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 112,
    description:
      "Optional support piece for size, brand, care or fibre-content labels at the waistband.",
  },
  {
    id: "tights-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 113,
    description:
      "Optional backing patches supporting appliqué, reflective transfer, logos or decorative applications.",
  },
];

export default tightsPatternMaster;