import { PatternLibraryItem } from "./index";

export const tshirtPatternMaster: PatternLibraryItem[] = [
  {
    id: "tshirt-front",
    name: "T-Shirt Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 1,
    description:
      "Main front body panel extending from the neckline and shoulders to the lower hem.",
  },
  {
    id: "tshirt-back",
    name: "T-Shirt Back",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 2,
    description:
      "Main back body panel extending from the back neckline and shoulders to the lower hem.",
  },
  {
    id: "tshirt-sleeve",
    name: "Short Sleeve",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 3,
    description:
      "Standard left and right short sleeves attached to the front and back armholes.",
  },
  {
    id: "tshirt-neck-rib",
    name: "Neck Rib",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Knitted rib strip used to finish and stabilise the neckline opening.",
  },
  {
    id: "tshirt-back-neck-binding",
    name: "Back Neck Binding",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Binding strip used to cover and reinforce the internal back neckline seam.",
  },
  {
    id: "tshirt-shoulder-tape",
    name: "Shoulder Reinforcement Tape",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Reinforcement tape applied along both shoulder seams to reduce stretching.",
  },
  {
    id: "tshirt-long-sleeve",
    name: "Long Sleeve",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Optional full-length sleeve components used for long-sleeve T-shirt styles.",
  },
  {
    id: "tshirt-raglan-sleeve-front",
    name: "Raglan Sleeve Front",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Front section of an optional raglan sleeve construction extending into the neckline.",
  },
  {
    id: "tshirt-raglan-sleeve-back",
    name: "Raglan Sleeve Back",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Back section of an optional raglan sleeve construction extending into the neckline.",
  },
  {
    id: "tshirt-sleeve-cuff",
    name: "Sleeve Rib Cuff",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Optional rib cuffs attached to sleeve openings for sportswear or long-sleeve styles.",
  },
  {
    id: "tshirt-bottom-rib-band",
    name: "Bottom Rib Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Optional rib band attached around the lower body opening.",
  },
  {
    id: "tshirt-bottom-hem-facing",
    name: "Bottom Hem Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Facing component used to reinforce and finish the lower hem.",
  },
  {
    id: "tshirt-sleeve-hem-facing",
    name: "Sleeve Hem Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional facing components used to finish the left and right sleeve openings.",
  },
  {
    id: "tshirt-side-slit-facing-left",
    name: "Left Side Slit Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Facing component reinforcing and finishing the left side slit opening.",
  },
  {
    id: "tshirt-side-slit-facing-right",
    name: "Right Side Slit Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Facing component reinforcing and finishing the right side slit opening.",
  },
  {
    id: "tshirt-chest-pocket",
    name: "Chest Patch Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional patch pocket positioned on the left or right chest.",
  },
  {
    id: "tshirt-chest-pocket-facing",
    name: "Chest Pocket Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Facing or reinforcement component used to finish the chest pocket opening.",
  },
  {
    id: "tshirt-front-yoke",
    name: "Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 18,
    description:
      "Optional upper front panel used for styling, colour blocking or reinforcement.",
  },
  {
    id: "tshirt-back-yoke",
    name: "Back Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 19,
    description:
      "Optional upper back panel used for styling, colour blocking or reinforcement.",
  },
  {
    id: "tshirt-side-panel-left",
    name: "Left Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Optional left body side panel used for shaping, sports styling or colour blocking.",
  },
  {
    id: "tshirt-side-panel-right",
    name: "Right Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Optional right body side panel used for shaping, sports styling or colour blocking.",
  },
  {
    id: "tshirt-underarm-panel-left",
    name: "Left Underarm Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional ventilation or contrast panel positioned below the left armhole.",
  },
  {
    id: "tshirt-underarm-panel-right",
    name: "Right Underarm Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional ventilation or contrast panel positioned below the right armhole.",
  },
  {
    id: "tshirt-placket",
    name: "Neck Placket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional left and right placket components used for buttoned or snap-neck T-shirt styles.",
  },
  {
    id: "tshirt-placket-underlay",
    name: "Placket Underlay",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Internal underlay component supporting an optional neckline placket.",
  },
  {
    id: "tshirt-v-neck-binding-left",
    name: "Left V-Neck Binding",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Left binding component used for an optional V-neck construction.",
  },
  {
    id: "tshirt-v-neck-binding-right",
    name: "Right V-Neck Binding",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Right binding component joined with the left binding at the V-neck point.",
  },
  {
    id: "tshirt-neckline-reinforcement-patch",
    name: "Neckline Reinforcement Patch",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 28,
    description:
      "Internal reinforcement patch supporting the back neckline and label area.",
  },
  {
    id: "tshirt-brand-label-guide",
    name: "Brand Label Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Reference guide identifying the approved position for the main brand label.",
  },
  {
    id: "tshirt-care-label-guide",
    name: "Care Label Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Reference guide identifying the approved position for the garment care label.",
  },
  {
    id: "tshirt-size-label-guide",
    name: "Size Label Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Reference guide identifying the standard position for the garment size label.",
  },
  {
    id: "tshirt-chest-print-guide",
    name: "Chest Print Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Reference guide controlling embroidery, screen print or heat-transfer placement on the chest.",
  },
  {
    id: "tshirt-centre-front-print-guide",
    name: "Centre Front Print Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Reference guide controlling artwork placement at the centre front body.",
  },
  {
    id: "tshirt-back-print-guide",
    name: "Back Print Placement Guide",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Reference guide controlling embroidery, screen print or heat-transfer placement on the back body.",
  },
  {
    id: "tshirt-sleeve-print-guide",
    name: "Sleeve Print Placement Guide",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Reference guides controlling logo, print or transfer placement on both sleeves.",
  },
];