export const waistcoatPatternMaster = [
  {
    id: "waistcoat-left-front",
    name: "Left Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Main left front outer-shell pattern including neckline, shoulder, armhole, centre-front opening, side seam and hem shaping.",
  },
  {
    id: "waistcoat-right-front",
    name: "Right Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Main right front outer-shell pattern including neckline, shoulder, armhole, centre-front opening, side seam and hem shaping.",
  },
  {
    id: "waistcoat-back",
    name: "Back",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 3,
    description:
      "Main back pattern cut on the centre-back fold, including neckline, shoulder, armhole, side seam and lower-back shaping.",
  },
  {
    id: "waistcoat-left-front-facing",
    name: "Left Front Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Left front facing used to clean-finish the centre-front opening, neckline and front hem area.",
  },
  {
    id: "waistcoat-right-front-facing",
    name: "Right Front Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Right front facing used to clean-finish the centre-front opening, neckline and front hem area.",
  },
  {
    id: "waistcoat-back-neck-facing",
    name: "Back Neck Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 6,
    description:
      "Back neckline facing joined to the front facings for a clean internal neckline finish.",
  },
  {
    id: "waistcoat-left-front-lining",
    name: "Left Front Lining",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Left front lining pattern shaped to fit inside the waistcoat shell.",
  },
  {
    id: "waistcoat-right-front-lining",
    name: "Right Front Lining",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Right front lining pattern shaped to fit inside the waistcoat shell.",
  },
  {
    id: "waistcoat-back-lining",
    name: "Back Lining",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 9,
    description:
      "Back lining pattern cut on the fold and joined to the front lining pieces.",
  },
  {
    id: "waistcoat-left-armhole-facing",
    name: "Left Armhole Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Optional pair of shaped front and back facing sections used to clean-finish the left armhole.",
  },
  {
    id: "waistcoat-right-armhole-facing",
    name: "Right Armhole Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Optional pair of shaped front and back facing sections used to clean-finish the right armhole.",
  },
  {
    id: "waistcoat-left-chest-welt",
    name: "Left Chest Pocket Welt",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 12,
    description:
      "Optional left chest welt piece for a formal breast pocket construction.",
  },
  {
    id: "waistcoat-left-chest-pocket-bag",
    name: "Left Chest Pocket Bag",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional pocket bag positioned behind the left chest welt opening.",
  },
  {
    id: "waistcoat-left-lower-welt",
    name: "Left Lower Pocket Welt",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Optional pair of welt pieces forming the left lower pocket opening.",
  },
  {
    id: "waistcoat-right-lower-welt",
    name: "Right Lower Pocket Welt",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional pair of welt pieces forming the right lower pocket opening.",
  },
  {
    id: "waistcoat-left-lower-pocket-bag",
    name: "Left Lower Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional pair of upper and lower pocket-bag sections for the left lower pocket.",
  },
  {
    id: "waistcoat-right-lower-pocket-bag",
    name: "Right Lower Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional pair of upper and lower pocket-bag sections for the right lower pocket.",
  },
  {
    id: "waistcoat-left-lower-pocket-flap",
    name: "Left Lower Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional upper and under flap pieces for the left lower pocket.",
  },
  {
    id: "waistcoat-right-lower-pocket-flap",
    name: "Right Lower Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional upper and under flap pieces for the right lower pocket.",
  },
  {
    id: "waistcoat-left-front-interfacing",
    name: "Left Front Interfacing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Left fusible or non-fusible reinforcement supporting the front edge, neckline, button area and lower front.",
  },
  {
    id: "waistcoat-right-front-interfacing",
    name: "Right Front Interfacing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Right fusible or non-fusible reinforcement supporting the front edge, neckline, button area and lower front.",
  },
  {
    id: "waistcoat-left-pocket-reinforcement",
    name: "Left Pocket Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Optional reinforcement pieces placed behind left chest and lower pocket openings.",
  },
  {
    id: "waistcoat-right-pocket-reinforcement",
    name: "Right Pocket Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional reinforcement piece placed behind the right lower pocket opening.",
  },
  {
    id: "waistcoat-back-waist-strap-left",
    name: "Left Back Waist Strap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional left back adjustment strap used with a buckle or slider.",
  },
  {
    id: "waistcoat-back-waist-strap-right",
    name: "Right Back Waist Strap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional right back adjustment strap used with a buckle or button fastening.",
  },
  {
    id: "waistcoat-back-belt",
    name: "One-Piece Back Belt",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional one-piece back belt replacing the two-part waist-strap construction.",
  },
  {
    id: "waistcoat-back-buckle-guard",
    name: "Back Buckle Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional fabric guard positioned behind the adjustment buckle for wearer comfort.",
  },
  {
    id: "waistcoat-front-button-stand-reinforcement",
    name: "Front Button Stand Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Optional reinforcement strips placed behind the button and buttonhole positions.",
  },
  {
    id: "waistcoat-collar",
    name: "Collar",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 29,
    description:
      "Optional upper and under collar pieces for a collared waistcoat style.",
  },
  {
    id: "waistcoat-collar-stand",
    name: "Collar Stand",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 30,
    description:
      "Optional inner and outer collar-stand pieces supporting a separate collar.",
  },
  {
    id: "waistcoat-shawl-collar-left",
    name: "Left Shawl Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 31,
    description:
      "Optional left shawl-collar section used in formal or evening waistcoat styles.",
  },
  {
    id: "waistcoat-shawl-collar-right",
    name: "Right Shawl Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional right shawl-collar section used in formal or evening waistcoat styles.",
  },
];

export default waistcoatPatternMaster;