export const waterproofJacketPatternMaster = [
  {
    id: "waterproof-jacket-left-front",
    name: "Left Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Main left front waterproof shell panel including shoulder, armhole, side seam, centre-front opening and hem shaping.",
  },
  {
    id: "waterproof-jacket-right-front",
    name: "Right Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Main right front waterproof shell panel including shoulder, armhole, side seam, centre-front opening and hem shaping.",
  },
  {
    id: "waterproof-jacket-back",
    name: "Back",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 3,
    description:
      "Main back waterproof shell panel cut on the centre-back fold with shoulder, armhole, side seam and hem shaping.",
  },
  {
    id: "waterproof-jacket-left-front-side-panel",
    name: "Left Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional shaped left front side panel used for ergonomic fit, seam positioning or colour blocking.",
  },
  {
    id: "waterproof-jacket-right-front-side-panel",
    name: "Right Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional shaped right front side panel used for ergonomic fit, seam positioning or colour blocking.",
  },
  {
    id: "waterproof-jacket-left-back-side-panel",
    name: "Left Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional shaped left back panel improving movement, body contour and functional seam placement.",
  },
  {
    id: "waterproof-jacket-right-back-side-panel",
    name: "Right Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Optional shaped right back panel improving movement, body contour and functional seam placement.",
  },
  {
    id: "waterproof-jacket-front-yoke-left",
    name: "Left Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Optional upper left front yoke used for reinforcement, seam relocation or contrast construction.",
  },
  {
    id: "waterproof-jacket-front-yoke-right",
    name: "Right Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional upper right front yoke used for reinforcement, seam relocation or contrast construction.",
  },
  {
    id: "waterproof-jacket-back-yoke",
    name: "Back Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 10,
    description:
      "Optional upper back yoke supporting shoulder structure, ventilation or reinforced weather protection.",
  },
  {
    id: "waterproof-jacket-back-vent-cape",
    name: "Back Vent Cape",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 11,
    description:
      "Optional floating back cape shielding a ventilation opening while reducing rain penetration.",
  },
  {
    id: "waterproof-jacket-back-vent-mesh",
    name: "Back Vent Mesh",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 12,
    description:
      "Optional breathable mesh panel positioned beneath the back vent cape.",
  },
  {
    id: "waterproof-jacket-left-upper-sleeve",
    name: "Left Upper Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Main left upper sleeve panel shaped for shoulder fit, articulation and waterproof coverage.",
  },
  {
    id: "waterproof-jacket-right-upper-sleeve",
    name: "Right Upper Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Main right upper sleeve panel shaped for shoulder fit, articulation and waterproof coverage.",
  },
  {
    id: "waterproof-jacket-left-under-sleeve",
    name: "Left Under Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Left under-sleeve panel completing the two-piece sleeve and supporting ergonomic arm movement.",
  },
  {
    id: "waterproof-jacket-right-under-sleeve",
    name: "Right Under Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Right under-sleeve panel completing the two-piece sleeve and supporting ergonomic arm movement.",
  },
  {
    id: "waterproof-jacket-left-elbow-panel",
    name: "Left Articulated Elbow Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional shaped left elbow panel improving articulation and reducing sleeve restriction.",
  },
  {
    id: "waterproof-jacket-right-elbow-panel",
    name: "Right Articulated Elbow Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional shaped right elbow panel improving articulation and reducing sleeve restriction.",
  },
  {
    id: "waterproof-jacket-left-sleeve-lining",
    name: "Left Sleeve Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional left sleeve lining providing comfort, smooth dressing and internal seam coverage.",
  },
  {
    id: "waterproof-jacket-right-sleeve-lining",
    name: "Right Sleeve Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Optional right sleeve lining providing comfort, smooth dressing and internal seam coverage.",
  },
  {
    id: "waterproof-jacket-left-front-facing",
    name: "Left Front Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Left front facing finishing and stabilising the centre-front zip, neckline and lower opening.",
  },
  {
    id: "waterproof-jacket-right-front-facing",
    name: "Right Front Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Right front facing finishing and stabilising the centre-front zip, neckline and lower opening.",
  },
  {
    id: "waterproof-jacket-front-facing-interfacing",
    name: "Front Facing Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional reinforcement supporting both front facings and the centre-front fastening system.",
  },
  {
    id: "waterproof-jacket-outer-storm-flap",
    name: "Outer Storm Flap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional outer flap covering the centre-front zip to reduce direct wind and water penetration.",
  },
  {
    id: "waterproof-jacket-inner-storm-flap",
    name: "Inner Storm Flap",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Internal storm flap positioned behind the centre-front zip to reduce wind and water entry.",
  },
  {
    id: "waterproof-jacket-storm-flap-interfacing",
    name: "Storm Flap Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional reinforcement supporting the shape and fastening positions of the outer storm flap.",
  },
  {
    id: "waterproof-jacket-zip-guard",
    name: "Zip Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional protective guard preventing the centre-front zip from contacting the wearer.",
  },
  {
    id: "waterproof-jacket-chin-guard",
    name: "Chin Guard",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 28,
    description:
      "Pair of shell or padded pieces protecting the chin from the zip slider and top fastening.",
  },
  {
    id: "waterproof-jacket-collar-outer",
    name: "Outer Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 29,
    description:
      "Optional outer collar panel providing structured neck coverage and weather protection.",
  },
  {
    id: "waterproof-jacket-collar-inner",
    name: "Inner Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 30,
    description:
      "Optional inner collar panel completing and clean-finishing the collar construction.",
  },
  {
    id: "waterproof-jacket-collar-interfacing",
    name: "Collar Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 31,
    description:
      "Optional reinforcement stabilising the collar and maintaining shape during repeated wear.",
  },
  {
    id: "waterproof-jacket-hood-centre-panel",
    name: "Hood Centre Panel",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Central hood panel extending over the crown from the front opening to the back neckline.",
  },
  {
    id: "waterproof-jacket-left-hood-side",
    name: "Left Hood Side",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Left hood side panel shaped around the face, crown and neckline.",
  },
  {
    id: "waterproof-jacket-right-hood-side",
    name: "Right Hood Side",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Right hood side panel shaped around the face, crown and neckline.",
  },
  {
    id: "waterproof-jacket-hood-peak-upper",
    name: "Upper Hood Peak",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional upper hood-peak panel projecting over the face to reduce direct rainfall.",
  },
  {
    id: "waterproof-jacket-hood-peak-under",
    name: "Under Hood Peak",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional lower hood-peak panel completing the peak construction.",
  },
  {
    id: "waterproof-jacket-hood-peak-reinforcement",
    name: "Hood Peak Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Optional stiffening insert maintaining the shape and projection of the hood peak.",
  },
  {
    id: "waterproof-jacket-hood-facing",
    name: "Hood Opening Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Facing used to clean-finish and stabilise the hood opening around the face.",
  },
  {
    id: "waterproof-jacket-hood-lining-centre",
    name: "Hood Lining Centre Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional central hood lining panel improving comfort and covering internal hood seams.",
  },
  {
    id: "waterproof-jacket-left-hood-lining",
    name: "Left Hood Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional left hood lining side panel shaped to match the outer hood.",
  },
  {
    id: "waterproof-jacket-right-hood-lining",
    name: "Right Hood Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Optional right hood lining side panel shaped to match the outer hood.",
  },
  {
    id: "waterproof-jacket-hood-neck-guard",
    name: "Hood Neck Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 42,
    description:
      "Optional internal guard covering the hood-to-neck seam and improving wearer comfort.",
  },
  {
    id: "waterproof-jacket-hood-cord-channel",
    name: "Hood Drawcord Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Optional casing strip containing the hood adjustment drawcord.",
  },
  {
    id: "waterproof-jacket-hood-eyelet-reinforcement",
    name: "Hood Eyelet Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Optional reinforcement patches positioned behind the hood drawcord eyelets or exits.",
  },
  {
    id: "waterproof-jacket-left-pocket-welt",
    name: "Left Pocket Welt",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Pair of welt pieces forming and protecting the left waterproof pocket opening.",
  },
  {
    id: "waterproof-jacket-right-pocket-welt",
    name: "Right Pocket Welt",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Pair of welt pieces forming and protecting the right waterproof pocket opening.",
  },
  {
    id: "waterproof-jacket-left-pocket-bag",
    name: "Left Pocket Bag",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Pair of pocket-bag sections forming the complete left hand pocket.",
  },
  {
    id: "waterproof-jacket-right-pocket-bag",
    name: "Right Pocket Bag",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Pair of pocket-bag sections forming the complete right hand pocket.",
  },
  {
    id: "waterproof-jacket-left-pocket-flap",
    name: "Left Pocket Storm Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional upper and under flap pieces shielding the left pocket opening from rain.",
  },
  {
    id: "waterproof-jacket-right-pocket-flap",
    name: "Right Pocket Storm Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional upper and under flap pieces shielding the right pocket opening from rain.",
  },
  {
    id: "waterproof-jacket-left-chest-pocket-bag",
    name: "Left Chest Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional pair of pocket-bag sections forming a waterproof left chest pocket.",
  },
  {
    id: "waterproof-jacket-right-chest-pocket-bag",
    name: "Right Chest Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Optional pair of pocket-bag sections forming a waterproof right chest pocket.",
  },
  {
    id: "waterproof-jacket-left-chest-pocket-welt",
    name: "Left Chest Pocket Welt",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Optional welt pieces forming and protecting the left chest pocket opening.",
  },
  {
    id: "waterproof-jacket-right-chest-pocket-welt",
    name: "Right Chest Pocket Welt",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Optional welt pieces forming and protecting the right chest pocket opening.",
  },
  {
    id: "waterproof-jacket-pocket-drainage-patch",
    name: "Pocket Drainage Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Optional mesh or reinforced drainage pieces allowing trapped water to escape from external pockets.",
  },
  {
    id: "waterproof-jacket-left-cuff-tab",
    name: "Left Cuff Adjustment Tab",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Upper and under tab pieces used to adjust and secure the left sleeve opening.",
  },
  {
    id: "waterproof-jacket-right-cuff-tab",
    name: "Right Cuff Adjustment Tab",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Upper and under tab pieces used to adjust and secure the right sleeve opening.",
  },
  {
    id: "waterproof-jacket-cuff-tab-reinforcement",
    name: "Cuff Tab Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 58,
    description:
      "Optional reinforcement pieces supporting hook-and-loop, snap or buckle attachment on both cuff tabs.",
  },
  {
    id: "waterproof-jacket-left-inner-cuff",
    name: "Left Inner Storm Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 59,
    description:
      "Optional elasticated or stretch inner cuff reducing wind and water entry at the left wrist.",
  },
  {
    id: "waterproof-jacket-right-inner-cuff",
    name: "Right Inner Storm Cuff",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 60,
    description:
      "Optional elasticated or stretch inner cuff reducing wind and water entry at the right wrist.",
  },
  {
    id: "waterproof-jacket-underarm-vent-left",
    name: "Left Underarm Vent Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 61,
    description:
      "Optional breathable or mesh panel supporting ventilation beneath the left arm.",
  },
  {
    id: "waterproof-jacket-underarm-vent-right",
    name: "Right Underarm Vent Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 62,
    description:
      "Optional breathable or mesh panel supporting ventilation beneath the right arm.",
  },
  {
    id: "waterproof-jacket-left-pit-zip-guard",
    name: "Left Pit-Zip Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional protective guard positioned behind the left underarm ventilation zip.",
  },
  {
    id: "waterproof-jacket-right-pit-zip-guard",
    name: "Right Pit-Zip Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 64,
    description:
      "Optional protective guard positioned behind the right underarm ventilation zip.",
  },
  {
    id: "waterproof-jacket-hem-drawcord-channel",
    name: "Hem Drawcord Channel",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 65,
    description:
      "Lower-edge casing containing the hem drawcord for fit adjustment and wind protection.",
  },
  {
    id: "waterproof-jacket-hem-eyelet-reinforcement",
    name: "Hem Eyelet Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 66,
    description:
      "Optional reinforcement patches supporting hem drawcord eyelets or cord-lock exits.",
  },
  {
    id: "waterproof-jacket-left-front-lining",
    name: "Left Front Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 67,
    description:
      "Optional left front lining panel providing comfort and clean internal finishing.",
  },
  {
    id: "waterproof-jacket-right-front-lining",
    name: "Right Front Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 68,
    description:
      "Optional right front lining panel providing comfort and clean internal finishing.",
  },
  {
    id: "waterproof-jacket-back-lining",
    name: "Back Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 69,
    description:
      "Optional back lining panel covering internal seams and improving wearer comfort.",
  },
  {
    id: "waterproof-jacket-left-mesh-lining",
    name: "Left Front Mesh Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 70,
    description:
      "Optional breathable left front mesh lining used in lightweight waterproof jackets.",
  },
  {
    id: "waterproof-jacket-right-mesh-lining",
    name: "Right Front Mesh Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 71,
    description:
      "Optional breathable right front mesh lining used in lightweight waterproof jackets.",
  },
  {
    id: "waterproof-jacket-back-mesh-lining",
    name: "Back Mesh Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 72,
    description:
      "Optional breathable back mesh lining improving airflow and moisture management.",
  },
  {
    id: "waterproof-jacket-left-shoulder-reinforcement",
    name: "Left Shoulder Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 73,
    description:
      "Optional abrasion-resistant panel protecting the left shoulder from backpack straps or heavy use.",
  },
  {
    id: "waterproof-jacket-right-shoulder-reinforcement",
    name: "Right Shoulder Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 74,
    description:
      "Optional abrasion-resistant panel protecting the right shoulder from backpack straps or heavy use.",
  },
  {
    id: "waterproof-jacket-left-elbow-reinforcement",
    name: "Left Elbow Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 75,
    description:
      "Optional abrasion-resistant reinforcement protecting the left elbow.",
  },
  {
    id: "waterproof-jacket-right-elbow-reinforcement",
    name: "Right Elbow Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 76,
    description:
      "Optional abrasion-resistant reinforcement protecting the right elbow.",
  },
  {
    id: "waterproof-jacket-reflective-back-panel",
    name: "Reflective Back Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 77,
    description:
      "Optional reflective back panel improving wearer visibility in low-light conditions.",
  },
  {
    id: "waterproof-jacket-reflective-sleeve-panels",
    name: "Reflective Sleeve Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 78,
    description:
      "Optional reflective sleeve panels improving side visibility and safety.",
  },
  {
    id: "waterproof-jacket-seam-reinforcement-strip",
    name: "Waterproof Seam Reinforcement Strip",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 79,
    description:
      "Optional shell reinforcement strip positioned beneath highly stressed seams before seam sealing.",
  },
  {
    id: "waterproof-jacket-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 80,
    description:
      "Optional backing patches supporting logos, embroidery, badges, identification marks or reflective transfers.",
  },
];

export default waterproofJacketPatternMaster;