export const windbreakerPatternMaster = [
  {
    id: "windbreaker-left-front",
    name: "Left Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 1,
    description:
      "Main left front windbreaker shell panel including shoulder, armhole, side seam, centre-front opening and hem shaping.",
  },
  {
    id: "windbreaker-right-front",
    name: "Right Front",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Main right front windbreaker shell panel including shoulder, armhole, side seam, centre-front opening and hem shaping.",
  },
  {
    id: "windbreaker-back",
    name: "Back",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 3,
    description:
      "Main back windbreaker shell panel cut on the centre-back fold with shoulder, armhole, side seam and hem shaping.",
  },
  {
    id: "windbreaker-left-front-side-panel",
    name: "Left Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Optional shaped left front side panel used for fit control, seam positioning or colour-block construction.",
  },
  {
    id: "windbreaker-right-front-side-panel",
    name: "Right Front Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional shaped right front side panel used for fit control, seam positioning or colour-block construction.",
  },
  {
    id: "windbreaker-left-back-side-panel",
    name: "Left Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional shaped left back side panel improving body contour, movement and functional seam placement.",
  },
  {
    id: "windbreaker-right-back-side-panel",
    name: "Right Back Side Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Optional shaped right back side panel improving body contour, movement and functional seam placement.",
  },
  {
    id: "windbreaker-left-front-yoke",
    name: "Left Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Optional upper left front yoke used for styling, reinforcement or contrast-fabric construction.",
  },
  {
    id: "windbreaker-right-front-yoke",
    name: "Right Front Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 9,
    description:
      "Optional upper right front yoke used for styling, reinforcement or contrast-fabric construction.",
  },
  {
    id: "windbreaker-back-yoke",
    name: "Back Yoke",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 10,
    description:
      "Optional upper back yoke supporting shoulder shaping, ventilation or contrast construction.",
  },
  {
    id: "windbreaker-back-vent-cape",
    name: "Back Vent Cape",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 11,
    description:
      "Optional floating back cape covering a ventilation opening while reducing wind and light-rain entry.",
  },
  {
    id: "windbreaker-back-vent-mesh",
    name: "Back Vent Mesh",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 12,
    description:
      "Optional breathable mesh panel positioned beneath the back vent cape.",
  },
  {
    id: "windbreaker-left-raglan-sleeve",
    name: "Left Raglan Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional one-piece left raglan sleeve extending into the neckline for athletic movement and simplified construction.",
  },
  {
    id: "windbreaker-right-raglan-sleeve",
    name: "Right Raglan Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Optional one-piece right raglan sleeve extending into the neckline for athletic movement and simplified construction.",
  },
  {
    id: "windbreaker-left-upper-sleeve",
    name: "Left Upper Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Main left upper sleeve panel shaped for shoulder fit, elbow movement and lightweight outerwear construction.",
  },
  {
    id: "windbreaker-right-upper-sleeve",
    name: "Right Upper Sleeve",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Main right upper sleeve panel shaped for shoulder fit, elbow movement and lightweight outerwear construction.",
  },
  {
    id: "windbreaker-left-under-sleeve",
    name: "Left Under Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Optional left under-sleeve panel completing a two-piece sleeve and improving ergonomic movement.",
  },
  {
    id: "windbreaker-right-under-sleeve",
    name: "Right Under Sleeve",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional right under-sleeve panel completing a two-piece sleeve and improving ergonomic movement.",
  },
  {
    id: "windbreaker-left-sleeve-insert",
    name: "Left Sleeve Contrast Insert",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 19,
    description:
      "Optional contrast or reflective insert positioned along the left sleeve.",
  },
  {
    id: "windbreaker-right-sleeve-insert",
    name: "Right Sleeve Contrast Insert",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Optional contrast or reflective insert positioned along the right sleeve.",
  },
  {
    id: "windbreaker-left-front-facing",
    name: "Left Front Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 21,
    description:
      "Left front facing finishing and stabilising the centre-front zip, neckline and lower opening.",
  },
  {
    id: "windbreaker-right-front-facing",
    name: "Right Front Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Right front facing finishing and stabilising the centre-front zip, neckline and lower opening.",
  },
  {
    id: "windbreaker-front-facing-interfacing",
    name: "Front Facing Interfacing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional reinforcement pieces supporting both front facings and the centre-front fastening.",
  },
  {
    id: "windbreaker-inner-storm-flap",
    name: "Inner Storm Flap",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Internal flap positioned behind the centre-front zip to reduce wind penetration.",
  },
  {
    id: "windbreaker-outer-storm-flap",
    name: "Outer Storm Flap",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Optional outer flap covering the centre-front zip for additional wind and light-rain protection.",
  },
  {
    id: "windbreaker-zip-guard",
    name: "Zip Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional internal guard protecting the wearer from the centre-front zip.",
  },
  {
    id: "windbreaker-chin-guard",
    name: "Chin Guard",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 27,
    description:
      "Optional pair of shell, fleece or padded pieces protecting the chin from the zip slider.",
  },
  {
    id: "windbreaker-stand-collar-outer",
    name: "Outer Stand Collar",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 28,
    description:
      "Outer stand-collar section providing neck coverage and wind protection.",
  },
  {
    id: "windbreaker-stand-collar-inner",
    name: "Inner Stand Collar",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 29,
    description:
      "Inner stand-collar section clean-finishing the neckline and supporting collar structure.",
  },
  {
    id: "windbreaker-collar-interfacing",
    name: "Collar Interfacing",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 30,
    description:
      "Optional reinforcement maintaining the stand collar shape during repeated wear.",
  },
  {
    id: "windbreaker-inner-fleece-collar",
    name: "Inner Fleece Collar",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 31,
    description:
      "Optional fleece or brushed-tricot inner collar improving comfort and light warmth.",
  },
  {
    id: "windbreaker-hood-centre-panel",
    name: "Hood Centre Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 32,
    description:
      "Optional central hood panel extending over the crown from the face opening to the back neckline.",
  },
  {
    id: "windbreaker-left-hood-side",
    name: "Left Hood Side",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 33,
    description:
      "Optional left hood side panel shaped around the face, crown and neckline.",
  },
  {
    id: "windbreaker-right-hood-side",
    name: "Right Hood Side",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 34,
    description:
      "Optional right hood side panel shaped around the face, crown and neckline.",
  },
  {
    id: "windbreaker-hood-facing",
    name: "Hood Opening Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 35,
    description:
      "Optional facing used to clean-finish and stabilise the hood opening.",
  },
  {
    id: "windbreaker-hood-peak",
    name: "Hood Peak",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 36,
    description:
      "Optional upper and under hood-peak pieces providing light rain and sun protection.",
  },
  {
    id: "windbreaker-hood-peak-reinforcement",
    name: "Hood Peak Reinforcement",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 37,
    description:
      "Optional stiffening insert maintaining the shape and projection of the hood peak.",
  },
  {
    id: "windbreaker-hood-drawcord-channel",
    name: "Hood Drawcord Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 38,
    description:
      "Optional casing strip containing the hood face-adjustment drawcord.",
  },
  {
    id: "windbreaker-hood-eyelet-reinforcement",
    name: "Hood Eyelet Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 39,
    description:
      "Optional reinforcement patches positioned behind hood drawcord eyelets or cord exits.",
  },
  {
    id: "windbreaker-packable-hood-pocket",
    name: "Packable Hood Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 40,
    description:
      "Optional collar or neckline pocket used to store a fold-away hood.",
  },
  {
    id: "windbreaker-left-pocket-welt",
    name: "Left Pocket Welt",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 41,
    description:
      "Pair of welt pieces forming and stabilising the left hand-pocket opening.",
  },
  {
    id: "windbreaker-right-pocket-welt",
    name: "Right Pocket Welt",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 42,
    description:
      "Pair of welt pieces forming and stabilising the right hand-pocket opening.",
  },
  {
    id: "windbreaker-left-pocket-bag",
    name: "Left Pocket Bag",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 43,
    description:
      "Pair of pocket-bag sections forming the complete left hand pocket.",
  },
  {
    id: "windbreaker-right-pocket-bag",
    name: "Right Pocket Bag",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 44,
    description:
      "Pair of pocket-bag sections forming the complete right hand pocket.",
  },
  {
    id: "windbreaker-left-pocket-flap",
    name: "Left Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 45,
    description:
      "Optional upper and under flap pieces protecting the left pocket opening.",
  },
  {
    id: "windbreaker-right-pocket-flap",
    name: "Right Pocket Flap",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 46,
    description:
      "Optional upper and under flap pieces protecting the right pocket opening.",
  },
  {
    id: "windbreaker-left-chest-pocket-bag",
    name: "Left Chest Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 47,
    description:
      "Optional pair of pocket-bag sections forming a left chest storage pocket.",
  },
  {
    id: "windbreaker-right-chest-pocket-bag",
    name: "Right Chest Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 48,
    description:
      "Optional pair of pocket-bag sections forming a right chest storage pocket.",
  },
  {
    id: "windbreaker-left-sleeve-pocket",
    name: "Left Sleeve Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 49,
    description:
      "Optional patch or zipped utility pocket positioned on the left sleeve.",
  },
  {
    id: "windbreaker-right-sleeve-pocket",
    name: "Right Sleeve Pocket",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 50,
    description:
      "Optional patch or zipped utility pocket positioned on the right sleeve.",
  },
  {
    id: "windbreaker-packable-pocket-bag",
    name: "Packable Storage Pocket Bag",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 51,
    description:
      "Optional enlarged pocket-bag sections allowing the complete jacket to pack into its own pocket.",
  },
  {
    id: "windbreaker-packable-pocket-zip-guard",
    name: "Packable Pocket Zip Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 52,
    description:
      "Optional internal guard protecting the reversible storage-pocket zip.",
  },
  {
    id: "windbreaker-left-elastic-cuff",
    name: "Left Elastic Cuff",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 53,
    description:
      "Elasticated or gathered left cuff section controlling the sleeve opening and reducing wind entry.",
  },
  {
    id: "windbreaker-right-elastic-cuff",
    name: "Right Elastic Cuff",
    required: true,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 54,
    description:
      "Elasticated or gathered right cuff section controlling the sleeve opening and reducing wind entry.",
  },
  {
    id: "windbreaker-left-cuff-tab",
    name: "Left Cuff Adjustment Tab",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 55,
    description:
      "Optional upper and under tab pieces used to adjust and secure the left sleeve opening.",
  },
  {
    id: "windbreaker-right-cuff-tab",
    name: "Right Cuff Adjustment Tab",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 56,
    description:
      "Optional upper and under tab pieces used to adjust and secure the right sleeve opening.",
  },
  {
    id: "windbreaker-left-sleeve-placket-facing",
    name: "Left Sleeve Placket Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 57,
    description:
      "Optional facing used to clean-finish and reinforce the left sleeve vent or opening.",
  },
  {
    id: "windbreaker-right-sleeve-placket-facing",
    name: "Right Sleeve Placket Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 58,
    description:
      "Optional facing used to clean-finish and reinforce the right sleeve vent or opening.",
  },
  {
    id: "windbreaker-hem-elastic-casing",
    name: "Hem Elastic Casing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 59,
    description:
      "Optional lower-edge casing containing elastic to control the jacket hem.",
  },
  {
    id: "windbreaker-hem-drawcord-channel",
    name: "Hem Drawcord Channel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 60,
    description:
      "Optional lower-edge casing containing a drawcord for fit adjustment and wind protection.",
  },
  {
    id: "windbreaker-hem-eyelet-reinforcement",
    name: "Hem Eyelet Reinforcement",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 61,
    description:
      "Optional reinforcement patches supporting hem drawcord exits or cord locks.",
  },
  {
    id: "windbreaker-left-front-hem-band",
    name: "Left Front Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 62,
    description:
      "Optional left front lower band used in bomber-style or fitted windbreaker construction.",
  },
  {
    id: "windbreaker-right-front-hem-band",
    name: "Right Front Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 63,
    description:
      "Optional right front lower band used in bomber-style or fitted windbreaker construction.",
  },
  {
    id: "windbreaker-back-hem-band",
    name: "Back Hem Band",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 64,
    description:
      "Optional back lower band used in bomber-style, elasticated or rib-finished windbreakers.",
  },
  {
    id: "windbreaker-left-front-lining",
    name: "Left Front Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 65,
    description:
      "Optional left front lining panel providing comfort and clean internal finishing.",
  },
  {
    id: "windbreaker-right-front-lining",
    name: "Right Front Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 66,
    description:
      "Optional right front lining panel providing comfort and clean internal finishing.",
  },
  {
    id: "windbreaker-back-lining",
    name: "Back Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 67,
    description:
      "Optional back lining panel covering internal seams and improving comfort.",
  },
  {
    id: "windbreaker-left-sleeve-lining",
    name: "Left Sleeve Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 68,
    description:
      "Optional left sleeve lining panel providing smooth dressing and internal seam coverage.",
  },
  {
    id: "windbreaker-right-sleeve-lining",
    name: "Right Sleeve Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 69,
    description:
      "Optional right sleeve lining panel providing smooth dressing and internal seam coverage.",
  },
  {
    id: "windbreaker-left-front-mesh-lining",
    name: "Left Front Mesh Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 70,
    description:
      "Optional breathable left front mesh lining used in sports and active windbreakers.",
  },
  {
    id: "windbreaker-right-front-mesh-lining",
    name: "Right Front Mesh Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 71,
    description:
      "Optional breathable right front mesh lining used in sports and active windbreakers.",
  },
  {
    id: "windbreaker-back-mesh-lining",
    name: "Back Mesh Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 72,
    description:
      "Optional breathable back mesh lining improving airflow and moisture management.",
  },
  {
    id: "windbreaker-left-underarm-vent",
    name: "Left Underarm Vent Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 73,
    description:
      "Optional breathable or mesh panel improving airflow beneath the left arm.",
  },
  {
    id: "windbreaker-right-underarm-vent",
    name: "Right Underarm Vent Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 74,
    description:
      "Optional breathable or mesh panel improving airflow beneath the right arm.",
  },
  {
    id: "windbreaker-back-action-pleat-left",
    name: "Left Back Action Pleat",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 75,
    description:
      "Optional left back action-pleat section providing additional shoulder and arm movement.",
  },
  {
    id: "windbreaker-back-action-pleat-right",
    name: "Right Back Action Pleat",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 76,
    description:
      "Optional right back action-pleat section providing additional shoulder and arm movement.",
  },
  {
    id: "windbreaker-left-shoulder-reflective-panel",
    name: "Left Shoulder Reflective Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 77,
    description:
      "Optional reflective or high-visibility panel positioned across the left shoulder.",
  },
  {
    id: "windbreaker-right-shoulder-reflective-panel",
    name: "Right Shoulder Reflective Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 78,
    description:
      "Optional reflective or high-visibility panel positioned across the right shoulder.",
  },
  {
    id: "windbreaker-reflective-back-panel",
    name: "Reflective Back Panel",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 79,
    description:
      "Optional reflective back panel improving wearer visibility in low-light conditions.",
  },
  {
    id: "windbreaker-reflective-sleeve-panels",
    name: "Reflective Sleeve Panels",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 80,
    description:
      "Optional reflective sleeve panels improving side visibility and safety.",
  },
  {
    id: "windbreaker-hanger-loop",
    name: "Internal Hanger Loop",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 81,
    description:
      "Optional reinforced fabric loop used to hang the windbreaker securely.",
  },
  {
    id: "windbreaker-label-backing",
    name: "Brand Label Backing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 82,
    description:
      "Optional backing patch supporting a woven, printed or heat-transfer brand label.",
  },
  {
    id: "windbreaker-decoration-backing",
    name: "Decoration Backing Patch",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 83,
    description:
      "Optional backing patches supporting embroidery, logos, badges, identification marks or heat transfers.",
  },
];

export default windbreakerPatternMaster;