import { PatternLibraryItem } from "./index";

export const womenFitAndFlareDressPatternMaster: PatternLibraryItem[] = [
  {
    id: "fit-flare-front-bodice",
    name: "Front Bodice",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 1,
    description:
      "Main fitted front upper-body panel extending from the neckline and shoulders to the waist seam.",
  },
  {
    id: "fit-flare-back-bodice",
    name: "Back Bodice",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 2,
    description:
      "Left and right fitted back upper-body panels prepared for centre-back opening or zipper construction.",
  },
  {
    id: "fit-flare-front-skirt",
    name: "Front Skirt",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 3,
    description:
      "Main flared front skirt panel joined to the front bodice at the waist seam.",
  },
  {
    id: "fit-flare-back-skirt",
    name: "Back Skirt",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 4,
    description:
      "Left and right flared back skirt panels joined at the centre-back seam and waistline.",
  },
  {
    id: "fit-flare-front-side-panel",
    name: "Front Side Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 5,
    description:
      "Optional shaped front side panels used for princess-seam fitting and improved body contour.",
  },
  {
    id: "fit-flare-back-side-panel",
    name: "Back Side Panel",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 6,
    description:
      "Optional shaped back side panels used for princess-seam construction and controlled waist fitting.",
  },
  {
    id: "fit-flare-sleeve",
    name: "Sleeve",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 7,
    description:
      "Optional left and right sleeves attached to the bodice armholes.",
  },
  {
    id: "fit-flare-sleeve-cuff",
    name: "Sleeve Cuff",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 8,
    description:
      "Optional cuff components used to finish and structure the sleeve openings.",
  },
  {
    id: "fit-flare-front-neck-facing",
    name: "Front Neck Facing",
    required: true,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 9,
    description:
      "Internal facing used to finish and stabilise the front neckline.",
  },
  {
    id: "fit-flare-back-neck-facing",
    name: "Back Neck Facing",
    required: true,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 10,
    description:
      "Left and right internal facing components used to finish the back neckline and centre-back opening.",
  },
  {
    id: "fit-flare-armhole-facing",
    name: "Armhole Facing",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 11,
    description:
      "Facing components used to finish the armholes when the dress is constructed without sleeves.",
  },
  {
    id: "fit-flare-front-waistband",
    name: "Front Waistband",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 12,
    description:
      "Optional shaped front waistband joining the bodice and skirt while defining the waistline.",
  },
  {
    id: "fit-flare-back-waistband",
    name: "Back Waistband",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 13,
    description:
      "Optional left and right back waistband components completing the defined waist construction.",
  },
  {
    id: "fit-flare-collar",
    name: "Collar",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 14,
    description:
      "Optional upper and under collar components used for collared fit-and-flare dress styles.",
  },
  {
    id: "fit-flare-collar-stand",
    name: "Collar Stand",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 15,
    description:
      "Optional inner and outer collar stand components supporting the collar around the neckline.",
  },
  {
    id: "fit-flare-front-placket",
    name: "Front Placket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 16,
    description:
      "Optional left and right front placket components used for buttoned or partially opened dress styles.",
  },
  {
    id: "fit-flare-side-seam-pocket-bag",
    name: "Side-Seam Pocket Bag",
    required: false,
    cutQuantity: 4,
    cutOnFold: false,
    custom: false,
    sequence: 17,
    description:
      "Pocket bag components forming optional concealed pockets at both side seams.",
  },
  {
    id: "fit-flare-patch-pocket",
    name: "Patch Pocket",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 18,
    description:
      "Optional external patch pockets positioned on the skirt or bodice.",
  },
  {
    id: "fit-flare-front-bodice-lining",
    name: "Front Bodice Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 19,
    description:
      "Internal front bodice lining providing comfort, opacity and a clean internal finish.",
  },
  {
    id: "fit-flare-back-bodice-lining",
    name: "Back Bodice Lining",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 20,
    description:
      "Left and right back bodice lining components matching the centre-back opening construction.",
  },
  {
    id: "fit-flare-front-skirt-lining",
    name: "Front Skirt Lining",
    required: false,
    cutQuantity: 1,
    cutOnFold: true,
    custom: false,
    sequence: 21,
    description:
      "Internal front skirt lining providing coverage, comfort and improved garment drape.",
  },
  {
    id: "fit-flare-back-skirt-lining",
    name: "Back Skirt Lining",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 22,
    description:
      "Left and right back skirt lining components joined at the centre-back seam.",
  },
  {
    id: "fit-flare-belt",
    name: "Self-Fabric Belt",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 23,
    description:
      "Optional self-fabric belt used to define and adjust the waistline.",
  },
  {
    id: "fit-flare-belt-loop",
    name: "Belt Loop",
    required: false,
    cutQuantity: 2,
    cutOnFold: false,
    custom: false,
    sequence: 24,
    description:
      "Optional belt loops positioned at the side seams to hold the self-fabric belt.",
  },
  {
    id: "fit-flare-hem-facing",
    name: "Hem Facing",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 25,
    description:
      "Separate shaped facing used for a clean and controlled finish around the flared skirt hem.",
  },
  {
    id: "fit-flare-zipper-guard",
    name: "Zipper Guard",
    required: false,
    cutQuantity: 1,
    cutOnFold: false,
    custom: false,
    sequence: 26,
    description:
      "Optional internal guard positioned beneath the centre-back zipper for comfort and protection.",
  },
];