/**
 * OptiFabric AI Pattern Geometry
 *
 * This file defines the engineering data structure used to convert an
 * uploaded pattern image into a measurable real-world geometry object.
 *
 * The geometry object will later be used by:
 *
 * - AI boundary tracing
 * - Scale calibration
 * - Pattern measurement
 * - Marker generation
 * - Fabric consumption
 * - Waste analysis
 * - Remnant reuse
 * - AI optimisation
 */

/**
 * Measurement systems supported by the geometry engine.
 */
export type GeometryMeasurementUnit =
  | "millimetre"
  | "centimetre"
  | "inch";

/**
 * Current geometry-processing stage for one pattern piece.
 */
export type PatternGeometryStatus =
  | "not-started"
  | "image-ready"
  | "calibration-required"
  | "calibrated"
  | "tracing"
  | "traced"
  | "validation-required"
  | "validated"
  | "warning"
  | "failed";

/**
 * Describes how the pattern may be positioned inside a marker.
 */
export type PatternRotationRule =
  | "fixed"
  | "180-only"
  | "90-allowed"
  | "free-rotation";

/**
 * Describes whether the pattern must be mirrored during cutting.
 */
export type PatternMirrorRule =
  | "none"
  | "mirror-pair"
  | "optional"
  | "prohibited";

/**
 * Directional restrictions created by the fabric or garment design.
 */
export type PatternDirectionRule =
  | "non-directional"
  | "one-way"
  | "two-way"
  | "nap-direction"
  | "stripe-direction"
  | "check-direction";

/**
 * Confidence classification used for management-facing reports.
 */
export type GeometryConfidenceLevel =
  | "very-low"
  | "low"
  | "medium"
  | "high"
  | "very-high";

/**
 * A single point recorded from the uploaded pattern image.
 *
 * x and y are image-space pixel coordinates.
 *
 * realX and realY are optional real-world coordinates calculated after
 * successful scale calibration.
 */
export interface PatternGeometryPoint {
  id: string;

  x: number;
  y: number;

  realX?: number;
  realY?: number;

  sequence: number;
}

/**
 * Bounding rectangle surrounding the traced pattern.
 */
export interface PatternBoundingBox {
  minimumX: number;
  minimumY: number;
  maximumX: number;
  maximumY: number;

  widthPixels: number;
  heightPixels: number;

  widthReal?: number;
  heightReal?: number;

  unit?: GeometryMeasurementUnit;
}

/**
 * Scale-reference information detected or entered for the uploaded image.
 */
export interface PatternScaleCalibration {
  calibrated: boolean;

  referenceLength: number;
  referenceUnit: GeometryMeasurementUnit;

  referencePixelLength: number;

  pixelsPerUnit: number;
  unitsPerPixel: number;

  startPoint?: PatternGeometryPoint;
  endPoint?: PatternGeometryPoint;

  calibrationMethod:
    | "manual-two-point"
    | "detected-ruler"
    | "detected-scale"
    | "document-size"
    | "not-calibrated";

  confidenceScore: number;

  calibratedAt?: string;
}

/**
 * Grain-line information attached to one pattern piece.
 */
export interface PatternGrainLine {
  detected: boolean;

  startPoint?: PatternGeometryPoint;
  endPoint?: PatternGeometryPoint;

  angleDegrees?: number;

  directionRule: PatternDirectionRule;

  confidenceScore: number;
}

/**
 * Engineering measurements calculated from the traced polygon.
 */
export interface PatternGeometryMeasurements {
  unit: GeometryMeasurementUnit;

  width: number;
  height: number;

  perimeter: number;
  area: number;

  areaSquareMillimetres: number;
  areaSquareCentimetres: number;
  areaSquareInches: number;
  areaSquareMetres: number;

  boundingBox: PatternBoundingBox;
}

/**
 * Geometry-quality warning generated by the validation engine.
 */
export interface PatternGeometryWarning {
  id: string;

  code:
    | "insufficient-points"
    | "open-boundary"
    | "self-intersection"
    | "missing-scale"
    | "invalid-scale"
    | "zero-area"
    | "unrealistic-size"
    | "missing-grain-line"
    | "low-confidence"
    | "image-not-available"
    | "duplicate-point"
    | "other";

  severity: "information" | "warning" | "critical";

  title: string;
  message: string;

  resolved: boolean;
}

/**
 * Complete validation result for one pattern geometry.
 */
export interface PatternGeometryValidation {
  valid: boolean;

  boundaryClosed: boolean;
  minimumPointsSatisfied: boolean;
  scaleValid: boolean;
  areaValid: boolean;
  dimensionsValid: boolean;
  selfIntersectionFree: boolean;
  grainLineValid: boolean;

  warnings: PatternGeometryWarning[];

  validatedAt?: string;
}

/**
 * AI confidence result for one traced pattern.
 */
export interface PatternGeometryConfidence {
  score: number;
  level: GeometryConfidenceLevel;

  imageQualityScore: number;
  scaleConfidenceScore: number;
  boundaryConfidenceScore: number;
  measurementConfidenceScore: number;
  grainLineConfidenceScore: number;

  explanation: string[];
}

/**
 * Polygon created from the traced pattern boundary.
 */
export interface PatternGeometryPolygon {
  points: PatternGeometryPoint[];

  closed: boolean;

  pixelArea: number;
  pixelPerimeter: number;

  signedPixelArea: number;

  clockwise: boolean;

  createdAt: string;
  updatedAt: string;
}

/**
 * Complete AI Engineering Digital Twin for one pattern piece.
 */
export interface PatternGeometry {
  id: string;

  projectId: string;
  patternId: string;
  patternName: string;

  sourceImageUrl?: string;
  sourceFileName?: string;

  status: PatternGeometryStatus;

  polygon: PatternGeometryPolygon;

  calibration: PatternScaleCalibration;

  measurements?: PatternGeometryMeasurements;

  grainLine: PatternGrainLine;

  rotationRule: PatternRotationRule;
  mirrorRule: PatternMirrorRule;
  directionRule: PatternDirectionRule;

  cutQuantity: number;
  cutOnFold: boolean;

  validation: PatternGeometryValidation;

  confidence: PatternGeometryConfidence;

  markerReady: boolean;

  engineeringNotes: string[];

  createdAt: string;
  updatedAt: string;
}

/**
 * Input required to create a new geometry record.
 */
export interface CreatePatternGeometryInput {
  projectId: string;

  patternId: string;
  patternName: string;

  sourceImageUrl?: string;
  sourceFileName?: string;

  cutQuantity?: number;
  cutOnFold?: boolean;

  rotationRule?: PatternRotationRule;
  mirrorRule?: PatternMirrorRule;
  directionRule?: PatternDirectionRule;
}

/**
 * Creates an empty geometry object for one uploaded pattern.
 *
 * This allows every uploaded pattern to enter the geometry workflow even
 * before calibration or tracing has started.
 */
export function createEmptyPatternGeometry(
  input: CreatePatternGeometryInput
): PatternGeometry {
  const now = new Date().toISOString();

  return {
    id: `${input.projectId}-${input.patternId}-geometry`,

    projectId: input.projectId,
    patternId: input.patternId,
    patternName: input.patternName,

    sourceImageUrl: input.sourceImageUrl,
    sourceFileName: input.sourceFileName,

    status: input.sourceImageUrl
      ? "image-ready"
      : "not-started",

    polygon: {
      points: [],
      closed: false,
      pixelArea: 0,
      pixelPerimeter: 0,
      signedPixelArea: 0,
      clockwise: false,
      createdAt: now,
      updatedAt: now,
    },

    calibration: {
      calibrated: false,
      referenceLength: 0,
      referenceUnit: "inch",
      referencePixelLength: 0,
      pixelsPerUnit: 0,
      unitsPerPixel: 0,
      calibrationMethod: "not-calibrated",
      confidenceScore: 0,
    },

    grainLine: {
      detected: false,
      directionRule:
        input.directionRule ?? "non-directional",
      confidenceScore: 0,
    },

    rotationRule:
      input.rotationRule ?? "180-only",

    mirrorRule:
      input.mirrorRule ?? "none",

    directionRule:
      input.directionRule ?? "non-directional",

    cutQuantity:
      input.cutQuantity && input.cutQuantity > 0
        ? input.cutQuantity
        : 1,

    cutOnFold: input.cutOnFold ?? false,

    validation: {
      valid: false,
      boundaryClosed: false,
      minimumPointsSatisfied: false,
      scaleValid: false,
      areaValid: false,
      dimensionsValid: false,
      selfIntersectionFree: true,
      grainLineValid: false,
      warnings: [],
    },

    confidence: {
      score: 0,
      level: "very-low",
      imageQualityScore: 0,
      scaleConfidenceScore: 0,
      boundaryConfidenceScore: 0,
      measurementConfidenceScore: 0,
      grainLineConfidenceScore: 0,
      explanation: [
        "Pattern geometry has not yet been processed.",
      ],
    },

    markerReady: false,

    engineeringNotes: [],

    createdAt: now,
    updatedAt: now,
  };
}

/**
 * Restricts a confidence score to the supported range of 0–100.
 */
export function clampGeometryConfidenceScore(
  score: number
): number {
  if (!Number.isFinite(score)) {
    return 0;
  }

  return Math.min(100, Math.max(0, score));
}

/**
 * Converts a numerical confidence score into a management-facing level.
 */
export function getGeometryConfidenceLevel(
  score: number
): GeometryConfidenceLevel {
  const safeScore =
    clampGeometryConfidenceScore(score);

  if (safeScore >= 90) {
    return "very-high";
  }

  if (safeScore >= 75) {
    return "high";
  }

  if (safeScore >= 55) {
    return "medium";
  }

  if (safeScore >= 30) {
    return "low";
  }

  return "very-low";
}

/**
 * Produces a stable point ID for manually or automatically traced points.
 */
export function createPatternGeometryPointId(
  patternId: string,
  sequence: number
): string {
  return `${patternId}-point-${sequence}`;
}

/**
 * Creates one polygon point from image-space coordinates.
 */
export function createPatternGeometryPoint(
  patternId: string,
  x: number,
  y: number,
  sequence: number
): PatternGeometryPoint {
  return {
    id: createPatternGeometryPointId(
      patternId,
      sequence
    ),
    x,
    y,
    sequence,
  };
}

export default PatternGeometry;