export type GpaRole =
  | "SUPER_ADMIN"
  | "GROUP_EXECUTIVE"
  | "FACTORY_DIRECTOR"
  | "GENERAL_MANAGER"
  | "PRODUCTION_MANAGER"
  | "IE_MANAGER"
  | "QUALITY_MANAGER"
  | "CUTTING_MANAGER"
  | "MERCHANDISER"
  | "STORE_MANAGER"
  | "MAINTENANCE_MANAGER"
  | "HR_MANAGER"
  | "VIEWER";

export type GpaPermission =
  | "VIEW_EXECUTIVE_DASHBOARD"
  | "VIEW_COMMAND_CENTRE"
  | "VIEW_CUTTING"
  | "VIEW_FABRIC"
  | "VIEW_PRODUCTION"
  | "VIEW_SHIPMENT"
  | "VIEW_FINANCE"
  | "MANAGE_USERS"
  | "MANAGE_FACTORIES";

export const gpaRolePermissions: Record<
  GpaRole,
  GpaPermission[]
> = {
  SUPER_ADMIN: [
    "VIEW_EXECUTIVE_DASHBOARD",
    "VIEW_COMMAND_CENTRE",
    "VIEW_CUTTING",
    "VIEW_FABRIC",
    "VIEW_PRODUCTION",
    "VIEW_SHIPMENT",
    "VIEW_FINANCE",
    "MANAGE_USERS",
    "MANAGE_FACTORIES",
  ],

  GROUP_EXECUTIVE: [
    "VIEW_EXECUTIVE_DASHBOARD",
    "VIEW_COMMAND_CENTRE",
    "VIEW_CUTTING",
    "VIEW_FABRIC",
    "VIEW_PRODUCTION",
    "VIEW_SHIPMENT",
  ],

  FACTORY_DIRECTOR: [
    "VIEW_EXECUTIVE_DASHBOARD",
    "VIEW_COMMAND_CENTRE",
    "VIEW_CUTTING",
    "VIEW_FABRIC",
    "VIEW_PRODUCTION",
  ],

  GENERAL_MANAGER: [
    "VIEW_COMMAND_CENTRE",
    "VIEW_CUTTING",
    "VIEW_FABRIC",
    "VIEW_PRODUCTION",
  ],

  PRODUCTION_MANAGER: [
    "VIEW_PRODUCTION",
  ],

  IE_MANAGER: [
    "VIEW_PRODUCTION",
  ],

  QUALITY_MANAGER: [
    "VIEW_FABRIC",
  ],

  CUTTING_MANAGER: [
    "VIEW_CUTTING",
  ],

  MERCHANDISER: [
    "VIEW_SHIPMENT",
  ],

  STORE_MANAGER: [
    "VIEW_FABRIC",
  ],

  MAINTENANCE_MANAGER: [
    "VIEW_PRODUCTION",
  ],

  HR_MANAGER: [
    "VIEW_EXECUTIVE_DASHBOARD",
  ],

  VIEWER: [
    "VIEW_EXECUTIVE_DASHBOARD",
  ],
};