import { GPALineOperationInput } from "./gpaLineBalancingEngine";

export const gpaSampleLineBalancingData: GPALineOperationInput[] = [
  {
    operationId: "OP-001",
    operationName: "Shoulder Join",
    operatorName: "Rahim",
    smv: 0.72,
    actualCycleTime: 0.95,
    hourlyTarget: 85,
    hourlyOutput: 62,
    skillLevel: "MEDIUM",
  },
  {
    operationId: "OP-002",
    operationName: "Sleeve Attach",
    operatorName: "Karim",
    smv: 0.88,
    actualCycleTime: 0.87,
    hourlyTarget: 70,
    hourlyOutput: 69,
    skillLevel: "HIGH",
  },
  {
    operationId: "OP-003",
    operationName: "Side Seam",
    operatorName: "Fatema",
    smv: 0.65,
    actualCycleTime: 0.55,
    hourlyTarget: 95,
    hourlyOutput: 118,
    skillLevel: "EXPERT",
  },
  {
    operationId: "OP-004",
    operationName: "Bottom Hem",
    operatorName: "Nasima",
    smv: 0.80,
    actualCycleTime: 1.18,
    hourlyTarget: 75,
    hourlyOutput: 48,
    skillLevel: "LOW",
  },
  {
    operationId: "OP-005",
    operationName: "Final Inspection",
    operatorName: "Jamal",
    smv: 1.10,
    actualCycleTime: 1.08,
    hourlyTarget: 52,
    hourlyOutput: 51,
    skillLevel: "HIGH",
  },
];