"use client";
import DashboardShell from "@/components/software/DashboardShell";
import RiskBadge from "@/components/software/RiskBadge";

import { exponentialSmoothing } from "@/lib/software/forecasting";
import { calculatePerformanceScore } from "@/lib/software/scoring";
import { assessRisk } from "@/lib/software/riskEngine";
import {
  generateForecastObservation,
  generateOperationalObservation,
  generateExecutiveSummary,
} from "@/lib/software/aiObservations";

export default function ExecutiveReportGeneratorPage() {
  const productionForecast = exponentialSmoothing([
    { period: "Jan", actual: 78 },
    { period: "Feb", actual: 82 },
    { period: "Mar", actual: 85 },
    { period: "Apr", actual: 87 },
    { period: "May", actual: 90 },
  ]);

  const score = calculatePerformanceScore([88, 84, 79, 91, 86]);
  const risk = assessRisk(score.score, "Overall Factory Operations");

  const operationalObservation = generateOperationalObservation(
    "Overall Factory Operations",
    score,
    risk
  );

  const forecastObservation = generateForecastObservation(
    "Production Forecast",
    productionForecast
  );

  const executiveSummary = generateExecutiveSummary("MBNCON Demo Factory", [
    operationalObservation,
    forecastObservation,
  ]);

  return (
    <DashboardShell
      title="Executive Report Generator"
      subtitle="Generate print-ready executive intelligence reports using scoring, forecasting, risk engine, and AI consultancy observations."
    >
      <div className="rounded-3xl border border-neutral-200 bg-white p-8 shadow-sm print:border-0 print:shadow-none">
        <div className="mb-10 rounded-3xl border border-cyan-200 bg-cyan-50 p-8">
  <p className="text-sm font-bold uppercase tracking-[0.25em] text-cyan-700">
    Confidential Executive Intelligence Report
  </p>

  <h1 className="mt-4 text-5xl font-black tracking-tight text-neutral-950">
    Manufacturing Intelligence Assessment
  </h1>

  <p className="mt-6 max-w-4xl text-lg leading-9 text-neutral-700">
    AI-powered operational intelligence report generated from production,
    manpower, wastage, export, utilities, maintenance, forecasting,
    and executive risk analysis systems.
  </p>

  <div className="mt-8 grid gap-5 md:grid-cols-4">
    <MetaCard label="Factory" value="MBNCON Demo Factory" />
    <MetaCard label="Period" value="May 2026" />
    <MetaCard label="Report Type" value="Executive Intelligence" />
    <MetaCard label="Generated By" value="MBNCON AI Engine" />
  </div>
</div>
        <div className="flex flex-wrap items-start justify-between gap-6 border-b border-neutral-200 pb-6">
          <div>
            <p className="text-sm font-semibold uppercase tracking-widest text-cyan-700">
              MBNCON Manufacturing Intelligence Platform
            </p>

            <h1 className="mt-3 text-4xl font-bold text-neutral-950">
              Executive Intelligence Report
            </h1>

            <p className="mt-3 text-neutral-600">
              Factory: MBNCON Demo Factory • Period: May 2026
            </p>
          </div>

          <RiskBadge level={risk.level} />
        </div>

        <section className="mt-8 grid gap-6 md:grid-cols-4">
          <ReportMetric label="Overall Score" value={`${score.score}%`} />
          <ReportMetric label="Grade" value={score.grade} />
          <ReportMetric label="Forecast Accuracy" value={`${productionForecast.averageAccuracy}%`} />
          <ReportMetric label="Next Forecast" value={`${productionForecast.nextForecast}%`} />
        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-bold text-neutral-950">
            Executive Summary
          </h2>

          <p className="mt-4 text-base leading-8 text-neutral-700">
            {executiveSummary}
          </p>
        </section>

        <section className="mt-10 grid gap-6 lg:grid-cols-2">
          <ReportBox
            title={operationalObservation.title}
            body={operationalObservation.summary}
            recommendation={operationalObservation.recommendation}
          />

          <ReportBox
            title={forecastObservation.title}
            body={forecastObservation.summary}
            recommendation={forecastObservation.recommendation}
          />
        </section>

        <section className="mt-10 rounded-2xl bg-neutral-50 p-6">
          <h2 className="text-2xl font-bold text-neutral-950">
            Management Action Plan
          </h2>

          <ul className="mt-5 space-y-3 text-sm leading-7 text-neutral-700">
            <li>• Review department-level productivity and delay trends.</li>
            <li>• Compare forecasted output with manpower and machine capacity.</li>
            <li>• Investigate wastage, rework, downtime, and absenteeism patterns.</li>
            <li>• Assign responsible owners for each high-risk operational area.</li>
            <li>• Re-run executive review after next reporting period.</li>
          </ul>
        </section>

        <div className="mt-10 flex justify-end print:hidden">
          <button
            onClick={() => window.print()}
            className="rounded-2xl bg-black px-6 py-4 text-sm font-bold text-white hover:bg-neutral-800"
          >
            Print / Save PDF
          </button>
        </div>
      </div>
      <div className="mt-16 grid gap-6 border-t border-neutral-200 pt-10 md:grid-cols-3">
  <SignatureBox
    title="Prepared By"
    name="MBNCON Intelligence Engine"
  />

  <SignatureBox
    title="Reviewed By"
    name="Executive Management"
  />

  <SignatureBox
    title="Approved By"
    name="Managing Director"
  />
</div>
    </DashboardShell>
  );
}

function ReportMetric({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5">
      <p className="text-xs font-semibold uppercase tracking-widest text-neutral-500">
        {label}
      </p>
      <p className="mt-3 text-3xl font-bold text-neutral-950">{value}</p>
    </div>
  );
}

function ReportBox({
  title,
  body,
  recommendation,
}: {
  title: string;
  body: string;
  recommendation: string;
}) {
  return (
    <div className="rounded-2xl border border-neutral-200 bg-white p-6">
      <h3 className="text-xl font-bold text-neutral-950">{title}</h3>

      <p className="mt-4 text-sm leading-7 text-neutral-700">{body}</p>

      <div className="mt-5 rounded-xl bg-cyan-50 p-4">
        <p className="text-sm font-bold text-cyan-800">Recommendation</p>
        <p className="mt-2 text-sm leading-7 text-cyan-900">
          {recommendation}
        </p>
      </div>
    </div>
  );
}
function MetaCard({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div className="rounded-2xl border border-cyan-200 bg-white p-5">
      <p className="text-xs font-bold uppercase tracking-wide text-cyan-700">
        {label}
      </p>

      <p className="mt-3 text-base font-semibold text-neutral-900">
        {value}
      </p>
    </div>
  );
}

function SignatureBox({
  title,
  name,
}: {
  title: string;
  name: string;
}) {
  return (
    <div className="rounded-2xl border border-neutral-200 p-6">
      <p className="text-xs font-bold uppercase tracking-wide text-neutral-500">
        {title}
      </p>

      <div className="mt-16 border-t border-neutral-400 pt-3">
        <p className="text-sm font-semibold text-neutral-900">
          {name}
        </p>
      </div>
    </div>
  );
}